### ISSUE TITLE
Get hostname by script

### ISSUE THREAD

**Issue by danielmotaleite** [backuppc/backuppc#100]
I need to run a script to detect what node is the current master, so i can execute the backup on that node.

I tried to hack this using `$NmbLookupFindHostCmd`  and almost done that, but then backuppc tried to do the reverse lookup and that will fail, as the reverse only gets the IP and gives no feedback what was the original cluster name. I also found that dump will later still use the backup name ($host), not the ip returned by the nmblookup

I also checked the https://github.com/backuppc/backuppc/pull/94 , but multiple entries will not help, the machines are all up and the first one may not be the master. The only workaround i have now is a cron changing the (clustername).pl  config file, but it is very a dirty hack and prone to fail.

So please add a option `$ClientNameAliasCmd` , where it runs with the backup $host variable as input to return a single line with the hostname/IP to be used just like it was the `$ClientNameAlias` (that basically overwrite any set `$ClientNameAlias`)

I tried to look to the code... but yep, my coding skills are too weak for this

Thanks

**Comment by adamgoryachev** [comment]
On 21/4/17 00:49, Daniel Mota Leite wrote:
>
> I need to run a script to detect what node is the current master, so i 
> can execute the backup on that node.
>
> I tried to hack this using |$NmbLookupFindHostCmd| and almost done 
> that, but then backuppc tried to do the reverse lookup and that will 
> fail, as the reverse only gets the IP and gives no feedback what was 
> the original cluster name. I also found that dump will later still use 
> the backup name ($host), not the ip returned by the nmblookup
>
> I also checked the #94 <https://github.com/backuppc/backuppc/pull/94> 
> , but multiple entries will not help, the machines are all up and the 
> first one may not be the master. The only workaround i have now is a 
> cron changing the (clustername).pl config file, but it is very a dirty 
> hack and prone to fail.
>
> So please add a option |$ClientNameAliasCmd| , where it runs with the 
> backup $host variable as input to return a single line with the 
> hostname/IP to be used just like it was the |$ClientNameAlias| (that 
> basically overwrite any set |$ClientNameAlias|)
>
> I tried to look to the code... but yep, my coding skills are too weak 
> for this
>
> Thanks
>
Hi Daniel,

You may have already considered this, but generally when using a 
master/slave configuration, you would have a "floating" IP address, 
which will always point to the master. Thus, if you point the backups to 
the floating IP address, then you will always backup the correct 
machine. If you want to use DNS, then simply set the DNS name to point 
to the floating IP.

I hope this helps.
Regards,
Adam

**Comment by ngharo** [comment]
see #102 regarding the netbios mismatch check

**Comment by craigbarratt** [comment]
Applied pr #102 which should allow you to turn off the reverse lookup.

**Comment by danielmotaleite** [comment]
Thanks @ngharo and @craigbarratt  , using $NmbLookupCmd  as the script should work fine now!

And by the way, yes, we have a "master IP", but it is used and managed by haproxy, so i can not use it directly as the haproxy is another machine without DBs... that is why i need the script :)

We will probably redo this later, but for now your fix looks perfect! thanks for the help!
