### ISSUE TITLE
backuppc configure.pl wrote ping6 path without single quotes

### ISSUE THREAD

**Issue by JacksonTech** [backuppc/backuppc#107]
My old backuppc 3 configuration file did not have ping6's path set. I attempted an in place upgrade from 3 to 4 by feeding configure.pl the old config file. 

After setting everything up, the BackupPC_migrateV3toV4 script failed with:

```
Couldn't execute /etc/backuppc/config.pl: Unknown regexp modifier "/6" at /etc/backuppc/config.pl line 2279, at end of line
BackupPC::Lib->new failed
```

This is because my ping6 path location is now:
`$Conf{Ping6Path} = /bin/ping6;`

(note the missing single quotes around the path).

Adding the single quotes seems to have fixed it!

**Comment by moisseev** [comment]
@JacksonTech, I can't reproduce your issue.  What BackupPC 4 version are you using? How did you install it (from git source, release tarball or some package)? What "did not have ping6's path set" exactly mean? There is no `$Conf{Ping6Path}` in the config.pl at all, `$Conf{Ping6Path} = '';` or `$Conf{Ping6Path} = undef;` ? How you did that "feeding"?

**Comment by JacksonTech** [comment]
@moisseev Sorry, let me see if I can get all that info for you.

BackupPC version (old): 3.3.1-2ubuntu3 (from Ubuntu 16.04 repos)
BackupPC version (new): 4.1.2

Installed from release tarball.

The old config contained:
$Conf{Ping6Path} = undef;

By "feeding" I mean I started configure.pl (as root) and, when asked for the full path to my config.pl, I provided the one from the old BackupPC version.

configure.pl automatically detected the path to ping6 and filled it in. However, there were other programs (rrdtool, rsync_bpc) that I had installed a day or two ago and those were not automatically detected. I typed in the paths manually as prompted and these config entries were properly populated. For example, my 4.x config.pl ended up with this:

$Conf{RsyncBackupPCPath} = "/usr/local/bin/rsync_bpc";

So, maybe this only happens under the following conditions:
1. Upgrading from BackupPC 3.x
2. Passing in a config.pl file that has ping6's path (or other program's path) set to undef
3. config.pl attempts to auto-detect the undef'd programs and doesn't properly insert the 's or "s around then

It DOESN'T seem to happen if I manually typed in the path myself, or if there was no key in the first place in the old config file. 

For instance, there was no key for the path to rrdtool in my 3.x config file, so I had to type it in myself, and the rrdtool line got properly added. Same situation with rsync_bpc's path.

I won't have time to do much digging for a few days, but let me know if I can give you more information from my setup.

**Comment by moisseev** [comment]
> config.pl attempts to auto-detect the undef'd programs and doesn't properly insert the 's or "s around then

Unfortunately `configure.pl` knows nothing about `$Conf{}` variable types. So it inserts unquoted values. But if it found a quoted value in `config.pl` then it updates the value inside the quotes and leaves the quotes intact.

In order for it to work properly you need to ensure empty strings (`''`) are used for string values and `undef` for others. For instance there should be `$Conf{Ping6Path} = '';` instead of `$Conf{Ping6Path} = undef;`

Regarding installed programs detection, is `/usr/local/bin` included in your `PATH` environment variable? If not, https://github.com/backuppc/backuppc/pull/109 should fix program detection.

**Comment by JacksonTech** [comment]
What would be the proper fix (assuming the user isn't savvy enough to put in the ''s themselves)? A pre-pass to replace certain the undef'd $Conf{} directives that should be strings with ''? Or a warning in the readme/install file to tell the user to do it themselves?

Not sure how undef got in there in the first place--might've been me fat fingering or it might've been an older installer (or the Ubuntu package). 

Regarding #109, I can give that a test when the next release drops as I still have the old config file available.

**Comment by moisseev** [comment]
https://github.com/backuppc/backuppc/pull/114 should fix the issue with misused `undef`.
