### ISSUE TITLE
Make SCGI server listening on localhost instead of 0.0.0.0

### ISSUE THREAD

**Issue by Shadow4711** [backuppc/backuppc#110]
Hello,

please change
`my $socket = IO::Socket::INET->new(Listen => 5, ReuseAddr => 1, LocalPort => $Conf{SCGIServerPort} || 8199)`
to
`my $socket = IO::Socket::INET->new(Listen => 5, ReuseAddr => 1, LocalAddr => 'localhost', LocalPort => $Conf{SCGIServerPort} || 8199)`

in BackupPC_Admin_SCGI to improve security.

Regards
Shadow4711

**Comment by craigbarratt** [comment]
Fixed in commit 44b68bf.
