### ISSUE TITLE
--one-file-system unexpectedly added to RsyncArgs on upgrade from 3.x

### ISSUE THREAD

**Issue by JacksonTech** [backuppc/backuppc#113]
My fault for not reading the Changelog, but I was really not expecting to see --one-file-system added to my rsync arguments when passing an existing config.pl file to configure.pl (by way of providing the full path name when running configure.pl as root). It led to an amusing morning of troubleshooting when my backups were suddenly a few hundred GB lighter than expected.

Could we add a warning when upgrading from an old installation where this config option is not present? Or make it optional?

**Comment by craigbarratt** [comment]
Cody,

I'll update configure.pl so that on an upgrade it doesn't add
--one-file-system if it isn't already present.

A clean V4 install will get the --one-file-system setting.

Craig
