### ISSUE TITLE
backup failed (No files dumped for share XXX)

### ISSUE THREAD

**Issue by hiscal2015** [backuppc/backuppc#120]
Hi, 

I'm using backuppc 4.1.2, and found backuppc will report backup failed if the target folder was empty. I think this should be a waning but not a failed event, in some scenario to backup an empty folder is expected, for example, an etcd cluster, the master will backup data to current host but not on slave hosts, when master down, one slave becomes master and backup data to the new master host, so backup server should monitor target backup folder on all etcd nodes.

**Comment by moisseev** [comment]
You can set `$Conf{BackupZeroFilesIsFatal} = 0;`
https://backuppc.github.io/backuppc/BackupPC.html#What-to-backup-and-when-to-do-it

**Comment by hiscal2015** [comment]
@moisseev Thanks, this is exactly what I want!
