### ISSUE TITLE
error in rsync protocol data stream (code 12) at io.c(629) when using rsync --compression

### ISSUE THREAD

**Issue by johanehnberg** [backuppc/backuppc#122]
Tested and present at least on BackupPC 4.1.2 - 4.1.3, bpc-rsync 3.0.9.6 - 3.0.9.7 and BackupPC-XS 0.53 - 0.55.

# Key triggers

- occurs only when --compress in is used in RsyncArgs
- occurs only for subsequent backups to the same pool files
- the first backup (#0) always succeeds
- switching between pool and cpool through Compression 0 and 1-9 also circumvents the error

In all other cases, backups complete fine.

# Workaround

Instead of --compress (or any of its synonyms, regardless of compression levels) in RsyncArgs, add -C to RsyncSshArgs. This does not allow for adjusting compression levels, however.

**Comment by craigbarratt** [comment]
This should be an issue for rsync-bpc, not backuppc.

I've been able to replicate this.  It appears this is a bug from standard rsync related to using the OS's zlib, versus the included zlib.  See: https://bugs.launchpad.net/ubuntu/+source/rsync/+bug/1300367.

Use of the OS's zlib is encouraged by security practices, vs using the included one.  But it breaks rsync --compression.

**Comment by johanehnberg** [comment]
I was still able to reproduce this with rsync 3.1.2 on the target and rsync-bpc 3.1.2 on the server.

**Comment by craigbarratt** [comment]
Can you confirm the steps you took to build rsync-bpc-3.1.2.  In particular, what configure options did you use?

**Comment by johanehnberg** [comment]
As close to vanilla as possible:
  wget https://github.com/backuppc/rsync-bpc/releases/download/$rsyncbpcver/rsync-bpc-3.1.2.0.tar.gz
  tar -zxf rsync-bpc-3.1.2.0.tar.gz
  cd rsync-bpc-3.1.2.0
  ./configure
  make
  make install
