### ISSUE TITLE
Windows 10 rsync

### ISSUE THREAD

**Issue by arturomj** [backuppc/backuppc#126]
Hi! 
I definitely don't know how to solve my problem with backuppc. First of all, I have two host making backups with backuppc hosted in my OdroidXU4 running ubuntu. Both hosts are running GNU/Linux an I can make the backups without problem, works great.

The problem is with windows 10. I have installed ssh, rsync with cygwin.

If I run from windows:

rsync -av --delete -e 'ssh -p 1111' /cygdrive/c/.../ user@mydomain:/...

It works great, but I have tested so many ways in backuppc and no one works. 

The common error is "(fileListReceive failed)"

In "RsyncClientCmd" I have:
$sshPath -p 1111 -l USER $host $rsyncPath $argList+

In "RsyncShareName": /cygdrive/c/...

any help?

**Comment by craigbarratt** [comment]
Please post this to the user email list.  You should include the version numbers you are running. And you should include some information from the XferLOG file.

 Github issues are for things related to code development (bugs, features etc).
