### ISSUE TITLE
RPM package

### ISSUE THREAD

**Issue by prupert** [backuppc/backuppc#127]
Is anyone willing to build and maintain RPM packages for BackupPC v4 on RHEL/CentOS? 

Some help is desired by the current maintainer of the v3 package in EPEL. See https://bugzilla.redhat.com/show_bug.cgi?id=1464121 and https://copr.fedorainfracloud.org/coprs/hobbes1069/BackupPC/

**Comment by SpareSimian** [comment]
Use the one in the Hobbes1069 repo. Use the EPEL package. It installs and runs fine on CentOS 7 and I'm sure it will work fine on CentOS 6.

**Comment by prupert** [comment]
I completely overlooked the progress in the Hobbes1069 repo, thank you for pointing that out.
