### ISSUE TITLE
restore .tar / .zip files empty

### ISSUE THREAD

**Issue by rmu75** [backuppc/backuppc#128]
Restore results in empty .tar / .zip files being downloaded.
Investigation reveals that perl complains about 
`Insecure dependency in open while running setuid at /usr/share/backuppc/lib/BackupPC/Storage/Text.pm line 74.
`
Inserting this snippet
```
    if ($host =~ /^([-\@\w.]+)$/) {
        $host = $1;                     # $host now untainted
    } else {
        die "Bad data in '$host'";      # log this somewhere
    }
```
before gets rid of the error. I'm not a perl programmer, I don't know how to debug this further, but it seems $host is tainted for whatever reason.

**Comment by craigbarratt** [comment]
I pushed a commit 6f01264005310cffe55d5258436d38609a1ac99d that should fix the problem.

**Comment by craigbarratt** [comment]
Just pushed some minor fixes to last commit; 0439411cc17757e5f15ebfbff902aacc3d4510b6

**Comment by prupert** [comment]
@craigbarratt: the last release of BackupPC (4.1.3) does not contain this fix. Since this bug is rather annoying (end-users can't download backups), would you be willing to release a new version with this fix?

**Comment by jeancf** [comment]
Same request here. It is a pretty important functionality that does not work.

**Comment by hobbes1069** [comment]
You didn't mention what version you're running. Have you updated to 4.1.4 yet?

**Comment by jeancf** [comment]
I had not noticed that a 4.1.4 was available. I am on arch linux and the repo is still on 4.1.3. I will check it out. Thanks.
