### ISSUE TITLE
Wiki for BackupPC 4 on Ubuntu Xenial 16.04 LTS change default Apache User

### ISSUE THREAD

**Issue by norac89** [backuppc/backuppc#129]
Instructions from the Wiki _Installing BackupPC 4 from git on Ubuntu Xenial 16.04 LTS_  are changing the default Apache user and group (www-data).  This cause other web applications depending on this user to stop working. 
```
sed -i "s/export APACHE_RUN_USER=www-data/export APACHE_RUN_USER=backuppc/" /etc/apache2/envvars
sed -i "s/export APACHE_RUN_GROUP=www-data/export APACHE_RUN_GROUP=backuppc/" /etc/apache2/envvars
```

**Comment by craigbarratt** [comment]
Updated the Wiki script with a comment prior to these two lines.
