### ISSUE TITLE
Hosts with IPV6 can't ping via backuppc - ping on linux CMD works fine

### ISSUE THREAD

**Issue by boospy** [backuppc/backuppc#130]
Hello, 

we are running backuppc on all us customers long years. So last week we changed us linuxserver to IPV6 only. Since this backuppc was not able to do some backup. The error message in the logs are aloways the same:
`2017-07-08 01:06:58 Can't find host benno.tuxi.local via netbios`
This is very strange. Why would backuppc resolve the hosts with netbios. All hosts are in public dns resolvable. And there is no windows and no samba at the servers. 

For a little hack i've changed somethin in config.pl:
```
..
#$Conf{NmbLookupPath} = '/usr/bin/nmblookup';
$Conf{NmbLookupPath} = '/bin/ping';
..
#$Conf{NmbLookupCmd} = '$nmbLookupPath -A $host';
$Conf{NmbLookupCmd} = '$nmbLookupPath $host';
..
```
But this has no effect. Does Backuppc not support IPV6?
System: Debian Stretch with Backuppc 3.3.1-4

Best Regards and Thanks

**Comment by craigbarratt** [comment]
3.x doesn't support ipv6.  4.x should.  The changes were minor (ping changes to ping6, and hostname lookup needs to be updated).  It should be possible, if you don't want to upgrade, to make the corresponding changes in 3.x.

The netbios error is just the fallback it does when hostname lookup doesn't work.

**Comment by boospy** [comment]
Ok, thank you for the answer. I have a look, maybe an Upgrade from 3 to 4 is possible in actual Debian stretch. 

The ping should not be the problem. The host are all pingable over the hostname. And there is no more ping6, only ping.

**Comment by boospy** [comment]
Hello :)
i followed the instructions: https://github.com/backuppc/backuppc/wiki/Build-Your-Own-Packages
to build my packages, it has worked perfectly. So also IPV6 work with version 4.X great. 

Thank you :+1:

**Comment by nosilver4u** [comment]
@craigbarratt, you mentioned "hostname lookup" that needs to be updated. So far all I've had to do on Debian Buster is define the ping6 path (Ping6Path = /usr/bin/ping6). Could there be something else missing?
For reference, Debian Buster has BackupPC 3.3.2, and all my hosts are dual-homed, so maybe that makes a difference.
