### ISSUE TITLE
Incremental backup does not remove old files

### ISSUE THREAD

**Issue by mpedretti** [backuppc/backuppc#135]
I'm on backuppc 4.1.3 configured to backup a share on windows server 2012 r2.
The share contains database backups and this is what happens that I think should not.
On day 1 the share contains file1 and file2, a full backup occurs overnight and contains both files.
On day 2 file1 is deleted ad file3 added, an incremental backup occurs overnight and contains file2 and file3 as it should but also file1.
On day 3 file2 is deleted and file4 added and the overnight incremental backup still contains file3 and file4 but also file1 and file2.
A full backup resets the cicle to normal.

Isn't it wrong? Or am I missing something?

**Comment by craigbarratt** [comment]
What is your XferMethod?

**Comment by mpedretti** [comment]
Sorry I forgot to mention XferMethod.
I use smb, also there is no difference if the backup is filled or not.
BackupPC is on Ubuntu 16.04.2 LTS and smbclient is version 4.3.11.

**Comment by mpedretti** [comment]
Also please note that if you restore one of those incremental backups all the listed files are restored and this is the real problem.

**Comment by craigbarratt** [comment]
With smb and tar xfers incremental files won't detect deleted files or renamed files. This is described in the documentation. If you use rsync, it will detect all changes during incrementals.

**Comment by mpedretti** [comment]
I really missed that part, my bad.
I'll switch to rsync.
Thank you.
