### ISSUE TITLE
Different backup paths for different hosts

### ISSUE THREAD

**Issue by codesmaker** [backuppc/backuppc#136]
Hi,

I'm a new Backuppc user here. Sorry if I'm posting my question in the wrong place but I couldn't find a forum.

I would like to have different backup paths for different hosts. From what I can see now, I can set the "RsyncShareName" but it will apply for all hosts? I need, for example, to backup "/etc" for host1 and "/bin" for host2. How can I do that?

**Comment by hobbes1069** [comment]
Basically you have a global config which by default will apply to all hosts, then you have a per host config where you override the defaults as needed.

**Comment by SpareSimian** [comment]
The users mailing list can be found here:
https://sourceforge.net/projects/backuppc/lists/backuppc-users

**Comment by craigbarratt** [comment]
Thanks for pointing OP to the mail list.  Git issues should be for things that are possibly or likely to be bugs.

**Comment by codesmaker** [comment]
Found it. Thanks guys for the help and sorry for posting here.

**Comment by moisseev** [comment]
@craigbarratt How can new users know about these rules?
You can create an issue template containing this policy and link to the mailing list so they will know about it _before_ posing an issue.
[Creating an issue template for your repository](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)

**Comment by craigbarratt** [comment]
Thanks - good suggestion.  I've added .github/issue_template.md.
