### ISSUE TITLE
Restoring via smb is reported as failed even if it completed successfully

### ISSUE THREAD

**Issue by bdachev** [backuppc/backuppc#140]
Running BackupPC v4.1.3 in a docker container based on Apline distribution.
(see https://hub.docker.com/r/adferrand/backuppc/)
I see the same problem on BackupPC v3.3.1 running on a VM based on Ubuntu 16.04.3 LTS.

The restore operation transfers the files successfully but at the end it fails.
IMHO the problem is related to changes in what smbclient reports on successful operation.

Below is the log:

File /data/backuppc/pc/boris-pc/RestoreLOG.0.z

Contents of file /data/backuppc/pc/boris-pc/RestoreLOG.0.z, modified 2017-08-24 18:51:07

Running: /usr/bin/smbclient \\\\boris-w10\\upload -I 192.168.4.139 -U backup -E -d 1 -c tarmode\ full -Tx -
Running: /usr/local/BackupPC/bin/BackupPC_tarCreate -h boris-pc -n 13 -s SOURCE -t /VulkanSDK
Xfer PIDs are now 1162,1163
/usr/bin/smbclient: Can't load /etc/samba/smb.conf - run testparm to debug it
Domain=[BORIS-W10] OS=[Windows 10 Pro 15063] Server=[Windows 10 Pro 6.3]
tar:316  tarmode is now full, system, hidden, noreset, quiet
tarCreate: Done: 1666 files, 376189143 bytes, 137 dirs, 0 specials, 0 errors
restore failed: tar:316  tarmode is now full, system, hidden, noreset, quiet

**Comment by craigbarratt** [comment]
Yes, your theory is likely correct.  BackupPC expects to see certain matching text in the output of smbclient, and its output has changed from time to time.

What version of smbclient are you running?

**Comment by bdachev** [comment]
Hi Craig, in Alpine container installation where BackupPC is v4.1.3 the smbclient is v4.5.10. In Ubuntu install with BackupPC v3.3.1 the smbclient is v4.3.11-Ubuntu. Both installations experience the same issue so probably it is something new in samba 4.x. 
The solution that worked for me (at least on Ubuntu installation) was to increase the debug log level of smbclient to 6 so that it instructs the tar to dump to output what is detected by BackupPC script as success event. I am not sure that is the correct solution as bunch of unnecessary output is generated by smbclient in such case.
B.

**Comment by craigbarratt** [comment]
I pushed a commit 1c7cc88 that bases the outcome of an smb restore on the exit status of smbclient, rather than trying to detect some string in its output (since smbclient's output isn't very useful).
