### ISSUE TITLE
Add group of host constraints

### ISSUE THREAD

**Issue by guestisp** [backuppc/backuppc#146]
Mapping some hosts to a group of host could be usefull for making some constraints like how many simultaneous backups should be running for servers in the same group of hosts.

in example, in a virtual environment, server1,server2,server3 are placed on node1 (group1) and server4, server5 and server6 are on node2 (group2)

Currently, by setting 2 as MaxBackups will result in server1 and server2 backupped at the same time.
This means an high load on node1.

By setting something like MaxBackupsPerGroups to 1, will run backup for server1 and server4, still 2 concurrent backups but from 2 different nodes.

**Comment by craigbarratt** [comment]
This suggestion has come up before.  Unfortunately it would be a significant amount of work, so there are no plans to do this.
