### ISSUE TITLE
Delete BackupFilesOnly value on press enter

### ISSUE THREAD

**Issue by Philippe-M** [backuppc/backuppc#161]
Hello, in the 4.1.3. 

When I edit a machine, in the Xfer tab. I click in any field and press the enter key. The values of the BackupFilesOnly parameter are cleared. I did the test in xfer rsync.

Firefox 55.0.3

**Comment by craigbarratt** [comment]
Unfortunately the keyboard focus in the browser is on the Delete button, so when you hit enter it's the same as clicking on Delete, which deletes that entry.

I'm not sure what the best fix is.  We could disable Enter on all buttons...

**Comment by craigbarratt** [comment]
Replaced "submit" with "button" so Delete doesn't get clicked with Enter.  Commit e3b947e.
