### ISSUE TITLE
Website Error on New Install

### ISSUE THREAD

**Issue by gpearson** [backuppc/backuppc#162]
BackupPC-4.1.3 Version

Installed BackupPC on LinuxMint 18 PC, configured to make sure BackupPC Daemon was working correctly. In trying to view the website admin getting an error

Software error:

Can't locate BackupPC/Lib.pm in @INC (you may need to install the BackupPC::Lib module) (@INC contains: __INSTALLDIR__/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/local/BackupPC/cgi-bin/BackupPC_Admin line 53.
BEGIN failed--compilation aborted at /usr/local/BackupPC/cgi-bin/BackupPC_Admin line 53.

For help, please send mail to this site's webmaster, giving this error message and the time and date of the error.

The cgi-bin directory was not created during installation of the software. Created the directory and moved the BackupPC_Admin to this directory. Set permission to backups:www-data and suid

the file Lib.pm is located in /usr/local/BackupPC/lib/BackupPC along with other files and directories. 

If I run the BackupPC_Admin from command line in the installation directory /root/BackupPC-4.1.3/cgi-bin I get the same error message.

**Comment by moisseev** [comment]
> The cgi-bin directory was not created during installation of the software.

That's expected. `no CGI` is the default.

> `@inc contains: __INSTALLDIR__/lib `

You can't just copy files from _BackupPC distribution tarball_. There are variables in the distribution files that need to be substituted during `configure.pl` run. E.g. `__INSTALLDIR__` should be replaced with something like `/usr/local/BackupPC`.

So if you need to customize installation paths, you should specify them as `configure.pl` command line options or interactively.

For instance you can enter `/usr/local/www/cgi-bin` when `configure.pl` asks for CGI path:
`--> CGI bin directory (full path, or empty for no CGI) []?`
