### ISSUE TITLE
feature request: Encrypt backup

### ISSUE THREAD

**Issue by higuita** [backuppc/backuppc#163]
Right now we can create a encrypted pool by encryption the all disk, but that requires encrypting everything and the pools is fully decrypted when mounted.

Having a encrypted pool (epool), just like the cpool and pool would be useful, as many time we just need more protection on some files (ssh/gpg keys, password stores, certificates, some config files).

The idea is to protect data if someone have a "quick access" to the backuppc pool (as a long term hacked is usually a total lost) or if we replicate the pool to another storage as a off-site backup or if someone steals the HD. Its just another layer of protection

Using gpg is the best way to encrypt, using key pair one can encrypt without the secret key and only require it to recover , we can pipe it, use it manually,  enter the password only when recovering or use gpg-agent to manually enter the key decrypt password when starting the service or even use no password and place the keys in a usb stick that will only be plugged when restoring.

The checksum stored would be probably the original file, so we do not need to encrypt it again to find if it changed. Also probably the ideal situation would be enable the encryption per share, to help encrypt as less as possible

**Comment by craigbarratt** [comment]
Nice suggestion, but this would be a significant amount of work.  I'll keep this on my long term list of potential features.

**Comment by ftrojahn** [comment]
Wouldn't it be sufficient to try the use of e.g. ecryptfs, luks or 
similar existing solutions and document 'em in FAQ/Wiki?

**Comment by higuita** [comment]
no, this is different, as i said:
>  but that requires encrypting everything and the pools is fully decrypted when mounted.

please re-read my 3 first paragraph.

This is not a replacement to encrypted filesystems, but yet another layer, specially on the more sensitive files.

For now, as workaround, i use this:
in the machine.pl
```
$Conf{DumpPreShareCmd} = '$sshPath -6 -q -x -l root $host /home/backup/crypt.sh $share';
$Conf{RsyncShareName} = [
  '/home/backup/home/higuita/work',
];

```
Then the crypt.sh script i have:

```
#!/bin/bash -e
if [ -z $1 ]; then
        echo "no share"
fi
share=$1
origin=${share/home\/backup/}
find $origin \
        -xdev \
        -type f \
        -not -iname "*.tmp" \
        -not -iname "*.iso" \
        -not -iname "*.gz" \
        -not -iname "*.xz" \
        -not -name "*.~" \
        -not -name "*.back" \
        -not -name "*.old"  \
        \( \
        -ipath "*Downloads/*" -prune -o \
        -ipath "*Desktop/*" -prune -o \
        -ipath "*cache/*" -prune -o \
        -path "*/home/backup/*/*" -prune -o \
        -path  "*.old/*" -prune -o \
        -path  "*/temp*" -prune -o \
        -path  "*/tmp*" -prune -o \
        -path  "*/storage/default/*" -prune -o \
        -path  "*/Local Storage/*" -prune -o \
        -path  "*/Crash Reports/*" -prune -o \
        -print \
        \) \
  | /usr/bin/rsyncrypto -cv --delete --filelist -  $share  /home/backup/keys/  /home/backup/backup.pub
```

This used [https://rsyncrypto.lingnu.com](https://rsyncrypto.lingnu.com) to create a encrypted data structure in /home/backup/??? that backuppc will later backup in a rsync compatible way (only change the file if modified). This uses only the public key, so as long i have a (offline) backup of the private key, i can restore those encrypted files. Sadly this duplicates the files, one version unencrypted, another encrypted. As i only want some files, i do not waste many space.

backuppc could use rsyncrypto also to implement this, it already do the heavy work, the rsyncrypto "unencrypted state" files are small and is what is used to check if the file have changed since last backup... but instead of saving the encrypted file, it would be sent to backuppc directly ... thing in something like `rsyncrypto | rsync ` ( pseudocode, as rsyncrypto do not support pipe)

**Comment by GWHAYWOOD** [comment]
Some possible options:

https://www.kernel.org/doc/html/v4.16/filesystems/fscrypt.html
https://wiki.centos.org/PhilipJensen(2f)TransparentEncryptionForHomeFolder.html
https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/TransparentEncryption.html

**Comment by higuita** [comment]
Thanks @GWHAYWOOD , but that is still a encrypted filesystem, that is fully decrypted when mounted. So if i want to protect those files, at very least during backup, those files are totally decrypted to anyone with access to the backuppc machine. They only protect from stolen disk, as no one can mount them without the key, but after mounted, it is easy.

 My solution is encrypt the files in the origin and backup the encrypted files. It does require more disk space in my origin disk... but the files are never decrypted in any place.  That is why i would love that backuppc supported rsyncrypto directly  and avoid this intermediate encrypted copy

right now :
- all origin files ->rsyncrypto -> all encrypted files -> backuppc -> backup of all  encrypted files inside of backuppc 
ideal solution:
- origin files -> rssyncrypto -> possible a temp encrypted file or memory -> backuppc rsyncrypto client -> backup of the encrypted filed and rsyncrypto metadata so later runs can check changed files

**Comment by GWHAYWOOD** [comment]
My thinking was that the BackupPC instance would read the encrypted versions of the files, not the decrypted versions.
So the system using the decrypted data and the BackupPC system would e.g. be using different mount points.
Just an idea, and it assumes file-by-file encryption not encryption of e.g. entire directories so it might need work at both 'ends'.
I don't know how easy it would be but if it's feasible it would avoid your current duplication of data. :)

You're really looking for the implementation of something like

.../BackupPC/lib/BackupPC/Xfer/RsyncCrypto.pm

but unless someone (you?) steps up to do the work then with the very limited amount of effort currently available (i.e. just me) there's no prospect of it happening in the foreseeable future.  If you wanted to do the work but needed help to get started I should be very glad to provide that help.
