### ISSUE TITLE
Got fatal error during xfer (No files dumped for share CDrive)

### ISSUE THREAD

**Issue by snathan9** [backuppc/backuppc#169]
I get this error when backing up a large windows pc.  The full backup takes almost 2 days and always fails with "Got fatal error during xfer (No files dumped for share CDrive)".  I even tried the command line option: /usr/share/backuppc/bin/BackupPC_dump -v -f <host> and got the same error.  However incremental always works as I do have a full backup from about a year ago.  Below is the full message: (host name is my_pc)

.....
.....
  pool     644       0/0          96 du.txt
  pool     644       0/0      904704 msdia80.dll
  create   755       0/0           0 msdownld.tmp
tarExtract: Done: 0 errors, 118197 filesExist, 288834407061 sizeExist, 288834407061 sizeExistComp, 121120 filesTotal, 311834025000 sizeTotal
Got fatal error during xfer (No files dumped for share CDrive)
cmdSystemOrEval: about to system /bin/ping -c 1 my_pc
cmdSystemOrEval: finished: got output PING my_pc (192.168.1.88) 56(84) bytes of data.
64 bytes from my_pc (192.168.1.88): icmp_seq=1 ttl=64 time=0.897 ms

--- my_pc ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.897/0.897/0.897/0.000 ms

cmdSystemOrEval: about to system /bin/ping -c 1 my_pc
cmdSystemOrEval: finished: got output PING my_pc (192.168.1.88) 56(84) bytes of data.
64 bytes from my_pc (192.168.1.88): icmp_seq=1 ttl=64 time=0.789 ms

--- my_pc ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.789/0.789/0.789/0.000 ms

CheckHostAlive: returning 0.789
Backup aborted (No files dumped for share CDrive)
Saving this as a partial backup, replacing the prior one (got 519510 and 0 files versus 0)
dump failed: No files dumped for share CDrive
link my_pc

Backuppc version is 3.3.0
Samba Client version 4.3.11-Ubuntu

**Comment by moisseev** [comment]
Compatibility with Samba 4.3 was added in BackuPC 3.3.2 (#22).
