### ISSUE TITLE
Not compatible with apache event MPM & php_mod?

### ISSUE THREAD

**Issue by hobbes1069** [backuppc/backuppc#170]
I'm not sure where this needs to be fixed so I thought I would start here...

With Fedora 27 the default MPM mode for apache was changed from prefork MPM to event MPM and it looks like BackupPC couldn't handle this. 

https://lists.fedorahosted.org/archives/list/users@lists.fedoraproject.org/thread/4LPE6NHL3BO2AMYAMK4ZVMI6DSK4QD37/

**Comment by craigbarratt** [comment]
This sounds like an issue specific to Fedora and the Fedora BackupPC package, which this project isn't responsible for.

**Comment by hobbes1069** [comment]
I'm not going to pretend to understand what's going on under the hood with apache, but there is apparently a major performance hit using prefork MPM versus event MPM...

It's really Apache and not Fedora related (other than the decision to change the default) and it's difficult for me to justify forcing the end user to use a specific module.

https://httpd.apache.org/docs/2.4/mod/event.html
https://httpd.apache.org/docs/2.4/mod/prefork.html

**Comment by hobbes1069** [comment]
Ok, it took me a while to remember, but it looks like mod_php is no longer shipped with Fedora so it works as expected.
