### ISSUE TITLE
Realindex.cgi location

### ISSUE THREAD

**Issue by vanzhiganov** [backuppc/backuppc#172]
Where is located lib/realindex.cgi file in repository? How I can modify it?

**Comment by moisseev** [comment]
There is no `realindex.cgi` file in the backuppc repository. I think it is specific for distribution you are using. Probably this file was added (or renamed) by the package maintainer.  You'd better ask the maintainer of that backuppc package.

**Comment by vanzhiganov** [comment]
This file gist https://gist.github.com/vanzhiganov/eec1573eccacb1374171a3ace3548693
May be this file was renamed or deleted. I am using  backuppc 3.3.0-2+deb8u1 on Debian Linux

**Comment by moisseev** [comment]
It's `BackupPC_Admin`: https://github.com/backuppc/backuppc/blob/v3.x.x/cgi-bin/BackupPC_Admin

Regarding your second question, it depends on your goals.

**Comment by vanzhiganov** [comment]
Thanks you, I will try to upgrade installation on my backup server.
