### ISSUE TITLE
XferErr NT_STATUS_INVALID_PARAMETER listing

### ISSUE THREAD

**Issue by sedejg** [backuppc/backuppc#173]
Hello, 

I have updated BKCPPC to version 4.1.5 and now i have problem with XferErr NT_STATUS_INVALID_PARAMETER listing when backing up windows machines.

Smbclient is Version 4.3.11-Ubuntu and OS is Ubuntu 14.04.5 LTS.

Below is the part of error log:

tar:316  tarmode is now full, system, hidden, noreset, quiet
tarExtract: /usr/local/BackupPC/bin/BackupPC_tarExtract: got Full = 1
XferErr NT_STATUS_INVALID_PARAMETER listing \\Users\Sxyz STOZ\Documents
tar:782  do_list failed on Users\Sxyz STOZ\Documents (NT_STATUS_INVALID_PARAMETER)
tar:712  Total bytes received: 0
readOutput: sysread returns 0 and got EOF (exit ok = , )
XferErr Non-zero exit status from smbclient
tarExtract: /usr/local/BackupPC/bin/BackupPC_tarExtract starting... (XferLogLevel = 5)
tarExtract: Done: 0 errors, 0 filesExist, 0 sizeExist, 0 sizeExistComp, 0 filesTotal, 0 sizeTotal, 0 filesNew, 0 sizeNew, 0 sizeNewComp, 5753 inodeLast
Xfer PIDs are now 
Got fatal error during xfer (Non-zero exit status from smbclient)
Backup aborted (Non-zero exit status from smbclient)
BackupFailCleanup: nFilesTotal = 0, type = full, BackupCase = 4, inPlace = 0, lastBkupNum = 278
Removing empty backup #278

Any help would be appreciated.

**Comment by StefanPeter** [comment]
Dear sedjeg

On 15.12.2017 09:43, sedejg wrote:
> Hello,
> 
> I have updated BKCPPC to version 4.1.5 and now i have problem with
> XferErr NT_STATUS_INVALID_PARAMETER listing when backing up windows
> machines.

This probably has nothing to do directly with BackupPC. The smbclient
takes quite some parameters from the /etc/samba/smb.conf and if one of
these does not work with the windows version you want to connect to, the
NT_STATUS_INVALID_PARAMETER is thrown.

I'd first try to connect to the windows client in question from the
command line (under the backuppc user, of course). You may be able to
get additional information using the debug flag or even by peeking
inside the event log of the windows machine.

Other than that, a google search which includes the OS of your server
may help you further.

With kind regards

Stefan Peter

**Comment by sedejg** [comment]
Hello StefanPeter,

The problem is that Win10 client has disabled SMB1 by default. 
So I tried smbclient command with -m option from server as backuppc user

/usr/bin/smbclient -e \\\\user1\\C\$ -U AB/Administrator -E -d 1 -c tarmode\ full -Tc - /Users/Name\ SURNAME/Desktop -m SMB3_11

The result is:

tar:316  tarmode is now full, system, hidden, noreset, quiet
NT_STATUS_INVALID_PARAMETER listing \\Users\Name SURNAME\Desktop
tar:782  do_list failed on Users\Name SURNAME\Desktop (NT_STATUS_INVALID_PARAMETER)
tar:712  Total bytes received: 0
readOutput: sysread returns 0 and got EOF (exit ok = , )
XferErr Non-zero exit status from smbclient

I tried with different options  -m SMB2 and SMB3 (tried with options SMB2_02, SMB2_10, SMB2_22, SMB2_24, SMB3_00, SMB3_02, SMB3_10, SMB3_11) and result is always the same.

Regards,

Gregor

**Comment by craigbarratt** [comment]
Running smbclient manually is the right approach to figure out what is wrong.

Try removing the space between "-m" and "SMB3", eg: "-mSMB3".

**Comment by sedejg** [comment]
Tried removing space between "-m" and "SMB3" in smbclient command but no luck.

**Comment by drnest** [comment]
Hi, I have same problem. I discovered that problem is if remote path has more than one directory names. It is not BackupPC problem but smbclient. I have version 4.6.2. on Centos7. On Centos5.11 with smbclient 3.0.33-3.41.el5_11 it works. I tested it against Windows10 and Windows7.

This command works:
`smbclient \\\\192.168.1.2\\D\$ -A credentials -E -d 1 -c tarmode\ full -mSMB3 -Tc client.tar /dir`
This not:
`smbclient \\\\192.168.1.2\\D\$ -A credentials -E -d 1 -c tarmode\ full -mSMB3 -Tc client.tar /dir/dir`

But I do not know what to do with it :-(

**Comment by craigbarratt** [comment]
Can you try the newest version of smbclient, eg, 4.7.4?

**Comment by drnest** [comment]
I just test smbclient 4.7.0 on live Fedora 27 and it works.

**Comment by craigbarratt** [comment]
Thanks for confirming.  Closing the issue.
