### ISSUE TITLE
import url in BackupPC_stnd.css causes warnings

### ISSUE THREAD

**Issue by MartijnRas** [backuppc/backuppc#174]
After finally upgrading from version 3 to 4 I was surprised to receive warnings on HTTPS requests being made to outside domains.

The cause is the following import statement in https://github.com/backuppc/backuppc/blob/master/conf/BackupPC_stnd.css:

@import url('https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,600i,700,700i')

For now I've simply removed this line from the file on my system, as I don't like this type of cross site imports.

If this line can not be dropped from the source code, please add an option to (dis)allow these kind of cross site imports in the configuration.

**Comment by craigbarratt** [comment]
Good point.  Do the fonts render correctly without that import?  That URL delivers 36 lines of font-face definitions, which could be included manually in place of the import().

**Comment by MartijnRas** [comment]
Everything works fine without the import.

**Comment by MartijnRas** [comment]
I'd simply set the font-family to sans-serif by default, so the browsers will simply render the font chosen by the user.

**Comment by moisseev** [comment]
I agree with @MartijnRas , we shouldn't force users to use certain fonts.

I'd also remove every`font-family` properties as well from BackupPC_stnd.css to allow users configure fonts in browser settings. Probably `font-family` makes sense for non-default themes, but default css should fit into user environment as much as possible.

**Comment by craigbarratt** [comment]
Any comments from @EquisTango, who wrote the current BackupPC_stnd.css?

**Comment by craigbarratt** [comment]
I removed the font import in commit a8a051a.
