### ISSUE TITLE
Ping to local machines don't work

### ISSUE THREAD

**Issue by ediazrod** [backuppc/backuppc#177]
I am testing the last version of backuppc and I am making a ping to a local host.

2017-12-29 21:48:35 no ping response from servidorpifa
2017-12-29 21:48:35 can't ping servidorpifa (client = servidorpifa); exiting

change of ping to /bin/echo it is working ok, but why I am getting this message? there is a problem with the new code?.

**Comment by craigbarratt** [comment]
Most likely a configuration issue.  Could it be a ping vs ping6 issue?  Please post this question on the user list.  Github issues are for reporting bugs.

**Comment by SpareSimian** [comment]
Can you ping from the BackupPC server to the host you're trying to back up? Note that the default Windows firewall blocks ICMP.

**Comment by ediazrod** [comment]
I will close this, I don't know why but ping look ok.. ..

`/usr/local/BackupPC/bin/BackupPC_dump -v -f servidorpifa
Backup type: type = full, needs_full = , needs_incr = , lastFullTime = 1514580832, opts{f} = 1, opts{i} = , opts{F} =
cmdSystemOrEval: about to system /bin/ping -c 1 servidorpifa
CheckHostAlive: first ping (/bin/ping -c 1 servidorpifa) failed (512, )
no ping response from servidorpifa
can't ping servidorpifa (client = servidorpifa); exiting
`
`backuppc@servidorpifa:/$ /bin/ping -c 1 servidorpifa
ping: icmp open socket: Operation not permitted`

`ls -al /bin/ping
-rwxr-xr-x 1 root root 43056 Nov  8  2014 /bin/ping`

`servidorpifa:~# ls -al /bin/ping*
-rwxr-xr-x 1 root root 43056 Nov  8  2014 /bin/ping
-rwxr-xr-x 1 root root 43376 Nov  8  2014 /bin/ping6
servidorpifa:~# rm ^C
servidorpifa:~# mv /bin/ping /bin/ping.old
servidorpifa:~# apt-get install --reinstall iputils-ping
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 59 not upgraded.
Need to get 0 B/56.2 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 186375 files and directories currently installed.)
Preparing to unpack .../iputils-ping_3%3a20121221-5+b2_i386.deb ...
Unpacking iputils-ping (3:20121221-5+b2) over (3:20121221-5+b2) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up iputils-ping (3:20121221-5+b2) ...
Setcap worked! Ping(6) is not suid!
[ Rootkit Hunter version 1.4.2 ]
File updated: searched for 177 files, found 149
servidorpifa:~# ls -al /bin/ping
-rwxr-xr-x 1 root root 43056 Nov  8  2014 /bin/ping
`

And now works..

`backuppc@servidorpifa:/$ /bin/ping -c 1 servidorpifa
PING tallerespifa (192.168.0.2) 56(84) bytes of data.
64 bytes from tallerespifa (192.168.0.2): icmp_seq=1 ttl=64 time=0.053 ms
`
