### ISSUE TITLE
Full backups take almost twice as long after migrating to version 4

### ISSUE THREAD

**Issue by MartijnRas** [backuppc/backuppc#178]
Hello,

Previously, while running version 3 full backups had a duration of around 1000 minutes and incremental backups around 25 minutes.
Currently, after migrating to version 4, full backups have a duration of around 1900 minutes while incremental backups still have a duration of around 25 minutes.

I've BackupPC_migrateV3toV4 to migrate all hosts and all backups and set PoolV3Enabled to 0.
The total amount of data that is backed up has hardly increased over the past six months.

Does anyone else notice an increased duration of full backups in version 4?

Mazzel,

Martijn.

**Comment by craigbarratt** [comment]
What is your XferMethod?  What version of BackupPC, backuppc-xs and rsync-bpc are you running?

**Comment by craigbarratt** [comment]
Closing due to no response.
