### ISSUE TITLE
Make BackupPC_tarExtract extract tar.gz files when using pigz in client data compression

### ISSUE THREAD

**Issue by jzielke-nli** [backuppc/backuppc#179]
Compressing data on the client before dumping it to the backup server is using only one core at a time, which is inefficient on large amounts of data. Hence pigz could be used within the tar-backup command line. But BackupPC_tarExtract can't handle those files. Maybe BackupPC_tarExtract can do some pre-unzip before reading the tar archive.

**Comment by craigbarratt** [comment]
The various xfer methods don't compress data on the client (unless you use ssh -C or rsync -z, which aren't the defaults).
