### ISSUE TITLE
[Feature] Description Field on Web Interface

### ISSUE THREAD

**Issue by andrewmaksymowsky** [backuppc/backuppc#180]
Would it be possible to add a description field for a backup host ?
We need a way to quickly identify which hosts belong to various groups we administer and having a description field would make this easier. On the backend it would just be a meaningless extra label.

Thank you !

**Comment by craigbarratt** [comment]
Would making it a config parameter (changed via the config editor) be ok?  Or should it be more like a status variable, maintained separately from the config?

Where would you want it displayed?  Can it be edited by the user?

**Comment by andrewmaksymowsky** [comment]
A config parameter would be great so long as we can specify the description per host. 
Would it be possible to display it on the "host Summary" page as an extra column ?
That way at a quick glance we could sort our hosts by the description and see which belong to the various groups we support. Thanks !

**Comment by craigbarratt** [comment]
Added new config parameter ClientComment in commit 3dfc35e that is displayed in the host summary and per-host status pages.

**Comment by andrewmaksymowsky** [comment]
Thank you !
