### ISSUE TITLE
Feature Request: continuous data protection (CDP) support

### ISSUE THREAD

**Issue by samuelxhu** [backuppc/backuppc#181]
Besides the currently supported full backup and incremental backup, many users would be interested to have a new backup scheduler, continuous data protection (CDP), i.e. the clients continuously monitor any changes of files or directories, and once such changes happened, they are pushed or pulled incrementally to the backup server.

Could this feature be done to bakcuppc?

Samuel

**Comment by thunfischbrot** [comment]
It would require a client to be installed on all machines, which is currently not part of backuppc.

**Comment by craigbarratt** [comment]
Yes, unfortunately this is outside the scope of the project.

**Comment by GWHAYWOOD** [comment]
This could be implemented by the Perl Script BackupPC_serverMesg in the .../BackupPC/bin/ directory of any recent installation.

Basically something on the client decides when a backup is needed.  That part is up to you.  When it decides to start a backup it runs a command on the client which (for example over SSH) connects to the BackupPC server as the backuppc user and simply runs a one-liner on the BackupPC server such as

/usr/local/BackupPC/bin/BackupPC_serverMesg backup clientname clientname backuppc 0
