### ISSUE TITLE
Export all content RsyncShare_name with BackupPC_tarCreate

### ISSUE THREAD

**Issue by alex8276** [backuppc/backuppc#182]
Hi everyone,
I use backuppc 3.3.
Is it possible to restore all content of RsyncShare_name with the scripts BackupPC_zipCreate or BackupPC_tarCreate ?
/usr/share/backuppc/bin/BackupPC_tarCreate -h xxx -n 631 -s /xxx/x/xxx "folder_to_restore" > /home/backuppc/xx.tar

If I have lot of folders/files it's a long time to do one by one.

Thanks,

**Comment by craigbarratt** [comment]
Yes, that should work.

You can test it to make sure you are getting what you expect by piping it into tar -tvf -, eg:
```
BackupPC_tarCreate -h xxx -n 631 -s /xxx/x/xxx "folder_to_restore" | tar -tvf - | less
```

**Comment by alex8276** [comment]
Hi Craigbarratt,
thanks to your answer !
My problem is that my rsyncShare_name (ie: /home/user) contain 500 folders. I have to make 500 times the command.
I its possible, I would like restore at once my 500 folders  in an archive

**Comment by craigbarratt** [comment]
Use "*" for the share name to create an archive with all the shares:
```
BackupPC_tarCreate -h xxx -n 631 -s "*" / | tar -tvf - | less
```

**Comment by alex8276** [comment]
Ok, I going to try it tomorrow !
Thanks

**Comment by alex8276** [comment]
Hello;
it work, thanks
