### ISSUE TITLE
Status showing "Pool hashing gives 0 repeated files with longest chain 0"

### ISSUE THREAD

**Issue by ki1022** [backuppc/backuppc#183]
My status page is showing "Pool hashing gives 0 repeated files with longest chain 0".  The shares being backed up definitely have many duplicate files throughout so I am trying to figure out what this means.  Is there a problem with my pooling/hashing or am I misunderstanding what this statistic is referring to?

**Comment by craigbarratt** [comment]
No, everything is fine.

It is not reporting the number of times each pool file is used (which could be many, as you note).  Rather, it's reporting whether there are hash collisions in the pool itself (ie, files that are different that have the same md5 digest).  While such files can be constructed, they very very rarely happen in the wild.  So most BackupPC4 installations will report the status exactly that way.
