### ISSUE TITLE
connection between 2 backuppc servers

### ISSUE THREAD

**Issue by IamHamada** [backuppc/backuppc#187]
Hello, 
i want to install backuppc  on a container and from this container i want to control and manage a backuppc server running in other big host . 
could you tell me please if this possible ? 
i tried to  configer the config.pl file and put the ip address for the out server as a backuppc server and also put the port and the  "ServerMesgSecret"  as well  but the backuppc running in the vm wasn't able to connect to the backuppc on the other big server . 
could you help please ?
thanks and best regards

**Comment by hobbes1069** [comment]
I don't quite understand what you're trying to do but it should be pretty easy to setup, but this seems to be more of a question of how to setup the container and not BackupPC. BackupPC being a web based service using Apache there should be generic instructions about how to set up the mapping into and out of the container.

As far as performing the actual backups, assuming you're going to use rsync over ssh, as long as rsync_bpc can get to the clients you should be good to go.

**Comment by IamHamada** [comment]
look at these variables in config.pl file 
$Conf{ServerHost} = 
$Conf{ServerPort} = 
and
$Conf{ServerMesgSecret}

i think these variables used if you want to connect to a far away BackupPC server in addition to the local host  .. is it right ?

**Comment by craigbarratt** [comment]
As @hobbes1069 mentioned, you should only have a single instance of BackupPC; two instances of BackupPC won't communicate with each other.  The config settings you mention are used when apache is running on a different host from BackupPC, but in almost all cases apache runs on the same server as BackupPC.
