### ISSUE TITLE
Can not edit config.pl and open log file in web Interface

### ISSUE THREAD

**Issue by nanomashinX** [backuppc/backuppc#188]
I'm trying to install BackupPC-4.1.5 on my Virtual machine(Centos 7). I have installed httpd,BackupPC and run them successfully.  I use mod_perl for CGI interface, and I can visit the page. But I can't open log file and edit config file in the page.  The user of BackupPC is backuppc. 

![image](https://user-images.githubusercontent.com/27765621/37813613-d0cc10da-2ea0-11e8-8a91-913d6df0233a.png)

**TextFileWrite: Failed to write /etc/BackupPC/config.pl.new**
**Can't open log file /var/log/BackupPC/LOG.**

 Is it that the user backuppc has no right permissions?

**Comment by craigbarratt** [comment]
First, check the ownership and permissions of /etcBackupPC and /var/log/BackupPC.

One possible cause is that mod_perl isn't running the CGI script as the BackupPC user.

**Comment by nanomashinX** [comment]
/var/log/BackupPC
**drwxr-x---. 2 backuppc backuppc     63 Mar 23 14:00 BackupPC**
/etc/BackupPC
**drwxr-x---.  2 backuppc backuppc   4096 Mar 23 13:16 BackupPC**
The user and group in "httpd.conf" is backuppc.
Is that right?
 I tried to start backuppc and httpd service by user  backuppc and has the same error.
su -s /bin/bash backuppc

**Comment by hobbes1069** [comment]
You didn't mention how you installed it. Did you do a manual install or a package?

**Comment by nanomashinX** [comment]
I installed it manually. And when the system reboot, I need to create a directory(/var/run/BackupPC) every time.

Here is some information:

/etc/BackupPC
**drwxr-x---.  2 backuppc backuppc   4096 Mar 23 13:16 BackupPC**
/var/log/BackupPC
**drwxr-x---. 2 backuppc backuppc     63 Mar 23 16:52 BackupPC**

Apache:
**root       1764  0.0  0.3 231292  7416 ?        Ss   09:58   0:00 /usr/sbin/httpd -DFOREGROUND
backuppc   1766  0.0  0.2 231292  3976 ?        S    09:58   0:00 /usr/sbin/httpd -DFOREGROUND
backuppc   1767  0.0  0.2 231292  3976 ?        S    09:58   0:00 /usr/sbin/httpd -DFOREGROUND
backuppc   1768  0.0  0.2 231292  3976 ?        S    09:58   0:00 /usr/sbin/httpd -DFOREGROUND
backuppc   1769  0.0  0.2 231292  3976 ?        S    09:58   0:00 /usr/sbin/httpd -DFOREGROUND
backuppc   1770  0.0  0.2 231292  3976 ?        S    09:58   0:00 /usr/sbin/httpd -DFOREGROUND**

BackupPC:
**backuppc   1969  0.0  0.5 157420  9436 ?        S    10:01   0:00 /usr/bin/perl /usr/local/BackupPC/bin/BackupPC -d**

Is that right? 

Thanks!

**Comment by moisseev** [comment]
> I need to create a directory(/var/run/BackupPC) every time.

It seems `/var/run` is not persistent (e.g. in-memory file system) in your setup. In this case you need to create it in the service's init script.

**Comment by nanomashinX** [comment]
My main proplem is that I can't save any thing modified and view the log file in the web page. I have checked the log of BackupPC, no errors.

**Comment by craigbarratt** [comment]
Probably the best way to debug this is to add some code that gives more diagnostic information.  Are you comfortable editing perl code using an editor like vim?

**Comment by nanomashinX** [comment]
I‘m not sure if I can. I‘m unfamiliar with perl.

**Comment by craigbarratt** [comment]
I'm happy to email snippets of perl code to you, and instructions about where to put it.  I could use diff format if you want.  So that could be a way to debug if you are ok editing the files, re-running and getting the debug output.

**Comment by nanomashinX** [comment]
Thanks! Let me try.

**Comment by craigbarratt** [comment]
Ok, I'll plan to send you something on the weekend.

**Comment by craigbarratt** [comment]
Here is a change to try.  This is in the form of a diff:
```--- lib/BackupPC/Storage/Text.pm	2018-04-08 16:57:41.785497457 -0700
+++ lib/BackupPC/Storage/Text.pm.orig	2018-04-08 16:49:11.076952954 -0700
@@ -266,8 +266,7 @@
             close($lockFd);
         }
     } else {
-        my $umask = sprintf("0%o", umask());
-        return "TextFileWrite: Failed to write $file.new (errno = $!, uids = $<,$>, gids = $(,$), umask = $umask, ver = $^V, prog = $^X)";
+        return "TextFileWrite: Failed to write $file.new";
     }
     return;
 }
```
If you want to edit it manually, just replace this line:
```
return "TextFileWrite: Failed to write $file.new";
```
with these two lines:
```
my $umask = sprintf("0%o", umask());
return "TextFileWrite: Failed to write $file.new (errno = $!, uids = $<,$>, gids = $(,$), umask = $umask, ver = $^V, prog = $^X)";
```
After making the change, try to save a configuration change, and see what the error message is.

**Comment by nanomashinX** [comment]
This is the error message.
**TextFileWrite: Failed to write /etc/BackupPC/config.pl.new (errno = Permission denied, uids = 1000,1000, gids = 1000 0 1000,1000 0 1000, umask = 027, ver = v5.26.1, prog = /usr/sbin/httpd)**

**Comment by craigbarratt** [comment]
Ok, what's the uid and gid of the BackupPC user?

Can you successfully create a file there as the backuppc user?  eg:
```
su - backuppc
touch /etc/BackupPC/testFile
ls -l  /etc/BackupPC/testFile
rm /etc/BackupPC/testFile
```

Can BackupPC successfully write to /var/log/BackupPC?  If so, that confirms it's specific to apache.  It must be something related to apache's config, or maybe selinux?

**Comment by nanomashinX** [comment]
oh，it is actually caused by selinux.  I forget it. Thank you!
