### ISSUE TITLE
Is this the new repo for BackupPC?

### ISSUE THREAD

**Issue by BenjaminLefoul** [backuppc/backuppc#19]
Is this the official migrated repo from https://sourceforge.net/projects/backuppc/files/backuppc/3.3.1/ ?

If so, can you prove it?

This software looks abandoned on sourceforge as well as by the packaging person "Bernard Johnson" from the fedoraproject. His email bjohnson@symetrix.com is fake and unresponsive. The company at symetrix.co (not com) don't know him. He has completely disappeared.

**Comment by xtaran** [comment]
Please have a look at the backuppc-devel mailing list archive at sourceforge first. Your (upstream) questions are already answered there: https://sourceforge.net/p/backuppc/mailman/backuppc-devel/

**Comment by ehannes** [comment]
As the backuppc creator himself agrees to move the repo to here in above mentionen thread, the answer to your question should be: yes.

Why not anounce this on the old official site (the sourceforge site)?

**Comment by craigbarratt** [comment]
Yes, this is the new repo.  I've updated the various release files and backuppc.sf.net to include pointers to Github.
