### ISSUE TITLE
Delete backup button causes internal server error on apache

### ISSUE THREAD

**Issue by jzielke-nli** [backuppc/backuppc#193]
**BackupPC version:** 4.2.0
**Apache2 version:** 2.4.18
**OS:** Ubuntu 16.04  4.4.0-116-generic

**Bug:**
Internal server error by apache when clicking "delete backup" button in BackupPC SCGI GUI.

**Additional informtion:**
Debug of apache2 gives no hint on any permission issues.

**Comment by craigbarratt** [comment]
Can you try restarting apache?

**Comment by craigbarratt** [comment]
I pushed a fix b427f19 for this.

**Comment by jzielke-nli** [comment]
@craigbarratt-travisci 

Thanks, the fix is working. :-)
