### ISSUE TITLE
Make 'delete' functionality optional for certain users

### ISSUE THREAD

**Issue by basg** [backuppc/backuppc#194]
Thanks for implementing the new "delete" functionality in BackupPC 4.2.0. It looks like a useful feature. However, in certain use-cases (such as ours) it would be nice if there was a way to prevent non-admin users from deleting backups. 

Is such a configuration option already present and are we overlooking something? If not, could this option be added?

**Comment by robbsie** [comment]
Good point, would be fine to disable this globally (in config) as we do not need this feauture.

**Comment by craigbarratt** [comment]
I pushed a set of changes 5ed68f3 that adds a new config variable to enable or disable the backup delete feature for users.  Admins always have the delete feature.
