### ISSUE TITLE
[Feature] Prometheus Integration

### ISSUE THREAD

**Issue by jkroepke** [backuppc/backuppc#197]
Hi,

https://prometheus.io/ - Prometheus is a powerful metric collector with has some awesome integration into different products. Since prometheus has a alerting API, its a nice monitoring tool in some small to medium sized environment.

Here is a incomplete list of all known exporters: https://github.com/prometheus/prometheus/wiki/Default-port-allocations

It would be awesome, if BackupPC provides such an API (https://prometheus.io/docs/instrumenting/writing_clientlibs/; http://search.cpan.org/~pevans/Net-Prometheus-0.03/lib/Net/Prometheus.pm). Such an API could be provides the same statical informations about every backup like a host detail status pages. It could be also contains an status about every backup, if the backup was success full or not.

Finally, you could use Grafana as a graphical backend to visualize different metrics.

If you habe more questions about this tool, just ask.

**Comment by raoulbhatia** [comment]
I think this would be a nice idea.  @jkroepke how about providing a pull request?

**Comment by jkroepke** [comment]
Hum. 

I have no knewledge about PERL and parsing the status file doesn't give me enough information about the hosts.

An generic status REST API would be helpful, but no Idea if that exists in backuppc.

I can try somethink but I guarantee no success.

**Comment by jkroepke** [comment]
Looks like backuppc is written in a very simple way. I can use the status page as good basic example. I'm thinking about how I design the metric names and labels.

@craigbarratt Do you interest in a PR about this feature?

**Comment by jkroepke** [comment]
I'll look into it.

**Comment by christianuhlmann** [comment]
Hi,
I am also very interested in an API.
@craigbarratt which API is there already, in the document https://backuppc.github.io/backuppc/BackupPC.html I found nothing

**Comment by Grokon** [comment]
any info?

**Comment by otwieracz** [comment]
You can have a look at: https://github.com/otwieracz/backuppc_exporter (NOTE: No warranty!)

**Comment by danielmotaleite** [comment]
I also workaround  this by using the RSS feed. In telegraf i imported this config:

```
[[inputs.exec]]
  ## get backuppc backup ages
  commands = [ "/usr/local/sbin/check-backups.sh" ]
  data_format = "influx"
  timeout = "15s"
```


Then the `check-backups.sh` have this :

```
#!/bin/bash
curl -s https://backuppc:PASSWORD@backuppc.example.net:8080/BackupPC_Admin?action=rss -k | \
  awk '
	BEGIN			{ FS="[<>, :;]" ; metric="backuppc,job="}
	/RSS feed/		{ next }
	/title/	&& NR>10	{ name=$3 }
	/Incr Age/		{ if($4>=0){ iage=$4 } else { iage=-1 } }
	/Full Age/	        	{ if($4>=0){ fage=$4 } else { fage=-1 } }
	/Disabled/		{ if ($3 == 0) { disabled="false" } else { disabled="true"} }
        # as we use non-standard FS, $2 and $NF are empty spaces
        /State/ && $3 !~ /idle/ {
                                  state=$3
                                  for (i=4; i<NF; i++) { state=state"_"$i }
                                  print "backuppc,job="name",state="state, "running=1"
                                }
	/\/description/		{ lage=fage
                                  if ( iage >=0 ) {
					if (iage < fage) {
						lage=iage
					}
                                  }
                                  print metric name ",disabled=" disabled , "incr="iage
                                  print metric name ",disabled=" disabled , "full="fage
                                  print metric name ",disabled=" disabled , "last="lage
```

This have been working fine for me

**Comment by jooola** [comment]
I just opened a PR  #344 for a basic stats/metrics endpoint including Prometheus exports.

Any input is very welcomed.
