### ISSUE TITLE
Inconsistent "prior to pooling and compression" and "full size" sums

### ISSUE THREAD

**Issue by bmalynovytch** [backuppc/backuppc#207]
Since migrating (new setup) to **BackupPC v4**, we're getting **inconsistent values** for "prior to pooling and compression" (global) as well as "full size" (per host).

Lets give some real world values, pulled from the "Host summary" page (I added 2 columns at the right, with size on host and # of inodes):

Host | User | Comment | #Full | Full Age (days) | Full Size (GiB) | Speed (MiB/s) | #Incr | Incr Age (days) | Last Backup (days) | State | #Xfer errs | Last attempt | Real usage on host | # inodes on host
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
x | x |   | 1 | 7.2 | **13.66 GiB** | 13.74 | 6 | 0.2 | 0.2 | idle | 0 | done | **19 GiB** | 243k
x | x |   | 1 | 7.1 | **13.27 GiB** | 18.62 | 5 | 0.2 | 0.2 | idle | 0 | done | **18 GiB** | 243k
x | x |   | 1 | 6.9 | **13.23 GiB** | 17.72 | 7 | 0.2 | 0.2 | idle | 0 | done | **18 GiB** | 243k
x | x |   | 1 | 7.2 | **96.08 GiB** | 31.07 | 8 | 0.2 | 0.2 | idle | 0 | done | **53 GiB** | 439k
x | x |   | 1 | 6.4 | **56.95 GiB** | 55.70 | 8 | 0.2 | 0.2 | idle | 0 | done | **38 GiB** | 439k
x | x |   | 1 | 6.4 | **57.32 GiB** | 54.75 | 8 | 0.2 | 0.2 | idle | 0 | done | **38 GiB** | 439k
x | x |   | 1 | 7.2 | **686.04 GiB** | 36.84 | 7 | 0.2 | 0.2 | idle | 1 | done | **181 GiB** | 800k
x | x |   | 1 | 6.7 | **758.90 GiB** | 41.55 | 6 | 0.2 | 0.2 | idle | 1 | done | **181 GiB** | 800k
x | x |   | 1 | 6.5 | **782.17 GiB** | 35.02 | 7 | 0.2 | 0.2 | idle | 1 | done | **181 GiB** | 800k

Summary shows:
```
There are 9 hosts that have been backed up, for a total of:

9 full backups of total size 2'477.63 GiB (prior to pooling and compression),
62 incr backups of total size 11'273.75 GiB (prior to pooling and compression).
```
while, on disk, the pool is:
```
# df -i .
Filesystem       Inodes    IUsed    IFree IUse% Mounted on
                67108864 11926731 55182133   18%
# df -h .
Filesystem       Size  Used Avail Use% Mounted on
                1008G  390G  568G  41%
```

As we can see, there are huge differences between real values observed:
- on the backup host: pool is around **400 GiB** while BackupPC thinks it is around **14 TB**
- on client hosts:
  - first three hosts are supposed to have **13 GiB** of data (BackupPC count) while real data usage is **19 GiB** (Linux hosts, nothing particular)
  - last three hosts are supposed to have around **750 GiB** (BackupPC count) while real data usage is **less than 200 GiB** (Linux hosts, with GlusterFS bricks included in backup, GlusterFS mountpoint excluded from backup)

The question is: how are the BackupPC counts made, particularly the "prior to pooling and compression" ?

## Versions
BackupPC version: 4.2.1
BackupPC-XS version: 0.57
rsync-bpc version: 3.0.9

**Comment by craigbarratt** [comment]
For you first question - this is expected.  BackupPC is reporting the sum of the raw size of the backups (prior to any pooling or compression) is 14TB.  It's reasonable that corresponds to 400GB of pool storage.

For your second question, could you be backing up sparse files (eg: /var/log/wtmp or /var/log/lastlog) or special files (eg, below /proc)?  df on the client will show the correct usage, but BackupPC doesn't know about sparse files and will count the full size.

**Comment by bmalynovytch** [comment]
Hi @craigbarratt !

I clearly understand what "prior to pooling and compression" means.
How can you explain that the sum of the real size used on the servers doesn't exceed 800GB while BackupPC reports a total of 14TB ?

There are no sparse files, special directories such as `/dev` and `/proc` are excluded from backups.
Incremental backups have nearly no changes from day to another.

**Comment by bmalynovytch** [comment]
I added a new host today, a Gitlab server.

Here are the real metrics:
```
$ df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/rootfs               18G   10G  7.6G  57% /
devtmpfs                 1.9G     0  1.9G   0% /dev
tmpfs                    1.9G  4.0K  1.9G   1% /dev/shm
tmpfs                    1.9G  193M  1.7G  11% /run
tmpfs                    1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/vda1                497M  254M  243M  52% /boot
tmpfs                    380M     0  380M   0% /run/user/0

$ df -i
Filesystem                Inodes  IUsed    IFree IUse% Mounted on
/dev/rootfs             18317312 160391 18156921    1% /
devtmpfs                  482698    408   482290    1% /dev
tmpfs                     485251      2   485249    1% /dev/shm
tmpfs                     485251    514   484737    1% /run
tmpfs                     485251     13   485238    1% /sys/fs/cgroup
/dev/vda1                 512000    351   511649    1% /boot
tmpfs                     485251      1   485250    1% /run/user/0
```
As we can see, real usage is around 12GB ...
while BackupPC reports a "Full Size" of 107.61GB

I also noticed that the backup took long (around 1.5 hour) when other new servers took less than 10 minutes.

I think there may bee an issue with large amounts of small (or empty ) files, hard links, symlinks, attributes, ...

**Comment by bmalynovytch** [comment]
I opened an issue on backuppc/rsync-bpc as I think the wrong stats come from there: https://github.com/backuppc/rsync-bpc/issues/6

**Comment by bmalynovytch** [comment]
Sorry, no, they contain sensible datas.
Though, scrolling through one of them, I can confirm that the sum of the size columns give the same wrong result (107GB).

I'm digging in the log to understand where these "extra datas" come from.

**Comment by bmalynovytch** [comment]
@craigbarratt Grumbl ... I finally found the guilty:
`var/lib/docker/devicemapper/devicemapper/data`
... which, as you suggested, IS a sparse file of 100GB, containing only 5GB.

For the other hosts I reported (https://github.com/backuppc/backuppc/issues/207#issue-342754934) I wasn't able to find sparse files.
Still trying to find where the extra datas come from (there seem to be duplication in hard links counts).

**Comment by bmalynovytch** [comment]
So ... I managed to find out what's happening.
As one would say, it isn't a bug, it's a feature.

To ensure security, on some hosts, we have bound mount points (parts of the filesystem tree remounted on top of some sub-directories). The main usage is chrooted envs for FTPS accesses.
The thing is that on some hosts, those trees hold most of the data and are remounted multiple times.
Thus, `rsync_bpc` duplicates all that.

**Comment by bmalynovytch** [comment]
@craigbarratt Although I understand you don't want to bother too much about this issue, I still believe we can think about a solution to identify sparse files and duplicated inodes / hard links, at least in the sum.

The main issue for us is that we use the totals to apply (real) usage quotas to customers, which are completely wrong for some of them, due to the sparse files and duplicated files.
