### ISSUE TITLE
Feature request: ionice 

### ISSUE THREAD

**Issue by SpareSimian** [backuppc/backuppc#211]
Add an option to ionice the process tree so that it runs at lower disk priority than other processes on the host. 

This adds ionice unconditionally using backuppc's systemd unit file:

https://ask.fedoraproject.org/en/question/63954/how-to-init-backuppc-with-ionice/

Some background on ionice and how to tell if your kernel has it:

https://friedcpu.wordpress.com/2007/07/17/why-arent-you-using-ionice-yet/

**Comment by hobbes1069** [comment]
I like the SystemD method if it works (I'm the Fedora maintainer BTW) but I'll have to see if there's a way to make it configurable without the end user having to copy from /lib/systemd/system to /etc/systemd/system.

**Comment by SpareSimian** [comment]
I asked on the systemd mailing list and was directed to this section on override files that are applied after a unit file.

https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Description

So one could create /etc/systemd/system/backuppc.service.d/10-ionice.conf containing:

[Service]
IOSchedulingClass=idle

**Comment by hobbes1069** [comment]
Interesting. Haven't seen that before. Thanks!
