### ISSUE TITLE
Problem after upgrade Ubuntu 16.04 -> 18.04

### ISSUE THREAD

**Issue by ktenney** [backuppc/backuppc#214]
Howdy,

I recently updated a BackupPC server VM to 18.04.

I have Salt states to fetch, build and install github master of
backuppc, backuppc-xs, rsync-bpc.

They have been working great on 16.04, but on 18.04 BackupPC
won't start, it fails with the message:

*Invalid version format (trailing decimal) at ./BackupPC line 125*

line 125 is:

*if ( $version eq "unknown" || version->parse($1) < version->parse($PackageVersion->{rsync_bpc})

At that point I'm lost. Suggestions?

Thanks,
Kent

**Comment by craigbarratt** [comment]
What is the output from
```
rsync_bpc --version
```

**Comment by ktenney** [comment]
rsync_bpc  version  3.1.2.beta0 protocol version 31

**Comment by raoulbhatia** [comment]
@Chris, thanks for finding a workaround.  How about submitting a PR?

However, I am curious to understand why you get the beta0 string attached in the first place.  Would it help to use proper Debian/Ubuntu packages, see https://github.com/backuppc/backuppc/wiki/Build-Your-Own-Packages?

**Comment by craigbarratt** [comment]
I pushed a fix 11e025b for this.
