### ISSUE TITLE
Duplicates not counted properly

### ISSUE THREAD

**Issue by 8666** [backuppc/backuppc#219]
This is the listing for one of the backups:

`
 su backuppc -s /bin/bash -c '/usr/local/backuppc/bin/BackupPC_ls -h "kodi" -n 14 -s "Backup" "/"'                                          
/:
-rw-r--r--       0/0 2534778880 2018-06-30 09:05:25  /20180630085210.tar (ff0b45c2c3f137ede6b205f442c308cf)
-rw-r--r--       0/0 2535178240 2018-06-30 17:35:07  /20180630172213.tar (4fc7c8c16c378240b994499b039526c3)
-rw-r--r--       0/0 2656522240 2018-08-28 23:18:57  /20180828230447.tar (a663c3a19c10537cab416d8e2f3208e4)
-rw-r--r--       0/0    3283190 2018-06-21 01:49:18  /New Bitmap Image.bmp (302c91b984ad2f2509e7ffe7bb428a1b)
-rw-r--r--       0/0   21828696 2014-05-18 16:35:57  /math_2.zip (c14f8bb8f36466522ff2a159d926766a)
-rw-r--r--       0/0   21828696 2014-05-18 16:35:57  /math_2_2.zip (c14f8bb8f36466522ff2a159d926766a)
-rw-r--r--       0/0   21828696 2014-05-18 16:35:57  /math_3.zip (c14f8bb8f36466522ff2a159d926766a)
-rw-r--r--       0/0   21828696 2014-05-18 16:35:57  /math_3_2.zip (c14f8bb8f36466522ff2a159d926766a)
`
math files have the same checksum but on the Status web page duplicates are counted as 0

also I do not see the right number here:

/bin/su -s /bin/sh backuppc -c "/usr/local/backuppc/bin/BackupPC_serverMesg status info"

Got reply: %Info = ("cpool4FileCntRep" => 0,"cpoolFileCntRep" => 0,"cpoolKbRm" => 0,"DUDailyMaxPrev" => 65,"poolKb" => 0,"PoolSizeNightlyPhase" => 0,"poolFileRepMax" => 0,"poolTime" => 0,"Version" => "4.1.5","cpoolFileLinkMax" => 0,"poolFileCntRep" => 0,"cpoolTime" => 0,"DUDailySkipHostCntPrev" => 0,"cpoolFileCntRm" => 0,"cpool4FileRepMax" => 0,"pool4FileLinkMax" => 0,"cpool4FileCntRm" => 251,"startTime" => 1535491131,"ConfigModTime" => 1530227043,"ConfigLTime" => 1535491131,"DUlastValueTime" => 1535887329,"cpoolKb" => 0,"poolFileCntRename" => 0,"NightlyPhase" => 0,"RunningPIDs" => {"2661" => 1,"2658" => 1,"2696" => 1},"HostsModTime" => 1530047363,"pool4Time" => 1535839662,"DUDailySkipHostCnt" => 0,"nextWakeup" => 1535889600,"poolDirCnt" => 0,"cpool4FileCntRename" => 0,"pool4FileCntRm" => 0,"cpool4Time" => 1535839665,"cpool4DirCnt" => 16512,"cpoolFileCntRename" => 0,"pool4Kb" => 0,"pool4FileCntRep" => 0,"poolFileLinkMax" => 0,"cpool4FileCnt" => 424084,"pool4DirCnt" => 0,"poolKbRm" => 0,"cpoolFileCnt" => 0,"pool" => {"pool4" => [{"FileLinkMax" => 0,"FileCntRep" => 0,"DirCnt" => 0,"Kb" => 0,"FileRepMax" => 0,"FileLinkTotal" => 0,"FileCntRm" => 0,"Time" => 1535839565,"KbRm" => 0,"FileCnt" => 0},{"DirCnt" => 0,"FileCntRep" => 0,"FileLinkTotal" => 0,"Kb" => 0,"FileRepMax" => 0,"FileLinkMax" => 0,"FileCnt" => 0,"KbRm" => 0,"Time" => 1535839565,"FileCntRm" => 0},{"KbRm" => 0,"FileCnt" => 0,"FileCntRm" => 0,"Time" => 1535839565,"FileRepMax" => 0,"Kb" => 0,"FileLinkTotal" => 0,"FileCntRep" => 0,"DirCnt" => 0,"FileLinkMax" => 0},{"FileLinkTotal" => 0,"Kb" => 0,"FileRepMax" => 0,"DirCnt" => 0,"FileCntRep" => 0,"FileLinkMax" => 0,"FileCnt" => 0,"KbRm" => 0,"Time" => 1535839565,"FileCntRm" => 0},{"Time" => 1535839565,"FileCntRm" => 0,"FileCnt" => 0,"KbRm" => 0,"FileLinkMax" => 0,"FileLinkTotal" => 0,"FileRepMax" => 0,"Kb" => 0,"DirCnt" => 0,"FileCntRep" => 0},{"KbRm" => 0,"FileCnt" => 0,"FileCntRm" => 0,"Time" => 1535839565,"FileRepMax" => 0,"Kb" => 0,"FileLinkTotal" => 0,"FileCntRep" => 0,"DirCnt" => 0,"FileLinkMax" => 0},{"FileLinkMax" => 0,"FileCntRep" => 0,"DirCnt" => 0,"FileRepMax" => 0,"Kb" => 0,"FileLinkTotal" => 0,"FileCntRm" => 0,"Time" => 1535839565,"KbRm" => 0,"FileCnt" => 0},{"FileCntRm" => 0,"Time" => 1535839565,"KbRm" => 0,"FileCnt" => 0,"FileLinkMax" => 0,"FileCntRep" => 0,"DirCnt" => 0,"FileRepMax" => 0,"Kb" => 0,"FileLinkTotal" => 0},{"FileLinkMax" => 0,"FileRepMax" => 0,"Kb" => 0,"FileLinkTotal" => 0,"FileCntRep" => 0,"DirCnt" => 0,"FileCntRm" => 0,"Time" => 1535839662,"KbRm" => 0,"FileCnt" => 0},{"FileCnt" => 0,"KbRm" => 0,"Time" => 1535839662,"FileCntRm" => 0,"DirCnt" => 0,"FileCntRep" => 0,"FileLinkTotal" => 0,"Kb" => 0,"FileRepMax" => 0,"FileLinkMax" => 0},{"KbRm" => 0,"FileCnt" => 0,"FileCntRm" => 0,"Time" => 1535839662,"FileCntRep" => 0,"DirCnt" => 0,"FileRepMax" => 0,"Kb" => 0,"FileLinkTotal" => 0,"FileLinkMax" => 0},{"FileLinkMax" => 0,"DirCnt" => 0,"FileCntRep" => 0,"FileLinkTotal" => 0,"Kb" => 0,"FileRepMax" => 0,"Time" => 1535839662,"FileCntRm" => 0,"FileCnt" => 0,"KbRm" => 0},{"DirCnt" => 0,"FileCntRep" => 0,"FileLinkTotal" => 0,"FileRepMax" => 0,"Kb" => 0,"FileLinkMax" => 0,"FileCnt" => 0,"KbRm" => 0,"Time" => 1535839662,"FileCntRm" => 0},{"Time" => 1535839662,"FileCntRm" => 0,"FileCnt" => 0,"KbRm" => 0,"FileLinkMax" => 0,"FileLinkTotal" => 0,"Kb" => 0,"FileRepMax" => 0,"DirCnt" => 0,"FileCntRep" => 0},{"FileCnt" => 0,"KbRm" => 0,"Time" => 1535839662,"FileCntRm" => 0,"DirCnt" => 0,"FileCntRep" => 0,"FileLinkTotal" => 0,"FileRepMax" => 0,"Kb" => 0,"FileLinkMax" => 0},{"FileCntRep" => 0,"DirCnt" => 0,"FileRepMax" => 0,"Kb" => 0,"FileLinkTotal" => 0,"FileLinkMax" => 0,"KbRm" => 0,"FileCnt" => 0,"FileCntRm" => 0,"Time" => 1535839662}],"cpool" => [{"FileLinkMax" => 0,"DirCnt" => 0,"FileCntRep" => 0,"FileLinkTotal" => 0,"FileRepMax" => 0,"Kb" => 0,"Time" => 0,"FileCntRm" => 0,"FileCnt" => 0,"KbRm" => 0,"FileCntRename" => 0},{"Kb" => 0,"FileRepMax" => 0,"FileLinkTotal" => 0,"FileCntRep" => 0,"DirCnt" => 0,"FileLinkMax" => 0,"FileCntRename" => 0,"KbRm" => 0,"FileCnt" => 0,"FileCntRm" => 0,"Time" => 0},{"FileRepMax" => 0,"Kb" => 0,"FileLinkTotal" => 0,"FileCntRep" => 0,"DirCnt" => 0,"FileLinkMax" => 0,"FileCntRename" => 0,"KbRm" => 0,"FileCnt" => 0,"FileCntRm" => 0,"Time" => 0},{"FileCntRm" => 0,"Time" => 0,"KbRm" => 0,"FileCnt" => 0,"FileCntRename" => 0,"FileLinkMax" => 0,"FileCntRep" => 0,"DirCnt" => 0,"FileRepMax" => 0,"Kb" => 0,"FileLinkTotal" => 0},{"FileCntRename" => 0,"KbRm" => 0,"FileCnt" => 0,"FileCntRm" => 0,"Time" => 0,"Kb" => 0,"FileRepMax" => 0,"FileLinkTotal" => 0,"FileCntRep" => 0,"DirCnt" => 0,"FileLinkMax" => 0},{"KbRm" => 0,"FileCnt" => 0,"FileCntRename" => 0,"FileCntRm" => 0,"Time" => 0,"FileCntRep" => 0,"DirCnt" => 0,"FileRepMax" => 0,"Kb" => 0,"FileLinkTotal" => 0,"FileLinkMax" => 0},{"FileCntRep" => 0,"DirCnt" => 0,"Kb" => 0,"FileRepMax" => 0,"FileLinkTotal" => 0,"FileLinkMax" => 0,"KbRm" => 0,"FileCnt" => 0,"FileCntRename" => 0,"FileCntRm" => 0,"Time" => 0},{"FileLinkTotal" => 0,"FileRepMax" => 0,"Kb" => 0,"DirCnt" => 0,"FileCntRep" => 0,"FileLinkMax" => 0,"FileCntRename" => 0,"FileCnt" => 0,"KbRm" => 0,"Time" => 0,"FileCntRm" => 0},{"FileLinkMax" => 0,"Kb" => 0,"FileRepMax" => 0,"FileLinkTotal" => 0,"FileCntRep" => 0,"DirCnt" => 0,"FileCntRm" => 0,"Time" => 0,"FileCntRename" => 0,"KbRm" => 0,"FileCnt" => 0},{"FileLinkMax" => 0,"DirCnt" => 0,"FileCntRep" => 0,"FileLinkTotal" => 0,"Kb" => 0,"FileRepMax" => 0,"Time" => 0,"FileCntRm" => 0,"FileCnt" => 0,"KbRm" => 0,"FileCntRename" => 0},{"KbRm" => 0,"FileCnt" => 0,"FileCntRename" => 0,"FileCntRm" => 0,"Time" => 0,"FileCntRep" => 0,"DirCnt" => 0,"Kb" => 0,"FileRepMax" => 0,"FileLinkTotal" => 0,"FileLinkMax" => 0},{"FileCntRename" => 0,"KbRm" => 0,"FileCnt" => 0,"FileCntRm" => 0,"Time" => 0,"Kb" => 0,"FileRepMax" => 0,"FileLinkTotal" => 0,"FileCntRep" => 0,"DirCnt" => 0,"FileLinkMax" => 0},{"FileCntRename" => 0,"FileCnt" => 0,"KbRm" => 0,"Time" => 0,"FileCntRm" => 0,"FileLinkTotal" => 0,"FileRepMax" => 0,"Kb" => 0,"DirCnt" => 0,"FileCntRep" => 0,"FileLinkMax" => 0},{"FileLinkMax" => 0,"DirCnt" => 0,"FileCntRep" => 0,"FileLinkTotal" => 0,"FileRepMax" => 0,"Kb" => 0,"Time" => 0,"FileCntRm" => 0,"FileCnt" => 0,"KbRm" => 0,"FileCntRename" => 0},{"FileCntRename" => 0,"FileCnt" => 0,"KbRm" => 0,"Time" => 0,"FileCntRm" => 0,"FileLinkTotal" => 0,"FileRepMax" => 0,"Kb" => 0,"DirCnt" => 0,"FileCntRep" => 0,"FileLinkMax" => 0},{"FileCntRm" => 0,"Time" => 0,"FileCntRename" => 0,"KbRm" => 0,"FileCnt" => 0,"FileLinkMax" => 0,"Kb" => 0,"FileRepMax" => 0,"FileLinkTotal" => 0,"FileCntRep" => 0,"DirCnt" => 0}],"pool" => [{"FileLinkTotal" => 0,"FileRepMax" => 0,"Kb" => 0,"DirCnt" => 0,"FileCntRep" => 0,"FileLinkMax" => 0,"FileCntRename" => 0,"FileCnt" => 0,"KbRm" => 0,"Time" => 0,"FileCntRm" => 0},{"Time" => 0,"FileCntRm" => 0,"FileCntRename" => 0,"FileCnt" => 0,"KbRm" => 0,"FileLinkMax" => 0,"FileLinkTotal" => 0,"FileRepMax" => 0,"Kb" => 0,"DirCnt" => 0,"FileCntRep" => 0},{"Time" => 0,"FileCntRm" => 0,"FileCnt" => 0,"KbRm" => 0,"FileCntRename" => 0,"FileLinkMax" => 0,"DirCnt" => 0,"FileCntRep" => 0,"FileLinkTotal" => 0,"Kb" => 0,"FileRepMax" => 0},{"FileCntRep" => 0,"DirCnt" => 0,"FileRepMax" => 0,"Kb" => 0,"FileLinkTotal" => 0,"FileLinkMax" => 0,"KbRm" => 0,"FileCnt" => 0,"FileCntRename" => 0,"FileCntRm" => 0,"Time" => 0},{"FileLinkMax" => 0,"DirCnt" => 0,"FileCntRep" => 0,"FileLinkTotal" => 0,"Kb" => 0,"FileRepMax" => 0,"Time" => 0,"FileCntRm" => 0,"FileCnt" => 0,"KbRm" => 0,"FileCntRename" => 0},{"FileLinkMax" => 0,"FileCntRep" => 0,"DirCnt" => 0,"Kb" => 0,"FileRepMax" => 0,"FileLinkTotal" => 0,"FileCntRm" => 0,"Time" => 0,"KbRm" => 0,"FileCnt" => 0,"FileCntRename" => 0},{"DirCnt" => 0,"FileCntRep" => 0,"FileLinkTotal" => 0,"Kb" => 0,"FileRepMax" => 0,"FileLinkMax" => 0,"FileCnt" => 0,"KbRm" => 0,"FileCntRename" => 0,"Time" => 0,"FileCntRm" => 0},{"FileLinkMax" => 0,"FileLinkTotal" => 0,"FileRepMax" => 0,"Kb" => 0,"DirCnt" => 0,"FileCntRep" => 0,"Time" => 0,"FileCntRm" => 0,"FileCntRename" => 0,"FileCnt" => 0,"KbRm" => 0},{"KbRm" => 0,"FileCnt" => 0,"FileCntRename" => 0,"FileCntRm" => 0,"Time" => 0,"FileCntRep" => 0,"DirCnt" => 0,"FileRepMax" => 0,"Kb" => 0,"FileLinkTotal" => 0,"FileLinkMax" => 0},{"FileCntRm" => 0,"Time" => 0,"KbRm" => 0,"FileCnt" => 0,"FileCntRename" => 0,"FileLinkMax" => 0,"FileCntRep" => 0,"DirCnt" => 0,"Kb" => 0,"FileRepMax" => 0,"FileLinkTotal" => 0},{"FileCntRm" => 0,"Time" => 0,"FileCntRename" => 0,"KbRm" => 0,"FileCnt" => 0,"FileLinkMax" => 0,"Kb" => 0,"FileRepMax" => 0,"FileLinkTotal" => 0,"FileCntRep" => 0,"DirCnt" => 0},{"FileLinkMax" => 0,"FileLinkTotal" => 0,"Kb" => 0,"FileRepMax" => 0,"DirCnt" => 0,"FileCntRep" => 0,"Time" => 0,"FileCntRm" => 0,"FileCntRename" => 0,"FileCnt" => 0,"KbRm" => 0},{"Time" => 0,"FileCntRm" => 0,"FileCnt" => 0,"KbRm" => 0,"FileCntRename" => 0,"FileLinkMax" => 0,"DirCnt" => 0,"FileCntRep" => 0,"FileLinkTotal" => 0,"Kb" => 0,"FileRepMax" => 0},{"FileLinkMax" => 0,"FileLinkTotal" => 0,"FileRepMax" => 0,"Kb" => 0,"DirCnt" => 0,"FileCntRep" => 0,"Time" => 0,"FileCntRm" => 0,"FileCntRename" => 0,"FileCnt" => 0,"KbRm" => 0},{"FileLinkMax" => 0,"FileLinkTotal" => 0,"FileRepMax" => 0,"Kb" => 0,"DirCnt" => 0,"FileCntRep" => 0,"Time" => 0,"FileCntRm" => 0,"FileCntRename" => 0,"FileCnt" => 0,"KbRm" => 0},{"FileCntRename" => 0,"FileCnt" => 0,"KbRm" => 0,"Time" => 0,"FileCntRm" => 0,"FileLinkTotal" => 0,"FileRepMax" => 0,"Kb" => 0,"DirCnt" => 0,"FileCntRep" => 0,"FileLinkMax" => 0}],"cpool4" => [{"FileCntRm" => 9,"Time" => 1535839566,"KbRm" => 3592,"FileCnt" => 26356,"FileLinkMax" => 245,"FileRepMax" => 0,"Kb" => 8719264,"FileLinkTotal" => 135507,"FileCntRep" => 0,"DirCnt" => 1032},{"DirCnt" => 1032,"FileCntRep" => 0,"FileLinkTotal" => 134962,"Kb" => 7703484,"FileRepMax" => 0,"FileLinkMax" => 444,"FileCnt" => 26313,"KbRm" => 11272,"Time" => 1535839566,"FileCntRm" => 17},{"KbRm" => 11784,"FileCnt" => 26462,"FileCntRm" => 12,"Time" => 1535839566,"FileCntRep" => 0,"DirCnt" => 1032,"Kb" => 8130608,"FileRepMax" => 0,"FileLinkTotal" => 134736,"FileLinkMax" => 610},{"Time" => 1535839567,"FileCntRm" => 21,"FileCnt" => 26487,"KbRm" => 64528,"FileLinkMax" => 360,"FileLinkTotal" => 137570,"Kb" => 8910292,"FileRepMax" => 0,"DirCnt" => 1032,"FileCntRep" => 0},{"FileLinkMax" => 632,"DirCnt" => 1032,"FileCntRep" => 0,"FileLinkTotal" => 138504,"FileRepMax" => 0,"Kb" => 12869736,"Time" => 1535839567,"FileCntRm" => 11,"FileCnt" => 26649,"KbRm" => 2956},{"FileLinkTotal" => 139879,"FileRepMax" => 0,"Kb" => 11025116,"DirCnt" => 1032,"FileCntRep" => 0,"FileLinkMax" => 2245,"FileCnt" => 26572,"KbRm" => 6036,"Time" => 1535839567,"FileCntRm" => 17},{"KbRm" => 23312,"FileCnt" => 26632,"FileCntRm" => 20,"Time" => 1535839567,"Kb" => 9260228,"FileRepMax" => 0,"FileLinkTotal" => 140267,"FileCntRep" => 0,"DirCnt" => 1032,"FileLinkMax" => 2395},{"FileCnt" => 26559,"KbRm" => 72496,"Time" => 1535839568,"FileCntRm" => 21,"DirCnt" => 1032,"FileCntRep" => 0,"FileLinkTotal" => 136987,"Kb" => 10485664,"FileRepMax" => 0,"FileLinkMax" => 928},{"DirCnt" => 1032,"FileCntRep" => 0,"FileLinkTotal" => 136820,"FileRepMax" => 0,"Kb" => 11097836,"FileLinkMax" => 650,"FileCnt" => 26470,"KbRm" => 92256,"Time" => 1535839662,"FileCntRm" => 13},{"FileLinkTotal" => 135899,"Kb" => 8112264,"FileRepMax" => 0,"DirCnt" => 1032,"FileCntRep" => 0,"FileLinkMax" => 565,"FileCnt" => 26530,"KbRm" => 3348,"Time" => 1535839663,"FileCntRm" => 19},{"FileLinkMax" => 344,"Kb" => 9465988,"FileRepMax" => 0,"FileLinkTotal" => 137506,"FileCntRep" => 0,"DirCnt" => 1032,"FileCntRm" => 15,"Time" => 1535839663,"KbRm" => 18492,"FileCnt" => 26760},{"FileLinkMax" => 387,"FileLinkTotal" => 135658,"Kb" => 8387212,"FileRepMax" => 0,"DirCnt" => 1032,"FileCntRep" => 0,"Time" => 1535839664,"FileCntRm" => 19,"FileCnt" => 26480,"KbRm" => 243552},{"FileLinkMax" => 456,"FileCntRep" => 0,"DirCnt" => 1032,"FileRepMax" => 0,"Kb" => 14343724,"FileLinkTotal" => 135557,"FileCntRm" => 17,"Time" => 1535839664,"KbRm" => 9404,"FileCnt" => 26790},{"KbRm" => 2628,"FileCnt" => 26341,"FileCntRm" => 13,"Time" => 1535839664,"FileRepMax" => 0,"Kb" => 9172844,"FileLinkTotal" => 139933,"FileCntRep" => 0,"DirCnt" => 1032,"FileLinkMax" => 2475},{"FileCnt" => 26350,"KbRm" => 216,"Time" => 1535839665,"FileCntRm" => 12,"DirCnt" => 1032,"FileCntRep" => 0,"FileLinkTotal" => 137444,"Kb" => 6547612,"FileRepMax" => 0,"FileLinkMax" => 945},{"FileCntRm" => 15,"Time" => 1535839665,"KbRm" => 10636,"FileCnt" => 26333,"FileLinkMax" => 350,"FileCntRep" => 0,"DirCnt" => 1032,"Kb" => 15063028,"FileRepMax" => 0,"FileLinkTotal" => 136447}]},"pool4FileRepMax" => 0,"DUDailyMaxStartTime" => 1535839200,"pool4FileCnt" => 0,"DUDailyMaxReset" => 0,"poolFileCntRm" => 0,"cpool4FileLinkMax" => 2475,"DUDailyMaxTime" => 1535839834,"poolFileCnt" => 0,"DUlastValue" => 64,"cpoolFileRepMax" => 0,"pool4KbRm" => 0,"DUDailyMax" => 65,"cpoolDirCnt" => 0,"cpool4KbRm" => 576508,"pool4FileCntRename" => 0,"cpool4Kb" => 159294900,"pid" => 238);
`

Runnning version 4.1.5

**Comment by craigbarratt** [comment]
What do you mean by "duplicates"?  Ie: what specific status message are you referring to?

The status page might say "Pool hashing gives 0 repeated files".  That refers to the number of different pool files that have the same md5 digest.  It's normally 0.

**Comment by 8666** [comment]
If I have 3  files that are exactly the same, then I expect that some kind of statistics about that will be displayed... BackupPC_ls lists them as files with the same checksum (c14f8bb8f36466522ff2a159d926766a) ...

I am seeing this
[https://imgur.com/a/UGmKlUr](https://imgur.com/a/UGmKlUr)

on /BackupPC_Admin?action=status

**Comment by craigbarratt** [comment]
Everything is fine.  BackupPC doesn't report the number of times a pool file is referenced (but you can find using some of the BackupPC tools if you really need to know).  The stats you are looking report something quite different: the number of unique files in the pool and the number of times different pool files have the same md5 digest (which is very unlikely in the wild).
