### ISSUE TITLE
Status Active even after reboot

### ISSUE THREAD

**Issue by 8666** [backuppc/backuppc#220]
If the backuppc machine is rebooted during active backup the backup jobs stay with status "active"

Backup# | Type | Filled | Level | Start Date | Duration/mins | Age/days | Server Backup Path
-- | -- | -- | -- | -- | -- | -- | --
0 | full | yes | 0 | 6/25 19:18 | 3.4 | 68.8 | /var/lib/backuppc/pc/pi0/0
31 | incr | no | 1 | 8/31 00:00 | 17.1 | 2.6 | /var/lib/backuppc/pc/pi0/31
32 | incr | no | 1 | 9/1 00:00 | 14.2 | 1.6 | /var/lib/backuppc/pc/pi0/32
33 | incr | no | 1 | 9/2 00:00 | 12.4 | 0.6 | /var/lib/backuppc/pc/pi0/33
34 | **active** | no | 0 | 9/2 13:40 |   | 0.0 | /var/lib/backuppc/pc/pi0/34 (was rebooted here)
35 | **active** | yes | 0 | 9/2 13:42 |   | 0.0 | /var/lib/backuppc/pc/pi0/35  (new manual backup)

There should be some sanitize function on backuppc start so status is update properly.

 version 4.1.5

**Comment by craigbarratt** [comment]
Pushed fix f6f76e7.
