### ISSUE TITLE
Latest backuppc to debian

### ISSUE THREAD

**Issue by trentasis** [backuppc/backuppc#221]
Please, update latest backuppc version to Debian Stable

Thanks

**Comment by raoulbhatia** [comment]
Hi @trentasis - there is currently no active Debian maintainer working on this.

There is already a bug filed for this - see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=873075

The packages have been orphaned and need a maintainer, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=887490

Anybody is welcome to jump in and help.  In the meantime, you can check if one of https://github.com/backuppc/backuppc/wiki/Build-Your-Own-Packages#downloads fits your needs.
(Happy to create & upload a new package for i.e. a specific Debian version on request)

Raoul

**Comment by raoulbhatia** [comment]
@craigbarratt feel free to close this issue.
