### ISSUE TITLE
RSS Stage field fail to report disabled backups

### ISSUE THREAD

**Issue by danielmotaleite** [backuppc/backuppc#222]
Using backuppc  4.2.1, and trying to use RSS to do a basic healthcheck, i found that it do not report what backups are disabled, making hard to see what backups are failing and those that are simply disabled

```
 curl -s 'https://backuppc.example.com:8080/BackupPC_Admin?action=rss'

(...)
<item>
<title>backuppc-a01, idle, idle</title>
<link>https://backuppc.example.com/BackupPC_Admin?host=backuppc-a01</link>
<description>Full Count: 4;
Full Age/days: 2.9;
Full Size/GiB: 0.00;
Speed MiB/sec: 0.02;
Incr Count: 11;
Incr Age/Days: 0.9;
State: idle;
Last Attempt: idle;
</description>
</item>
(...)

```

I would say that the `State` should be `disable` instead of `idle`

**Comment by craigbarratt** [comment]
Rather than override State, I added a new value "Disabled" which is the value of $Conf{BackupsDisable}.  Commit 2cd21e2.
