### ISSUE TITLE
Add a reference to the RSS to the documentation

### ISSUE THREAD

**Issue by danielmotaleite** [backuppc/backuppc#223]
RSS is hidden, documentation make no reference to it and only looking to the source one can find it

please add a small reference to it, with a example URL:

https://backuppc.example.com/BackupPC_Admin?action=rss

**Comment by craigbarratt** [comment]
It's already in the [documentation](https://backuppc.github.io/backuppc/BackupPC.html#RSS)

**Comment by danielmotaleite** [comment]
sorry, either i was searching in the wrong documentation or i'm blind! :)

How about adding a link to the rss feed in the backuppc page, below the "current queues" ? that would give it more visibility, as the browser do not detect the RSS, so if gives no feedback that it exists.
