### ISSUE TITLE
File exclusions not actually being excluded

### ISSUE THREAD

**Issue by paulemurray** [backuppc/backuppc#226]
Here is the CGI config for file exclusions, shown at the top is all the slash combinations/configurations I've tried (as well with forward slashes instead of backslashes), none of which have actually worked. It seems from what I've looked up that it's an issue may people have/are having. 

![capture](https://user-images.githubusercontent.com/36320737/46313885-a93a5380-c58e-11e8-8d11-16c9e742652e.PNG)

Both BackupPC and Samba are fully up to date, as well as the versions of Windows on the clients

**Comment by haarp** [comment]
Figuring out excludes, especially for Windows hosts, is excrutiatingly difficult. Here's waht works for me (on BPC 3 at least)

![screenshot_2018-10-09_10-13-17](https://user-images.githubusercontent.com/781030/46655527-1f047780-cbac-11e8-840f-57b085e39063.png)

I do think BackupPC should do better abstractions.

**Comment by paulemurray** [comment]
That worked, thanks so much! I thought I had tried something like that but I guess not because everything works fine now.
