### ISSUE TITLE
Xfer PID shows as Hash of Hex number during a merge of backups

### ISSUE THREAD

**Issue by nerrehmit** [backuppc/backuppc#237]
Hi Craig

BackupPC Version 4.2.1

When I delete a backup the delete job under "currently running jobs" on the status page shows "HASH(0x0ca9028).
I understand that during a merge there is no Transfer PID available but maybe the field should then just be blank?

I added a screen shot for clarification. The upper is a delete job, the lower is a regular backup job without issues.
![backuppc-xfer-pid-merge](https://user-images.githubusercontent.com/15264624/48631697-69ed8800-e9bf-11e8-9e56-c43f14ccfa01.png)

**Comment by craigbarratt** [comment]
Thanks for reporting this.  I noticed that too and it got fixed about a month ago with this commit https://github.com/backuppc/backuppc/commit/4bc00a5e1e5b029a9de54770811c407de586e2c4.

**Comment by nerrehmit** [comment]
Perfect, thanks a lot. I'll wait for the next release.
