### ISSUE TITLE
Random tab order in EditConfig

### ISSUE THREAD

**Issue by palego** [backuppc/backuppc#24]
Hello,

On the Edit Config page, the tabs are in an unpredictable order, and selecting one or refreshing the page change their order.
This happens because, since Perl 5.18, the order of keys in a hash is randomized on each access.
Before that, the order was decided at population time, and was mostly predictable for a given set of keys fed in a given order.
PR #23 proposes the simple fix of sorting the keys in the relevant foreach loops.

**Comment by craigbarratt** [comment]
PR #23 applied; also to v3.x.x.  Thanks.
