### ISSUE TITLE
How to restore backup (Direct Restore) by command (not by GUI) in backuppc

### ISSUE THREAD

**Issue by surjitiit** [backuppc/backuppc#243]
I have setup backuppc on my server. All things are working fine. And manual restoration (By GUI) are working. 
Now i want to restore backuped file or dir (Direct Restore) by command line or by cron. So how i do it. Which script i need to run?

**Comment by craigbarratt** [comment]
For user questions, please send an email to the user list.  Git issues are for reporting bugs or discussing features.
