### ISSUE TITLE
Bug in /lang/en.pm

### ISSUE THREAD

**Issue by karlis-irmejs** [backuppc/backuppc#245]
BackupPC v. 4.3.0 (and previous v. 4.2.1)

On page 'Host Summary' table 'Hosts with no backups' data columns are shifted to right relative to table and last data column is outside the table. It's due to missing table column 'Comment' in /lib/BackupPC/lang/en.pm (perhaps other languages too, at least DE the same). Corrected by adding missing line 192.

```
\${h2("Hosts with no Backups")}
<p>
There are \$hostCntNone hosts with no backups.
<p>
<table class="sortable" id="host_summary_nobackups" border cellpadding="3" cellspacing="1">
<tr class="tableheader"><td> Host </td>
    <td align="center"> User </td>
+   <td align="center"> Comment </td>
    <td align="center"> #Full </td>
    <td align="center"> Full Age (days) </td>
```

**Comment by craigbarratt** [comment]
Thanks for reporting this.  I pushed a fix to all the lang files: f217ddd.
