### ISSUE TITLE
backuppc > rsync skips mounted partitions

### ISSUE THREAD

**Issue by huglester** [backuppc/backuppc#248]
I am backuping up using rsync method (over ssh)-  works

I have some exclude parameters - works

But one directory - /home/m is mounted from /dev/sdb1 disk, and it is not included in the backup.
How I can make it work?

Version 4.2.1

Thank you

**Comment by SpareSimian** [comment]
Could this be a --one-file-system issue? If that's in your rsync options, rsync won't hop over into another filesystem. Usually, that's desired. Perhaps you should back up the other filesystem with a separate share or even another host.

**Comment by craigbarratt** [comment]
@SpareSimian  is right.  $Conf{RsyncArgs} by default includes --one-file-system.  If you remove --one-file-system please make sure you are excluding /proc.

**Comment by huglester** [comment]
Thanks. 
Why do you suggest creating separate host for this? Ar there any issues when backing up multiple filesystems?

Thabk you

**Comment by SpareSimian** [comment]
It depends on how long the backup takes. I've broken up large backups into multiple hosts because they time out or because the backup runs into the morning when people arrive to use their computers and they reboot to fix the slowness, aborting the backup.

**Comment by huglester** [comment]
Valid point. Thank you!
