### ISSUE TITLE
tarExtract exited with fail status 256 after upgrade 4.2.1 to 4.3.0

### ISSUE THREAD

**Issue by 77os** [backuppc/backuppc#256]
Hi, we've been using backuppc during 12 years, and updating and upgrading from 2.x 3.x and 4.x

Right now our server:
Ubuntu server 16.04.5 LTS
Backuppc 4.3.0

After upgrade from 4.2.1 to 4.3.0 we get this error during windows hosts backups:
Got fatal error during xfer (BackupPC_tarExtract exited with fail status 256)

Please help!

**Comment by craigbarratt** [comment]
Can you review the XferLOG file and see what errors or warnings  are reported?

**Comment by 77os** [comment]
In the XferLOG:

tarExtract: BackupPC_tarExtact aborting (Unexpected end of tar archive)
tarExtract: Done: 1 errors, 60914 filesExist, 31398995566 sizeExist, 2241321593 sizeExistComp, 60914 filesTotal, 31398995566 sizeTotal, 0 filesNew, 0 sizeNew, 0 sizeNewComp, 113690 inodeLast
BackupPC_tarExtract exited with fail status 256
Xfer PIDs are now
Got fatal error during xfer (BackupPC_tarExtract exited with fail status 256)

**Comment by 77os** [comment]
Finally we solved this issue installing cygwin on windows hosts and using cygwin-rsyncd instead of smb.
