### ISSUE TITLE
RRDTool Graphs

### ISSUE THREAD

**Issue by maksyms** [backuppc/backuppc#26]
Dear authors,

  I can see that Ubuntu version of backuppc has the patch that produces pool size and utilisation on the front page. This repository does not have it. Does it mean that is a modification you guys don't want to incorporate into the code, or simply that you had no chance to do so yet?

Thanks,
  Maksym

**Comment by moisseev** [comment]
It is already in the master:
https://github.com/backuppc/backuppc/blob/master/bin/BackupPC_rrdUpdate

I'd like to add it to `v3` as well, but last time I proposed this, Craig answered he don't plan add any features to `v3`, merely fixes.
In case he changed his mind I can open a PR, the patch is ready:
https://github.com/moisseev/BackupPC/commit/28bb59f29e31bb0571d72f99d5c3823f5ea51000

**Comment by maksyms** [comment]
Thanks for that. The RRD functionality, although using different code to @moisseev's, is included by default in Ubuntu. And it gets broken with each update. The fix for the version of BackupPC that gets shipped with Ubuntu is [here](https://bugs.launchpad.net/ubuntu/+source/backuppc/+bug/1612600).

It is quite inconvenient to have Ubuntu's version, where both Samba backups and RRD graphs don't work, Github version, where Samba compatibility was recently fixed, but RRD functionality isn't present at all, and the actual version on my server, where both Samba and RRD are fixed. Ah well, Open Source. :-)
