### ISSUE TITLE
[Improvement] Provide port in error message shown by client when BackupPC server is unavailable

### ISSUE THREAD

**Issue by dmak** [backuppc/backuppc#261]
When BackupPC server is not reachable on some reason the following error message is shown:
```
This CGI script (/backuppc/index.cgi) is unable to connect to the BackupPC server on ... port -1.
The error was: unix connect: Connection refused.
```
It would b nice if this error message prints the actual port. This can help to trace down/debug the problem.

**Comment by craigbarratt** [comment]
The error message does contain the actual port: $Conf{ServerPort}, which is -1 in your case.

However, BackupPC also tries the unix-domain socket at $Conf{RunDir}/BackupPC.sock.  The error message you saw (unix connect failed) suggests that the unix socket connect didn't work.

**Comment by dmak** [comment]
I got it. Maybe the message should then refer the Unix socket, e.g. "$Conf{RunDir}/BackupPC.sock" as you said?

**Comment by craigbarratt** [comment]
I added the socket file name to the unix connect error message and the port number to the inet connection error messages.  Commit 22af954.
