### ISSUE TITLE
backuppc behind nginx - nginx on other machine

### ISSUE THREAD

**Issue by mamema** [backuppc/backuppc#262]
Hi

i'm using latest backuppc and want to connect emotely to it. I have nginx on another host, not on same host where backuppc is running on.

So, i'm struggling to get the nginx config working to connect to the backuppc host. The configs on the internet are all for nginx configs if backuppc and nginx are on the same host.

**Comment by craigbarratt** [comment]
Git issues are for bug reports or feature requests.  Please post your question to the user list.
