### ISSUE TITLE
How to Uninstall?

### ISSUE THREAD

**Issue by Wasca** [backuppc/backuppc#263]
Hi

I've just installed using the installbackuppc script (https://github.com/backuppc/backuppc/wiki/Installing-BackupPC-4-from-tarball-or-git-on-Ubuntu), just wondering how to uninstall now?

I'd like to go back to the start and try installing to a new location on my server. It appears it installed Backuppc in the folder I was executing the script from, in my case I was in /root/, does that sound right?

I now see these folders in my /root folder

```
BackupPC-4.3.0
BackupPC-XS-0.59
rsync-bpc-3.1.2.0
```

and the install script...

`installbackuppc`

**Comment by craigbarratt** [comment]
Please post these questions on the user list.  Git issues are for potential bugs or feature requests.
