### ISSUE TITLE
Main_Initialize should check process name in addition to PID when looking for existing BackupPC instance

### ISSUE THREAD

**Issue by toggoboge** [backuppc/backuppc#264]
Hi,
I am running BackupPC inside a container using Adrien Ferrand's docker image ("docker pull adferrand/backuppc"). This currently gives me BackupPC version 4.3.0. For reasons unrelated to BackupPC, I power-cycled my server. When I it came back up, I saw the following repeated in my docker logs:

```
[root@comte ~]# docker logs --since 120m backuppc
2019-04-21 02:00:04 [1382] | 2019-04-21 02:00:04 Another BackupPC is running (pid 18); quitting...
2019-04-21 02:00:09 [1384] | 2019-04-21 02:00:09 Another BackupPC is running (pid 18); quitting...
2019-04-21 02:00:14 [1386] | 2019-04-21 02:00:14 Another BackupPC is running (pid 18); quitting...
```

However, inside the container, I see this (though this is **after** I had resolved the problem, so `BackupPC` is running):

```
bash-4.4# ps
PID   USER     TIME  COMMAND
    1 root      0:00 {run.sh} /bin/sh /run.sh
   14 root      0:21 {circusd} /usr/bin/python3.6 /usr/bin/circusd /etc/circus.ini
   18 backuppc  0:02 /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf -D
   24 root      0:00 /bin/bash
  597 backuppc  0:01 {BackupPC} /usr/bin/perl /usr/local/BackupPC/bin/BackupPC
  655 root      0:00 ps
```

So PID 18 is `lighttpd`, not `BackupPC` (and it is started as user backuppc which seems to be relevant to [perl's kill](https://perldoc.perl.org/functions/kill.html)).

I found someone else had had the same problem in 2017 ("Problems Starting BackupPC") and the solution specified [here](https://sourceforge.net/p/backuppc/mailman/backuppc-users/thread/CADSzEFgdc0kFxNMdokYruzPFMy1Qb447bZ-CS9HbKYfFAC%2BTwA%40mail.gmail.com/#msg35868434) worked for me. That was simply to remove the line in `status.pl` (located at `/data/backuppc/log/status.pl` in my container) which indicated the PID of the `BackupPC` process.

As speculated in the linked discussion, in my case at least, the cause of this appears be that [Main_Initialize](https://github.com/backuppc/backuppc/blob/b6f764204dbd72a39104d52eba726482051dcb88/bin/BackupPC#L267) doesn't check that the process which matches the previous BackupPC instance's PID is in fact a BackupPC process:

``` perl
sub Main_Initialize
{
    umask($Conf{UmaskMode});

    #
    # Check for another running process, verify executables are configured
    # correctly and make sure $TopDir is on a file system that supports
    # hardlinks.
    #
    if ( $Info->{pid} ne "" && kill(0, $Info->{pid}) ) {
        print(STDERR $bpc->timeStamp,
                 "Another BackupPC is running (pid $Info->{pid}); quitting...\n");
        exit(1);
    }
```

The problem could be avoided if `Main_Initialize` were to also check the process name. I'm not a perl programmer, but this seems to be a little tricky to do in a way that is fully portable???

Thanks,
Brian

**Comment by craigbarratt** [comment]
Yes, I'm not sure how to do this in a portable manner.  Let me think about it.

**Comment by craigbarratt** [comment]
One option is to have BackupPC try to connect to the existing server if it thinks the PID is alive:
```perl
if ( $Info->{pid} ne "" && kill(0, $Info->{pid}) && !$bpc->ServerConnect($Conf{ServerHost}, $Conf{ServerPort}) ) {
    print(STDERR $bpc->timeStamp,
             "Another BackupPC is running (pid $Info->{pid}); quitting...\n");
    exit(1);
}
```

**Comment by craigbarratt** [comment]
I decided to commit this change cd3e375.

**Comment by toggoboge** [comment]
Thanks, Craig. Brian
