### ISSUE TITLE
RsyncShareName with accents

### ISSUE THREAD

**Issue by Yann79** [backuppc/backuppc#266]
Hello,
I am running BackupPC version 4.3.0 on Fedora 29.
I am doing the backup with rsync of a Ubuntu 18.04. 

When I add in RsyncShareName an accentuated name (ie. "Modèles"), BackupPC identifies the share as an orphan and the process ends with a delete of the files.
I get the typical log sequence:

...

> Running: /usr/bin/rsync_bpc --bpc-top-dir /var/lib/BackupPC/ --bpc-host-name nvie --bpc-share-name Modèles --bpc-bkup-num 4 --bpc-bkup-comp 3 --bpc-bkup-prevnum 3 --bpc-bkup-prevcomp 3 --bpc-bkup-inode0 96692 --bpc-attrib-new --bpc-log-level 1 -e /usr/bin/ssh\ -l\ ys --rsync-path=/usr/bin/rsync --super --recursive --protect-args --numeric-ids --perms --owner --group -D --times --links --hard-links --delete --delete-excluded --one-file-system --partial --log-format=log:\ %o\ %i\ %B\ %8U,%8G\ %9l\ %f%L --stats --timeout=72000 nvie-1:Modèles/ /
> incr backup started for directory Modèles
> Xfer PIDs are now 1762
> This is the rsync child about to exec /usr/bin/rsync_bpc
> Xfer PIDs are now 1762,1765
> xferPids 1762,1765
>     new    recv cd+++++++++ rwxr-xr-x     1000,    1000      4096 .
>     pool   recv >f+++++++++ rwxr--r--     1000,    1000   2381868 template.02.pptx
>     pool   recv >f+++++++++ rw-r--r--     1000,    1000    231424 Modele 1.doc
>     pool   recv >f+++++++++ rw-r--r--     1000,    1000    226304 Modele 2.doc
>     pool   recv >f+++++++++ rw-rw-r--     1000,    1000      9216 Note.doc
>     pool   recv >f+++++++++ rw-rw-rw-     1000,    1000     11264 Thumbs.db
>     same   recv >f+++++++++ rw-rw-r--     1000,    1000         0 Thumbs.db:encryptable
> Done: 0 errors, 5 filesExist, 2860076 sizeExist, 2747541 sizeExistComp, 0 filesTotal, 0 sizeTotal, 0 filesNew, 0 sizeNew, 0 sizeNewComp, 96707 inode
> 
> Number of files: 7 (reg: 6, dir: 1)
> Number of created files: 7 (reg: 6, dir: 1)
> Number of deleted files: 0
> Number of regular files transferred: 6
> Total file size: 2,860,076 bytes
> Total transferred file size: 2,860,076 bytes
> Literal data: 2,860,076 bytes
> Matched data: 0 bytes
> File list size: 246
> File list generation time: 0.001 seconds
> File list transfer time: 0.000 seconds
> Total bytes sent: 148
> Total bytes received: 2,861,274
> 
> sent 148 bytes  received 2,861,274 bytes  1,907,614.67 bytes/sec
> total size is 2,860,076  speedup is 1.00
> DoneGen: 0 errors, 0 filesExist, 0 sizeExist, 0 sizeExistComp, 6 filesTotal, 2860076 sizeTotal, 0 filesNew, 0 sizeNew, 0 sizeNewComp, 96694 inode

....

followed at the end by:

...

> Xfer PIDs are now 
> Finished BackupPC_backupDelete, status = 0 (running time: 0 sec)
> Xfer PIDs are now 
> OrphanShareNameClean: removing orphan share Modèles from /var/lib/BackupPC//pc/xxxx/4
> Xfer PIDs are now 1785
> BackupPC_backupDelete: removing #4/Modèles
> BackupPC_backupDelete: Merge into backup 3/Modèles
> Xfer PIDs are now 1786,1785
> BackupPC_refCountUpdate: host nvie got 0 errors (took 1 secs)
> Xfer PIDs are now 1785
> Xfer PIDs are now 
> Finished BackupPC_backupDelete, status = 0 (running time: 1 sec)

...

I have checked server and client PC. Both return the same answer to the command:
`locale -c charmap`
> LC_CTYPE
> UTF-8

In the config file, the `ClientCharset `const is left empty (default value utf8 should be used). And `ClientCharsetLegacy` is set to "iso-8859-1".
[config.pl.txt](https://github.com/backuppc/backuppc/files/3179009/config.pl.txt)

**Comment by craigbarratt** [comment]
Thanks for the detailed bug report.  I was able to replicate this.  I committed a fix 0675f5f.

**Comment by Yann79** [comment]
Great job. Thx a lot.

**Comment by kb3ien** [comment]
It's still this way in 4.4.0.
