### ISSUE TITLE
Mac clients offending key for IP

### ISSUE THREAD

**Issue by gseiki** [backuppc/backuppc#267]
I'm using backuppc to backup about 60 MacBooks on a DHCP network.  But, every 2-3 weeks clients stop backing up.  Once this happens, trying to ssh into clients from backuppc, gives me an **_offending key for ip_** error.  Then, I have to edit backuppc's known_hosts file and delete the line with the offending key. Once that's done, clients backup again for another 2-3 weeks.  I was thinking this was happening because the DHCP leases were expiring and clients were receiving new ip address from our network, but I'm not totally certain this is the case.  

A couple of things about my setup.  I don't have a local DNS server, but I'm using an Avahi server to do hostname resolution.  When I add a client to backuppc, I copy backuppc's ssh key to the client.  Then, I add the client to backuppc's gui using hostname and start backing up my clients.  One more note, selecting the DHCP box when adding a client to backuppc doesn't seem to help.  When I select DHCP, backuppc is unable to backup clients even though there are no offending keys. 

Any advice or help would be greatly appreciated.

**Comment by SpareSimian** [comment]
Something is changing your Mac's "host fingerprint". This isn't the key used for login. It's a different key used to identify the machine. Find out why the host key is changing.

Lots of background info about this here:

https://superuser.com/questions/421997/what-is-a-ssh-key-fingerprint-and-how-is-it-generated

**Comment by SpareSimian** [comment]
If you dual-boot, the host key needs to be the same for all operating systems that you plan to ssh into. 

https://www.insanelymac.com/forum/topic/300067-where-are-ssh-host-keys-located/

**Comment by gseiki** [comment]
Thanks for your help.  In the link you provided, I noticed load balancers were referenced as a potential cause of changed host fingerprints.  I'm using a Cisco network on a school campus.  Teachers can walk their device from one end of campus to the next, and the Cisco network passes their MacBooks on to the nearest wireless radio so their WiFi connection is uninterrupted by their travels.  The wireless radios are also suppose to distributing client sessions across access point radios with overlapping coverage.  Could this type of load balancing cause the host fingerprint issue I'm experiencing?

**Comment by SpareSimian** [comment]
Find your sshd_config file. On CentOS it's /etc/ssh/sshd_config. I think on Mac it's /etc/sshd_config. Look for the HostKey lines to see where your host keys are stored.  (There's one for each encryption protocol.) Look at the timestamps on those files. When did they change? What happened at that moment? You might also have access to a Mac utility that alerts you when a file changes, and you can configure it to watch those files and make a sound when they change.

**Comment by gseiki** [comment]
Thanks for pointing me in the right direction.  Your help aided me in troubleshooting this problem.  I setup a test network with one server and two client computers, A and B.  I'm know confident that expiring DHCP leases are the problem.  In my test system, my server can do password-less SSH into clients A and B, regardless of how many times their IP addresses have changed.  The problem arises when client B is issued an IP address previously used by client A or vice versa.  As a result, my server's known_hosts file will throw an **offending key for ip** error.

The VLAN that my Backuppc server is running on has a little over one hundred devices on it.  I'm trying to backup approximately 60 MacBooks on that VLAN.  When the DHCP leases expire, Backuppc clients are often re-issued different IP address.  This explains why my Backuppc server runs well for 2-3 weeks and then stops backing up computers.  My network administrator told me that 2-3 weeks is the approximate DHCP lease period on the VLAN I'm using. 

Moving forward, editing the ssh_config file on my server to reflect the following lines fixed the immediate problem.  However, it introduces a new problem in the form spoofing vulnerabilities. 
**CheckHostIP no
StrictHostKeyChecking no**

Do you know of a way to fix my problem without introducing security vulnerabilities?

**Comment by SpareSimian** [comment]
Which DHCP server are you using? The ISC implementation common with Linux distributions remembers expired leases and will try to re-issue the same address when a client eventually reappears. As long as the pool isn't exhausted by new devices, forcing reuse of expired addresses, expired clients will always get their old addresses. Unfortunately, other implementations may not do this, and will recycle expired leases.

**Comment by SpareSimian** [comment]
If a client is truly "permanent", have your DHCP admin give it a permanent address assignment. This is usually done with servers. Your backup clients are "servers" for purposes of hosting an ssh server, so they justify a permanent assignment.

**Comment by craigbarratt** [comment]
I think this issue is resolved; not really related to BackupPC.  Please re-open if not.
