### ISSUE TITLE
Rsync/ssh up on a non-standard port?

### ISSUE THREAD

**Issue by citadella** [backuppc/backuppc#269]
Hello there-I run several devices behind NAT and I typically use port 22 for the primary router and 2222 for my primary server behind. Is there any way to tailor the configs for an individual host to point at individual ports? I've been able to modify the rsync config within the config.pl file to point at -p 2222:
$Conf{RsyncClientCmd} = '$sshPath -q -x -p 2222 -l root $host $rsyncPath $argList+';
But that then means I'm only able to connect on port 2222 and never 22. I'd like this to be configurable on a per-host level.

**Comment by adamgoryachev** [comment]
On 26/6/19 18:51, citadella wrote:
>
> Hello there-I run several devices behind NAT and I typically use port 
> 22 for the primary router and 2222 for my primary server behind. Is 
> there any way to tailor the configs for an individual host to point at 
> individual ports? I've been able to modify the rsync config within the 
> config.pl file to point at -p 2222:
> $Conf{RsyncClientCmd} = '$sshPath -q -x -p 2222 -l root $host 
> $rsyncPath $argList+';
> But that then means I'm only able to connect on port 2222 and never 
> 22. I'd like this to be configurable on a per-host level.
>
> —
>
Easy, just put :

  $Conf{RsyncClientCmd} = '$sshPath -q -x -p 2222 -l root $host 
$rsyncPath $argList+';

Into the host files where you need it, you can set the -p parameter to 
whatever you need on a host by host basis.

This applies to most of the options in the main config, so you can 
override the global defaults for a specific host.

Regards,
Adam

**Comment by citadella** [comment]
Ahh, crap, yes-forgot about that. Just not intuitive to find, having to click on a host then find its settings link up top. In any case, figured it out-cheers!
