### ISSUE TITLE
Fix RunDir for tmpfs systems

### ISSUE THREAD

**Issue by johanehnberg** [backuppc/backuppc#27]
Modern distributions use tmpfs for pid files. Thus init scripts typically need to create a directory at boot in /var/run with permissions for non-root apps to store their pid. BackupPC has this variable in config.pl which is run after init and as the backuppc user so this is too late. Instead, the setting needs to be moved out to a more standard location, and the init script needs something like:

if [ ! -d /var/run/BackupPC ]; then
    mkdir -p /var/run/BackupPC
    chown backuppc:backuppc /var/run/BackupPC
    chmod 0755 /var/run/BackupPC
fi

The symptoms when hitting this problem are BackupPC not running and this in the LOG file:
unix bind() failed: Permission denied

One liner fix for existing installations:
sed '/test/a\ \nif [ ! -d /var/run/BackupPC ]; then\n  mkdir -p /var/run/BackupPC\n  chown backuppc:backuppc /var/run/BackupPC\n  chmod 0755 /var/run/BackupPC\nfi' /etc/init.d/backuppc

**Comment by craigbarratt** [comment]
Good point.  Currently the mkdir($Conf{RunDir}) is in configure.pl.  On my Ubuntu system it looks like the BackupPC user can successfully mkdir($Conf{RunDir}), so adding that to BackupPC's startup should solve the problem.

**Comment by craigbarratt** [comment]
I've added creation of $Conf{RunDir} to BackupPC's startup, and also to the linux template init.d scripts.
