### ISSUE TITLE
  Can't use an undefined value as a subroutine reference at /usr/local/www/cgi-bin/BackupPC_Admin line 109.

### ISSUE THREAD

**Issue by Martintoy** [backuppc/backuppc#270]
Hello, Im runing backuppc4 in FreeBSD.
However when I try to restore using rsync it says

Software error:
Can't use an undefined value as a subroutine reference at /usr/local/www/cgi-bin/BackupPC_Admin line 109.

My BackupPC_last ltine is like this. Not sure where to search

require "BackupPC/CGI/$action.pm"
            if ( !defined($BackupPC::CGI::{"${action}::"}) );
$BackupPC::CGI::{"${action}::"}{action}();

Please help, thanks in advance,
Martin

**Comment by moisseev** [comment]
What backuppc4 port version and Perl version are you using?

**Comment by Martintoy** [comment]
Thanks for your prompt answer, this port is from FreeBSD.

pkg info backuppc4
backuppc4-4.3.0
Name           : backuppc4
Version        : 4.3.0
Installed on   : Wed Jan 16 21:11:44 2019 -05
Origin         : sysutils/backuppc4
Architecture   : FreeBSD:11:*

And perl version
perl -v
This is perl 5, version 28, subversion 1 (v5.28.1) built for amd64-freebsd-thread-multi

Thank in advance, I confirm that when I press the button "restore" it shows the error log

**Comment by craigbarratt** [comment]
Either $action is not valid, or the corresponding CGI script isn't available or can't be loaded.

First we should confirm whether the action is valid.  Right before this line:
```
$BackupPC::CGI::{"${action}::"}{action}();
```
add:
```
ErrorExit("CGI request action = $action; path = $installDir; script = BackupPC/CGI/$action.pm") if ( !defined($BackupPC::CGI::{"${action}::"}) );
```
Try the same restore action, and see if you get an error, which should look like this:
```
Error: CGI request action = Restore; path = /usr/local/BackupPC/lib; script = BackupPC/CGI/Restore.pm
```
Also you should confirm the script exists at the indicated path, eg:
```
perl -c -I /usr/local/BackupPC/lib /usr/local/BackupPC/lib/BackupPC/CGI/Restore.pm
```

**Comment by Martintoy** [comment]
Thanks for the reply,
Adding this line, breaks the whole backuppc
`Dir; script = BackupPC/CGI/$action.pm") if ( !defined($BackupPC::CGI::{"${action}::"}) );`

It doesnt show this error,
`IError: CGI request action = Restore; path = /usr/local/BackupPC/lib; script = BackupPC/CGI/Restore.pm`

It shows the following error, so I disabled the added ending line,
```
Software error:
Can't find string terminator '"' anywhere before EOF at /usr/local/www/cgi-bin/BackupPC_Admin line 110.
```

I executed this, but for my installation is not the correct path,
`perl -c -I /usr/local/BackupPC/lib /usr/local/BackupPC/lib/BackupPC/CGI/Restore.pm`

The path installed is
`/usr/local/lib/BackupPC/CGI/Restore.pm`

**Comment by craigbarratt** [comment]
I think you pasted the new line of code incorrectly.  Please review it carefully and try again.

**Comment by Martintoy** [comment]
Im sorry Craig, Im not a developer, what I did is this.
```
require "BackupPC/CGI/$action.pm"
            if ( !defined($BackupPC::CGI::{"${action}::"}) );
            Dir; script ="BackupPC/CGI/$action.pm") if ( !defined($BackupPC::CGI::{"${action}::"}) );
            $BackupPC::CGI::{"${action}::"}{action}();

**Comment by craigbarratt** [comment]
Sorry that is wasn't clear - the line of code I proposed is wider than the text box - you need to scroll it left and right to see all of it.

**Comment by Martintoy** [comment]
Thanks Craig,
This is the ourput,
Error: CGI request action = Restore; path = /usr/local/lib; script = BackupPC/CGI/Restore.pm

Just in case, the lines left like this,
```
#require "BackupPC/CGI/$action.pm"
#           if ( !defined($BackupPC::CGI::{"${action}::"}) );
            ErrorExit("CGI request action = $action; path = $installDir; script = BackupPC/CGI/$action.pm") if ( !defined($BackupPC::CGI::{"${action}::"}) );
            $BackupPC::CGI::{"${action}::"}{action}();
```

**Comment by moisseev** [comment]
@Martintoy Please execute the following command:
```
perl -I /usr/local/lib -c /usr/local/lib/BackupPC/CGI/Restore.pm
```

**Comment by Martintoy** [comment]
This is the output moisseev

# perl -I /usr/local/lib -c /usr/local/lib/BackupPC/CGI/Restore
Can't open perl script "/usr/local/lib/BackupPC/CGI/Restore": No such file or directory
root@VENUS02:/usr/home

**Comment by moisseev** [comment]
You've truncated the line. The module name should be `Restore.pm`, not `Restore`.

**Comment by Martintoy** [comment]
Sorry moisseev, 
was on mobile phone. 
Here is the output
```
perl -I /usr/local/lib -c /usr/local/lib/BackupPC/CGI/Restore.pm
/usr/local/lib/BackupPC/CGI/Restore.pm syntax OK
```

**Comment by craigbarratt** [comment]
Ok, thanks for that.  What happens when you uncomment (ie, remove the "#" characters at the start of the two lines) the two lines:
```
#require "BackupPC/CGI/$action.pm"
#           if ( !defined($BackupPC::CGI::{"${action}::"}) );
```

**Comment by Martintoy** [comment]
When this is enabled
```
require "BackupPC/CGI/$action.pm"
            if ( !defined($BackupPC::CGI::{"${action}::"}) );
               ErrorExit("CGI request action = $action; path = $installDir; script = BackupPC/CGI/$action.pm") if ( !defined($BackupPC::CGI::{"${action}::"}) );
            $BackupPC::CGI::{"${action}::"}{action}()
```
It shows this,
```
Software error:

[Mon Jul  1 19:56:38 2019] Restore.pm: Attempt to reload Errno.pm aborted.
[Mon Jul  1 19:56:38 2019] Restore.pm: Compilation failed in require at /usr/local/lib/BackupPC/Xfer/Rsync.pm line 45.
[Mon Jul  1 19:56:38 2019] Restore.pm: BEGIN failed--compilation aborted at /usr/local/lib/BackupPC/Xfer/Rsync.pm line 45.
[Mon Jul  1 19:56:38 2019] Restore.pm: Compilation failed in require at /usr/local/lib/BackupPC/Xfer.pm line 47.
[Mon Jul  1 19:56:38 2019] Restore.pm: BEGIN failed--compilation aborted at /usr/local/lib/BackupPC/Xfer.pm line 47.
[Mon Jul  1 19:56:38 2019] Restore.pm: Compilation failed in require at /usr/local/lib/BackupPC/CGI/Restore.pm line 40.
[Mon Jul  1 19:56:38 2019] Restore.pm: BEGIN failed--compilation aborted at /usr/local/lib/BackupPC/CGI/Restore.pm line 40.
Compilation failed in require at /usr/local/www/cgi-bin/BackupPC_Admin line 108.
```

**Comment by moisseev** [comment]
@Martintoy  Please execute the following command:
```
perl -e 'use Errno qw(EINTR); print "EINTR has the number ", EINTR, "\n";'
```

**Comment by Martintoy** [comment]
Sure,
```
 perl -e 'use Errno qw(EINTR); print "EINTR has the number ", EINTR, "\n";'
EINTR has the number 4
```

**Comment by Martintoy** [comment]
Guys, please help I cant restore my backups

**Comment by Martintoy** [comment]
To add more lights to the issue, this appears in my httpd-error.log file
[Sat Jul  6 19:05:09 2019] Archive.pm: Scalar value @HostList[0] better written as $HostList[0] at /usr/local/lib/BackupPC/Xfer/Archive.pm line 61.
[Sat Jul  6 19:05:09 2019] Archive.pm: Scalar value @HostList[0] better written as $HostList[0] at /usr/local/lib/BackupPC/Xfer/Archive.pm line 72.
[Sat Jul  6 19:05:09 2019] Archive.pm: Scalar value @BackupList[0] better written as $BackupList[0] at /usr/local/lib/BackupPC/Xfer/Archive.pm line 73.
[Sat Jul  6 19:05:09 2019] Ftp.pm: "my" variable $f masks earlier declaration in same scope at /usr/local/lib/BackupPC/Xfer/Ftp.pm line 1340.
[Sat Jul 06 19:05:09.255602 2019] [:error] [pid 21522] [Sat Jul  6 19:05:09 2019] -e: [Sat Jul  6 19:05:09 2019] Restore.pm: Attempt to reload Errno.pm aborted.\n[Sat Jul  6 19:05:09 2019] -e: [Sat Jul  6 19:05:09 2019] Restore.pm: Compilation failed in require at /usr/local/lib/BackupPC/Xfer/Rsync.pm line 45.\n[Sat Jul  6 19:05:09 2019] -e: [Sat Jul  6 19:05:09 2019] Restore.pm: BEGIN failed--compilation aborted at /usr/local/lib/BackupPC/Xfer/Rsync.pm line 45.\n[Sat Jul  6 19:05:09 2019] -e: [Sat Jul  6 19:05:09 2019] Restore.pm: Compilation failed in require at /usr/local/lib/BackupPC/Xfer.pm line 47.\n[Sat Jul  6 19:05:09 2019] -e: [Sat Jul  6 19:05:09 2019] Restore.pm: BEGIN failed--compilation aborted at /usr/local/lib/BackupPC/Xfer.pm line 47.\n[Sat Jul  6 19:05:09 2019] -e: [Sat Jul  6 19:05:09 2019] Restore.pm: Compilation failed in require at /usr/local/lib/BackupPC/CGI/Restore.pm line 40.\n[Sat Jul  6 19:05:09 2019] -e: [Sat Jul  6 19:05:09 2019] Restore.pm: BEGIN failed--compilation aborted at /usr/local/lib/BackupPC/CGI/Restore.pm line 40.\n[Sat Jul  6 19:05:09 2019] -e: Compilation failed in require at /usr/local/www/cgi-bin/BackupPC_Admin line 108.\n

**Comment by moisseev** [comment]
Sorry, I don't really know how to help you to troubleshoot the issue. It might be broken Perl installation, more than one Perl version installed at the same time, incorrect Perl invocation from web server CGI module or something else. To rule out configuration issues you can try to install BackupPC on a clean test system.

As temporary measure you can try to restore files you need using [command line tools](https://backuppc.github.io/backuppc/BackupPC.html#Command-line-restore-options).
