### ISSUE TITLE
Outdated Cgi Nav Bar Links

### ISSUE THREAD

**Issue by emsquared-inc** [backuppc/backuppc#273]
The sidebar links, "Wiki" and "Sourceforge" are outdated.

See the issue here: <backuppc_home>/index.cgi?action=editConfig

The bottom 2 links on the left-hand column nav, "Wiki" and "SourceForge" are outdated. Wiki points to a nonexistent page and the SourceForge links should be Github.

**Comment by moisseev** [comment]
It has already been fixed two years ago: https://github.com/backuppc/backuppc/commit/9298feb150571216e42a18fe330db1832bdeae41
Apparently you are using an ancient BackupPC version.

**Comment by emsquared-inc** [comment]
Thanks for the reply. I installed from the Debian repo. I'll upgrade...
