### ISSUE TITLE
Web interface fails on ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by hazardlabs** [backuppc/backuppc#276]
Installed version: 3.3.1-4ubuntu1

On a clean system, using:
'sudo apt install backuppc' to install the package I am unable to load the admin webpage. I am presented with a dialog asking to download the page instead.

![image](https://user-images.githubusercontent.com/10254256/60875237-54b8b880-a231-11e9-8255-0cc93449eb67.png)

This was fixed by issuing:

`sudo a2disconf serve-cgi-bin`
`sudo service apache2 restart`

Is this a known issue?

**Comment by SpareSimian** [comment]
I'd say it's a combination of a documentation issue and possibly an Ubuntu packaging issue. 

Apache is an extremely versatile web server and it looks like Ubuntu's default configuration is as a stripped-down static-document-only server, which is the most secure you can get. The Ubuntu package for BackupPC should enable the CGI engine (as you found out). I'd recommend filing a bug against the BackupPC package in the Ubuntu bug tracking system.  Include a link to this Github issue. Post a link to that report in this issue. 

You can also recommend an edit to the documentation wording here to help new users who need to install on Ubuntu-like systems.

**Comment by hazardlabs** [comment]
@SpareSimian , Thank you for getting back to me.

As requested I've raised the issues on lanuchpad, here: https://bugs.launchpad.net/ubuntu/+source/backuppc/+bug/1835929

Depending what the guys on launch pad say, I'll request to update the wiki here if user input is required.
