### ISSUE TITLE
makeDist does not work with dash

### ISSUE THREAD

**Issue by johanehnberg** [backuppc/backuppc#28]
Running makeDist with dash (default in Ubuntu) results in an error:
sh: 1: Syntax error: Bad fd number

As a workaround in Ubuntu, choose 'no' for dash as default shell:
sudo dpkg-reconfigure dash

**Comment by craigbarratt** [comment]
This is fixed in git.  The syntax check system() call used ">&" stderr redirection, which dash doesn't support.
