### ISSUE TITLE
Wrapping/escaping issues with alternative port

### ISSUE THREAD

**Issue by MrMEEE** [backuppc/backuppc#280]
Hi guys

I'm running BackupPC 4.3.1 and I'm having issues getting a backup running on an alternative ssh port (rsync over ssh)..

I feel like I have tried every kind of combination, and there seems to be some kind of wrapping/escaping issue...

If I try to do a configuration like shown in the picture: 
![backuppc](https://user-images.githubusercontent.com/768031/61438634-2f6a2f80-a940-11e9-968f-e00723388e98.png)

I end up with this in the logs:
```
Backup prep: type = full, case = 1, inPlace = 1, doDuplicate = 0, newBkupNum = 0, newBkupIdx = 0, lastBkupNum = , lastBkupIdx =  (FillCycle = 0, noFillCnt = )
Running: /usr/bin/rsync_bpc --bpc-top-dir /var/lib/BackupPC/ --bpc-host-name akiva.outerrim.lan --bpc-share-name /var/lib/pgsql/ --bpc-bkup-num 0 --bpc-bkup-comp 3 --bpc-bkup-prevnum -1 --bpc-bkup-prevcomp -1 --bpc-bkup-inode0 2 --bpc-attrib-new --bpc-log-level 1 --rsync-path=/usr/bin/rsync --super --recursive --protect-args --numeric-ids --perms --owner --group -D --times --links --hard-links --delete --delete-excluded --one-file-system --partial --log-format=log:\ %o\ %i\ %B\ %8U,%8G\ %9l\ %f%L --stats --rsh=\"/usr/bin/ssh\ -l\ root\ -p\ 22150\" --checksum --timeout=72000 akiva.outerrim.lan:/var/lib/pgsql/ /
full backup started for directory /var/lib/pgsql/
Xfer PIDs are now 19923
This is the rsync child about to exec /usr/bin/rsync_bpc
rsync_bpc: Failed to exec /usr/bin/ssh -l root -p 22150: No such file or directory (2)
```

If I manually remove the escaping and rerun on the command line, it works.. but I can't figure out how to get BackupPC to do this.

Thanks for a great project!!

**Comment by adamgoryachev** [comment]
On 18/7/19 17:43, Martin Juhl wrote:
>
> Hi guys
>
> I'm running BackupPC 4.3.1 and I'm having issues getting a backup 
> running on an alternative ssh port (rsync over ssh)..
>
> I feel like I have tried every kind of combination, and there seems to 
> be some kind of wrapping/escaping issue...
>
> If I try to do a configuration like shown in the picture:
> backuppc 
> <https://user-images.githubusercontent.com/768031/61438634-2f6a2f80-a940-11e9-968f-e00723388e98.png>
>
> I end up with this in the logs:
>
> |Backup prep: type = full, case = 1, inPlace = 1, doDuplicate = 0, 
> newBkupNum = 0, newBkupIdx = 0, lastBkupNum = , lastBkupIdx = 
> (FillCycle = 0, noFillCnt = ) Running: /usr/bin/rsync_bpc 
> --bpc-top-dir /var/lib/BackupPC/ --bpc-host-name akiva.outerrim.lan 
> --bpc-share-name /var/lib/pgsql/ --bpc-bkup-num 0 --bpc-bkup-comp 3 
> --bpc-bkup-prevnum -1 --bpc-bkup-prevcomp -1 --bpc-bkup-inode0 2 
> --bpc-attrib-new --bpc-log-level 1 --rsync-path=/usr/bin/rsync --super 
> --recursive --protect-args --numeric-ids --perms --owner --group -D 
> --times --links --hard-links --delete --delete-excluded 
> --one-file-system --partial --log-format=log:\ %o\ %i\ %B\ %8U,%8G\ 
> %9l\ %f%L --stats --rsh=\"/usr/bin/ssh\ -l\ root\ -p\ 22150\" 
> --checksum --timeout=72000 akiva.outerrim.lan:/var/lib/pgsql/ / full 
> backup started for directory /var/lib/pgsql/ Xfer PIDs are now 19923 
> This is the rsync child about to exec /usr/bin/rsync_bpc rsync_bpc: 
> Failed to exec /usr/bin/ssh -l root -p 22150: No such file or 
> directory (2) |
>
> If I manually remove the escaping and rerun on the command line, it 
> works.. but I can't figure out how to get BackupPC to do this.
>

Hi Martin,

This is what I use:

$Conf{RsyncSshArgs} = [
         '-e', '$sshPath -p 222 -l root',
];

Try adding it to the RsyncSSHArgs instead of RsyncArgs.

Regards,
Adam

**Comment by adamgoryachev** [comment]
On 18/7/19 20:30, Martin Juhl wrote:
>
> Hi.. This doesn't work either, rsync just hangs:
>
> |[root@degobah backuppc]# ps aux |grep rsync backuppc 17814 0.0 0.0 
> 137036 2588 ? S 12:23 0:00 /usr/bin/rsync_bpc --bpc-top-dir 
> /var/lib/BackupPC/ --bpc-host-name akiva.outerrim.lan --bpc-share-name 
> /var/lib/pgsql/ --bpc-bkup-num 0 --bpc-bkup-comp 3 --bpc-bkup-prevnum 
> -1 --bpc-bkup-prevcomp -1 --bpc-bkup-inode0 2 --bpc-attrib-new 
> --bpc-log-level 1 -e /usr/bin/ssh -l root -p 22150 
> --rsync-path=/usr/bin/rsync --super --recursive --protect-args 
> --numeric-ids --perms --owner --group -D --times --links --hard-links 
> --delete --delete-excluded --one-file-system --partial 
> --log-format=log: %o %i %B %8U,%8G %9l %f%L --stats --checksum 
> --timeout=72000 akiva.outerrim.lan:/var/lib/pgsql/ / backuppc 17815 
> 0.3 0.1 180992 6972 ? S 12:23 0:00 /usr/bin/ssh -l root -p 22150 
> akiva.outerrim.lan /usr/bin/rsync --server --sender 
> -slHogDtprcxe.iLsfxC backuppc 17817 0.5 0.0 155660 3740 ? S 12:24 0:00 
> /usr/bin/rsync_bpc --bpc-top-dir /var/lib/BackupPC/ --bpc-host-name 
> akiva.outerrim.lan --bpc-share-name /var/lib/pgsql/ --bpc-bkup-num 0 
> --bpc-bkup-comp 3 --bpc-bkup-prevnum -1 --bpc-bkup-prevcomp -1 
> --bpc-bkup-inode0 2 --bpc-attrib-new --bpc-log-level 1 -e /usr/bin/ssh 
> -l root -p 22150 --rsync-path=/usr/bin/rsync --super --recursive 
> --protect-args --numeric-ids --perms --owner --group -D --times 
> --links --hard-links --delete --delete-excluded --one-file-system 
> --partial --log-format=log: %o %i %B %8U,%8G %9l %f%L --stats 
> --checksum --timeout=72000 akiva.outerrim.lan:/var/lib/pgsql/ / root 
> 17891 0.0 0.0 112708 988 pts/1 S+ 12:26 0:00 grep --color=auto rsync |
>
> The problem here is that there is missing ticks around the ssh 
> options.. so they are transferred to the rsync command instead...
>
> if I do:
>
> |/usr/bin/rsync_bpc --bpc-top-dir /var/lib/BackupPC/ --bpc-host-name 
> akiva.outerrim.lan --bpc-share-name /var/lib/pgsql/ --bpc-bkup-num 0 
> --bpc-bkup-comp 3 --bpc-bkup-prevnum -1 --bpc-bkup-prevcomp -1 
> --bpc-bkup-inode0 2 --bpc-attrib-new --bpc-log-level 1 -e 
> '/usr/bin/ssh -l root -p 22150' --rsync-path=/usr/bin/rsync --super 
> --recursive --protect-args --numeric-ids --perms --owner --group -D 
> --times --links --hard-links --delete --delete-excluded 
> --one-file-system --partial --log-format=log: %o %i %B %8U,%8G %9l 
> %f%L --stats --checksum --timeout=72000 
> akiva.outerrim.lan:/var/lib/pgsql/ / |
>
> it works..
>
> but if I but the ' or " inside the configuration, I end up with:
>
> |Backup prep: type = full, case = 1, inPlace = 1, doDuplicate = 0, 
> newBkupNum = 0, newBkupIdx = 0, lastBkupNum = , lastBkupIdx = 
> (FillCycle = 0, noFillCnt = ) Running: /usr/bin/rsync_bpc 
> --bpc-top-dir /var/lib/BackupPC/ --bpc-host-name akiva.outerrim.lan 
> --bpc-share-name /var/lib/pgsql/ --bpc-bkup-num 0 --bpc-bkup-comp 3 
> --bpc-bkup-prevnum -1 --bpc-bkup-prevcomp -1 --bpc-bkup-inode0 2 
> --bpc-attrib-new --bpc-log-level 1 /usr/bin/ssh\ -l\ root\ -p\ 22150 
> --rsync-path=/usr/bin/rsync --super --recursive --protect-args 
> --numeric-ids --perms --owner --group -D --times --links --hard-links 
> --delete --delete-excluded --one-file-system --partial 
> --log-format=log:\ %o\ %i\ %B\ %8U,%8G\ %9l\ %f%L --stats --checksum 
> --timeout=72000 akiva.outerrim.lan:/var/lib/pgsql/ / |


You didn't show the config you used, nor the log files produced. Try 
editing the config file directly without the web interface, and copy 
what I provided, it works for me, so no reason it shouldn't work for you.

Looking at my config from the web interface, I see two options:

RsyncSshArgs  -e

               $sshPath -p 222 -l root

There are no quotes/etc required at all.

Regards,
Adam

**Comment by MrMEEE** [comment]
hmmm.. weird.. I had "$sshPath -l root -p 22150"
If I flip it to: "$sshPath -p 22150 -l root"... it works?

**Comment by MrMEEE** [comment]
Or actually... no it doesn't ... rsync just hangs...

My config is:
```
$Conf{RsyncSshArgs} = [
  '-e',
  '$sshPath -l root -p 22150'
];
$Conf{FullPeriod} = '30';
$Conf{RsyncShareName} = [
  '/var/lib/pgsql/',
  '/home/awx-build/',
  '/opt/gogs/',
  '/etc/'
];
$Conf{RsyncArgs} = [
  '--super',
  '--recursive',
  '--protect-args',
  '--numeric-ids',
  '--perms',
  '--owner',
  '--group',
  '-D',
  '--times',
  '--links',
  '--hard-links',
  '--delete',
  '--delete-excluded',
  '--one-file-system',
  '--partial',
  '--log-format=log: %o %i %B %8U,%8G %9l %f%L',
  '--stats'
];
$Conf{RsyncRestoreArgs} = [
  '--recursive',
  '--super',
  '--protect-args',
  '--numeric-ids',
  '--perms',
  '--owner',
  '--group',
  '-D',
  '--times',
  '--links',
  '--hard-links',
  '--delete',
  '--partial',
  '--log-format=log: %o %i %B %8U,%8G %9l %f%L',
  '--stats'
];
$Conf{XferLogLevel} = '1';
```
Not errors in the log, just stops at: 
```
2019-07-18 13:47:47 Renaming /var/lib/BackupPC//pc/akiva.outerrim.lan/XferLOG.0.z -> /var/lib/BackupPC//pc/akiva.outerrim.lan/XferLOG.0.z.tmp
2019-07-18 13:47:47 full backup started for directory /var/lib/pgsql/
```
If I run the rsync manually:
```
-bash-4.2$ /usr/bin/rsync_bpc --bpc-top-dir /var/lib/BackupPC/ --bpc-host-name akiva.outerrim.lan --bpc-share-name /var/lib/pgsql/ --bpc-bkup-num 0 --bpc-bkup-comp 3 --bpc-bkup-prevnum -1 --bpc-bkup-prevcomp -1 --bpc-bkup-inode0 2 --bpc-attrib-new --bpc-log-level 1 /usr/bin/ssh\ -l\ root\ -p\ 22150 --rsync-path=/usr/bin/rsync --super --recursive --protect-args --numeric-ids --perms --owner --group -D --times --links --hard-links --delete --delete-excluded --one-file-system --partial --log-format=log:\ %o\ %i\ %B\ %8U,%8G\ %9l\ %f%L --stats --checksum --timeout=72000 akiva.outerrim.lan:/var/lib/pgsql/ /
Unexpected remote arg: akiva.outerrim.lan:/var/lib/pgsql/
Done: 0 errors, 0 filesExist, 0 sizeExist, 0 sizeExistComp, 0 filesTotal, 0 sizeTotal, 0 filesNew, 0 sizeNew, 0 sizeNewComp, 2 inode
rsync error: syntax or usage error (code 1) at main.c(1348) [sender=3.1.2.0]
```
If I add quotes and remove escapes:
```
-bash-4.2$ /usr/bin/rsync_bpc --bpc-top-dir /var/lib/BackupPC/ --bpc-host-name akiva.outerrim.lan --bpc-share-name /var/lib/pgsql/ --bpc-bkup-num 0 --bpc-bkup-comp 3 --bpc-bkup-prevnum -1 --bpc-bkup-prevcomp -1 --bpc-bkup-inode0 2 --bpc-attrib-new --bpc-log-level 1 -e '/usr/bin/ssh -l root -p 22150' --rsync-path=/usr/bin/rsync --super --recursive --protect-args --numeric-ids --perms --owner --group -D --times --links --hard-links --delete --delete-excluded --one-file-system --partial --log-format=log:\ %o\ %i\ %B\ %8U,%8G\ %9l\ %f%L --stats --checksum --timeout=72000 akiva.outerrim.lan:/var/lib/pgsql/ /
xferPids 20091,20093
__bpc_progress_fileCnt__ 1
__bpc_progress_fileCnt__ 21
__bpc_progress_fileCnt__ 41
__bpc_progress_fileCnt__ 61
__bpc_progress_fileCnt__ 81
__bpc_progress_fileCnt__ 101
__bpc_progress_fileCnt__ 121
__bpc_progress_fileCnt__ 141
__bpc_progress_fileCnt__ 161
__bpc_progress_fileCnt__ 181
__bpc_progress_fileCnt__ 201
__bpc_progress_fileCnt__ 221
__bpc_progress_fileCnt__ 241
__bpc_progress_fileCnt__ 261
__bpc_progress_fileCnt__ 281

```

**Comment by MrMEEE** [comment]
@adamgoryachev What version of BackupPC are you running? how does your rsync line look?

**Comment by MrMEEE** [comment]
hmmm.. Actually it connects to the remote server.. and starts up an rsync process..
```
/usr/bin/rsync --server --sender -slHogDtprcxe.iLsfxC
```

But then nothing more seems to happen??

**Comment by MrMEEE** [comment]
Forget it.. I figured it out.. thanks for the help
