### ISSUE TITLE
Document WakeupSchedule clock

### ISSUE THREAD

**Issue by tedtoal** [backuppc/backuppc#288]
Git issues are meant for development-related topics, such as bug reports and feature requests.

For user questions / support, please go to the user mail list: http://lists.sourceforge.net/lists/listinfo/backuppc-users

(Please delete this text and enter your bug report, feature request etc.  Please include version numbers, config settings, relevant LOG snippets etc.)

**Comment by tedtoal** [comment]
The documentation for the WakeupSchedule config parameter should indicate whether the values are in hours after midnight UNIVERSAL TIME or LOCAL TIME.

**Comment by craigbarratt** [comment]
It's localtime.  I've added a comment to that effect.
