### ISSUE TITLE
Bug in V3 diggest calculation in MigrateV3toV4

### ISSUE THREAD

**Issue by palmtop** [backuppc/backuppc#291]
In line 395 of migrate V3toV4 there is the following code the calculate the V3 diggest:

`my $digest3 = $bpc->Buffer2MD5_v3(Digest::MD5->new(), $fileSize, \$data1MB);`

But at this point $data1MB is undefined, so it seems, like a random hash is calculated, which usually  doesn't match, and therefore the files are all copied.

With this small correction, marked by ###, this can be corrected in lines 381 to 392:

	do {
	    $thisRead = $f->read(\$data, 1 << 20);
	    if ( $thisRead < 0 ) {
		print("BackupPC_migrateV3toV4: error reading file $fullPath (read returns $thisRead)\n");
		$ErrorCnt++;
		$f->close();
		next;
	    } elsif ( $thisRead > 0 ) {
		$md5->add($data);
		$fileSize += length($data);
        ###$data1MB=$data if ($fileSize<= (1<<20));###
	    }
	} while ( $thisRead > 0 );

I tested this with a sample 10 Gigabyte V3 backup and it speeded up migration from 4 M 12 Sec to  52 seconds.

I saw the same problem in backupDuplicate.

**Comment by craigbarratt** [comment]
Thanks for finding this bug in both scripts.  Here's the fix I added (not yet committed):
```
$data1MB .= $data if ( length($data1MB) < (1 << 20) );
```

**Comment by craigbarratt** [comment]
I pushed this change d4afde0.
