### ISSUE TITLE
Sudo: Sorry, you must have a terminal to execute sudo.

### ISSUE THREAD

**Issue by qweadd** [backuppc/backuppc#293]
XferLOG file /data/backuppc/pc/192.168.0.152/XferLOG.0.z created 2019-09-26 15:49:54 
Backup prep: type = full, case = 1, inPlace = 1, doDuplicate = 0, newBkupNum = 0, newBkupIdx = 0, lastBkupNum = , lastBkupIdx =  (FillCycle = 0, noFillCnt = )
Running: /usr/local/bin/rsync_bpc --bpc-top-dir /data/backuppc --bpc-host-name 192.168.0.152 --bpc-share-name /etc --bpc-bkup-num 0 --bpc-bkup-comp 3 --bpc-bkup-prevnum -1 --bpc-bkup-prevcomp -1 --bpc-bkup-inode0 2 --bpc-attrib-new --bpc-log-level 1 -e /usr/bin/ssh\ -q\ -x\ -p\ 10022\ -i\ /home/backuppc/.ssh/zwzxops.key\ -l\ zwzxops --rsync-path=sudo\ /usr/bin/rsync --super --recursive --protect-args --numeric-ids --perms --owner --group -D --times --links --hard-links --delete --delete-excluded --one-file-system --partial --log-format=log:\ %o\ %i\ %B\ %8U,%8G\ %9l\ %f%L --stats --checksum --timeout=72000 192.168.0.152:/etc/ /
**_full backup started for directory /etc
Xfer PIDs are now 56745
This is the rsync child about to exec /usr/local/bin/rsync_bpc
Sudo: Sorry, you must have a terminal to execute sudo._**
rsync_bpc: connection unexpectedly closed (0 bytes received so far) [Receiver]
Done: 0 errors, 0 filesExist, 0 sizeExist, 0 sizeExistComp, 0 filesTotal, 0 sizeTotal, 0 filesNew, 0 sizeNew, 0 sizeNewComp, 2 inode
rsync error: error in rsync protocol data stream (code 12) at io.c(629) [Receiver=3.0.9.12]
rsync_bpc exited with fatal status 12 (3072) (rsync error: error in rsync protocol data stream (code 12) at io.c(629) [Receiver=3.0.9.12])
Xfer PIDs are now 
Got fatal error during xfer (No files dumped for share /etc)
Backup aborted (No files dumped for share /etc)
BackupFailCleanup: nFilesTotal = 0, type = full, BackupCase = 1, inPlace = 1, lastBkupNum = 
Removing empty backup #0
Xfer PIDs are now 56752
BackupPC_backupDelete: removing #0
BackupPC_backupDelete: No prior backup for merge
Xfer PIDs are now 56752,56753
BackupPC_refCountUpdate: host 192.168.0.152 got 0 errors (took 0 secs)
Xfer PIDs are now 56752
Xfer PIDs are now 
Finished BackupPC_backupDelete, status = 0 (running time: 1 sec)
Xfer PIDs are now 
Running BackupPC_refCountUpdate -h 192.168.0.152 -f on 192.168.0.152
Xfer PIDs are now 56754
BackupPC_refCountUpdate: host 192.168.0.152 got 0 errors (took 0 secs)
Xfer PIDs are now 
Finished BackupPC_refCountUpdate (running time: 0 sec)
Xfer PIDs are now

**Comment by craigbarratt** [comment]
Have you googled that error message to see what the likely causes might be?

**Comment by qweadd** [comment]
Thank you. The problem has been solved.
