### ISSUE TITLE
Issues with the install script for Ubuntu

### ISSUE THREAD

**Issue by denellum** [backuppc/backuppc#298]
Good Morning, 
I am trying to install backuppc on ubuntu 18.04, but was getting an error on line 11 : 
https://github.com/backuppc/backuppc/wiki/Installing-BackupPC-4-from-tarball-or-git-on-Ubuntu

I replaced line 10 & 11 with the following and everything worked as intended : 
`read -p 'Give password or leave empty to generate one: ' PASSWORD`

Thank you!
denellum

**Comment by craigbarratt** [comment]
I don't have 18.04 available to test, but the existing commands do work on 16.04.
