### ISSUE TITLE
problem with tar restore (webinterface and commandline)

### ISSUE THREAD

**Issue by hamster65** [backuppc/backuppc#299]
Hi, 
I had to restore all my data after an Windows 10 upgrade corrupted my ext4 partition. I ran into the following issues during restore:

1) Restores to tar file from the web interface returned incomplete or empty archives / zero bytes tar files.  

2) Restore commands to tar file from the commandline terminated with an error, stating that the backup number was invalid.

I figured out that BackupPC was trying to start new backups for the host. That made the number of the backup which I was trying to restore invalid because it changed. Is this an error or by design? It should not happen while a restore is running  or while the user is selecting files to be restored from the webinterface.

I paused backups for the next 5 hours and after that I was able to restore all my data to tar files from commandline.

3) Restores to tar files from the web interface did not return zero byte archives now that I stopped backups. But I still got only incomplete archives. Maybe there is a size or time limitation for downloading files?

**Comment by craigbarratt** [comment]
Thanks for reporting this.  Yes, your explanation sounds correct.  I need to figure out how to fix this.  I'm not sure about (3) - that is probably unrelated.

**Comment by craigbarratt** [comment]
I've pushed code (6996d6b) that makes all the worker programs read/write exclusive.  For each host, you can have multiple readers running (eg, BackupPC_tarCreate, BackupPC_zipCreate, BackupPC_restore, BackupPS_archive), or at most one writer (eg, BackupPC_dump, BackupPC_backupDelete, BackupPC_backupDuplicate).  You can use the -m command-line option to force a program to run, even if it violates the read/write exclusivity (user beware).

**Comment by fauust** [comment]
Hi @craigbarratt!
So I understand the reason of 6996d6b, and I believe it is necessary.
But then what would you recommend to be able to use `BackupPC_tarCreate` on `DumpPostUserCmd`?
Should I force with `-m` ?

Explanation, I have coupled BackupPC with ![restic](https://github.com/restic/restic) and I am exporting the last backup off-site with a bash script (called by `DumpPostUserCmd`) that do something like:
```bash
/usr/local/BackupPC/bin/BackupPC_tarCreate -h host -n -1 -s '*' / /usr/local/bin/restic backup --tag host --stdin --stdin-filename host.tar
```
Of course, now I get:
> Can't run BackupPC_tarCreate while BackupPC_dump is running on host

This is clearly not a pb to add the `-m` option but maybe there is a better way?
Thanks!

**Comment by ftrojahn** [comment]
> Of course, now I get:
> 
> > Can't run BackupPC_tarCreate while BackupPC_dump is running on host
> 
> This is clearly not a pb to add the `-m` option but maybe there is a better way?
> Thanks!

May be just start the tarCreate using `at` 10 min later, or put the command in an `tsp` queue? So, `DumpPostUserCmd` and the whole job would be finished before tarCreate starts.

**Comment by fauust** [comment]
Hi @ftrojahn!
Good suggestion, but I believe that the `DumpPostUserCmd` is forked from `BackupPC_dump` so waiting for some time will not resolve this?

Anyway, using `-m` option is ok for the moment and as It's for personal use, there should not be concurrent dumps in my case.
