### ISSUE TITLE
backuppc does not delete files

### ISSUE THREAD

**Issue by tom-x1** [backuppc/backuppc#301]
We are using backuppc 4.2.1 on debian 9

We are facing a quite similar problem like in #135 

The thing is, since the beginning we are using rsync and never used other methods and doing a full dump like mentioned in the issue above does not solve the problem. So backuppc seems to never delete files. I have attached a screenshot of a testdirectory... You see 5 backups for the foo* files:

![2019-11-28_162211](https://user-images.githubusercontent.com/28628667/69817725-8b509900-11fb-11ea-9314-210ad9df3236.png)

204-207 are inc backups, 208 is a full backup. The changes were:

204 > created foo1
205 > created foo2, deleted foo1
206 > created foo3, deleted foo2
207 > created foo4, deleted foo3
208 > Full Backup with no changes

208 contains every foo* file while there should be only foo4. 
207 contains every foo* file
206 contains foo3-1
205 contains foo2-1
204 contains foo1

As we can see at our database dumps, those files are even not deleted if the last backup "in chain" got deleted by backuppc. I've sent a this issue to the mailinglist: https://sourceforge.net/p/backuppc/mailman/message/36863219/

**Comment by ftrojahn** [comment]
Same versions and same problem here. Recently we noticed that our gitlab backup dir was included in the BackupPC rsync backup. All versions of `nnn_201x_mm_dd_a.b.c_gitlab_backup.tar` until december 20, 2018 are there - while our latest backups of the host are 2019-09-11 (inc) vs 2019-09-15 (full), and the contents of the original directory is like this:

```
ls -l /srv/gitlab/data/backups/
insgesamt 9727216
-rw------- 1 gitlab gitlab 9960663040 Dez  8 23:51 dump_gitlab_backup.tar
```
since we have changed this gitlab backup setting.

We have:

```
$Conf{FullKeepCntMin} = 1;
$Conf{FullAgeMax} = 90;
$Conf{IncrKeepCnt} = 90;
$Conf{IncrKeepCntMin} = 1;
$Conf{IncrAgeMax} = 90;
```
(if you need more info, please tell).

Our v3 BackupPC server doesn't show this problem (it runs on another server)
![Bildschirmfoto von 2019-12-09 12-25-21](https://user-images.githubusercontent.com/6184818/70432297-36c0df80-1a7f-11ea-8b5c-5cf98697727a.png)

but history of the v4 BackupPC for this same directory looks like this:
![Bildschirmfoto von 2019-12-09 12-28-41](https://user-images.githubusercontent.com/6184818/70432414-81425c00-1a7f-11ea-8a11-43c2b5a222fa.png)

**Comment by tom-x1** [comment]
@ftrojahn 
Your V4 history shows exactly the same problem like ours - our database dumps were also not deleted:
![3](https://user-images.githubusercontent.com/28628667/70432987-cf0b9400-1a80-11ea-8390-0c997dc42859.png)

I've checked with the backuppc scripts stored at /usr/share/backuppc/bin/ which backups reference those old files. And it looks like BackupPC thinks that EVERY Full Dump is referencing those old files which is definetely not the case. I've used this guide: https://github.com/backuppc/backuppc/wiki/How-to-find-which-backups-reference-a-particular-pool-file

**Comment by tom-x1** [comment]
Meanwhile we upgraded to the most recent version (4.3.1) unfortunately without any changes regarding this behaviour.

**Comment by craigbarratt** [comment]
rsync skips the deletion of files if there are any transfer errors.

Try adding the --ignore-errors option to $Conf{RsyncArgs}.

**Comment by ftrojahn** [comment]
Added it, didn't change something - all files remained in the /srv/gitlab/data/backup dir, while on the real server ther is only one. Does it make a difference, if it is an incremental or full backup run?

**Comment by tom-x1** [comment]
Unfortunately also no change here. Makes no difference if Full or Inc...

**Comment by craigbarratt** [comment]
Can you tell me
- the version of rsync-bpc you are running
- the full rsync cmd line (from the XferLOG file)

**Comment by tom-x1** [comment]
Sorry for the late response... we are running:

```
ii  backuppc                          4.3.1                             amd64        high-performance, enterprise-grade system for backing up PCs
ii  backuppc-dbgsym                   4.3.1                             amd64        Debug symbols for backuppc
ii  libbackuppc-xs-perl:amd64         0.59-1                            amd64        Perl module with C backend for BackupPC 4
ii  libbackuppc-xs-perl-dbgsym:amd64  0.59-1                            amd64        Debug symbols for libbackuppc-xs-perl
ii  rsync-bpc                         3.0.9.14                          amd64        high-performance, enterprise-grade system for backing up PCs
```

**Comment by tom-x1** [comment]
This is the Xfer log from the latest (incremental) backup:

```
XferLOG file /backup/backuppc//pc/host.example.com/XferLOG.211.z created 2020-01-02 01:37:53
Backup prep: type = incr, case = 4, inPlace = 0, doDuplicate = 0, newBkupNum = 211, newBkupIdx = 17, lastBkupNum = 210, lastBkupIdx = 16 (FillCycle = 0, noFillCnt = 4)
Running: /usr/bin/rsync_bpc --bpc-top-dir /backup/backuppc/ --bpc-host-name host.example.com --bpc-share-name / --bpc-bkup-num 211 --bpc-bkup-comp 3 --bpc-bkup-prevnum 210 --bpc-bkup-prevcomp 3 --bpc-bkup-inode0 116393 --bpc-attrib-new --bpc-log-level 1 -e /usr/bin/ssh\ -l\ backuppc\ -o\ StrictHostKeyChecking=no --rsync-path=sudo\ /usr/bin/rsync --numeric-ids --perms --owner --group -D --links --hard-links --times --block-size=2048 --recursive --checksum-seed=32761 --ignore-errors --timeout=72000 --exclude=/backups/ --exclude=/dev --exclude=/home/services --exclude=/pgdata --exclude=/proc --exclude=/proxmox_zfs --exclude=/sys --exclude=/tmp --exclude=/usr/games --exclude=/usr/include --exclude=/usr/lib --exclude=/usr/src --exclude=/var/cache --exclude=/var/lib/mysql --exclude=/var/lib/postgresql --exclude=/var/mirror --exclude=/var/ossec --exclude=/var/spool --exclude=/var/tmp host.example.com:/ /
incr backup started for directory /
Xfer PIDs are now 19888
This is the rsync child about to exec /usr/bin/rsync_bpc
Xfer PIDs are now 19888,19890
xferPids 19888,19890
Done: 0 errors, 49 filesExist, 6738477 sizeExist, 1712231 sizeExistComp, 0 filesTotal, 0 sizeTotal, 43 filesNew, 31381679979 sizeNew, 31150301762 sizeNewComp, 116395 inode
DoneGen: 0 errors, 0 filesExist, 0 sizeExist, 0 sizeExistComp, 40629 filesTotal, 73872203654 sizeTotal, 0 filesNew, 0 sizeNew, 0 sizeNewComp, 116414 inode
Xfer PIDs are now
Removing unfilled backup 203
Xfer PIDs are now 8466
BackupPC_backupDelete: removing #203
BackupPC_backupDelete: No prior backup for merge
Xfer PIDs are now 8467,8466
BackupPC_refCountUpdate: host host.example.com got 0 errors (took 9 secs)
Xfer PIDs are now 8466
Xfer PIDs are now
Finished BackupPC_backupDelete, status = 0 (running time: 10 sec)
Xfer PIDs are now
Running BackupPC_refCountUpdate -h host.example.com on host.example.com
Xfer PIDs are now 8470
BackupPC_refCountUpdate: host host.example.com got 0 errors (took 1 secs)
Xfer PIDs are now
Finished BackupPC_refCountUpdate (running time: 1 sec)
Xfer PIDs are now

```

**Comment by craigbarratt** [comment]
Sorry about the delay in replying.  I've been traveling for the last few weeks, but I'm back now.  I'd definitely like to solve this issue.

Thanks for the log files.  The first thing I noticed is your rsync command doesn't have the "--delete" option.  That is what tells rsync to delete files that are no longer present.  Here's the default setting for $Conf{RsyncArgs}:
```
$Conf{RsyncArgs} = [
            '--super',
            '--recursive',
            '--protect-args',
            '--numeric-ids',
            '--perms',
            '--owner',
            '--group',
            '-D',
            '--times',
            '--links',
            '--hard-links',
            '--delete',
            '--delete-excluded',
            '--one-file-system',
            '--partial',
            '--log-format=log: %o %i %B %8U,%8G %9l %f%L',
            '--stats',
            #
            # Add additional arguments here, for example --acls or --xattrs
            # if all the clients support them.
            #
            #'--acls',
            #'--xattrs',
];
```

**Comment by tom-x1** [comment]
Ok, thats awkward. This really seems to be the issue. I don't have a clue, how those default settings have changed- I'm really sorry! 

Anyway, this is now the new history of the directory which I have also postet in my initial post. Now all those old backups were dropped from the current backup:


![Screenshot_2020-01-15 BackupPC Directory](https://user-images.githubusercontent.com/28628667/72414394-63e56980-3772-11ea-91a5-15c8d023af35.png)

**Comment by ftrojahn** [comment]
> .... I don't have a clue, how those default settings have changed- I'm really sorry!
> 
I know, where these settings came from: we did use the old settings from backuppc v3, on some hosts we've added --checksumseed=... So, the RsyncArgs setting was written into some host's config file and preserved when using backuppc v4.

**Comment by craigbarratt** [comment]
In a v3 -> v4 upgrade, any per-host config settings (that override the main config settings) aren't updated during the upgrade process.  I need to make that clearer in the documentation or print some visible warnings during the upgrade...

**Comment by tortureduck** [comment]
I had the same problem with the RsyncArgs setting, there was no -- delete option for some reason.
