### ISSUE TITLE
bad poolRangeStart

### ISSUE THREAD

**Issue by guestisp** [backuppc/backuppc#304]
v4.3.1

```
2019-12-26 22:44:19 Running BackupPC_nightly -m -P 10 864 867 (pid=20264)
2019-12-26 22:44:19  admin : /usr/local/backuppc/bin/BackupPC_nightly:
bad poolRangeStart '864'
2019-12-26 22:44:19 Finished  admin  (BackupPC_nightly -m -P 10 864 867)
```

**Comment by craigbarratt** [comment]
What are you settings for
```
$Conf{MaxBackupPCNightlyJobs}
$Conf{BackupPCNightlyPeriod}
$Conf{PoolSizeNightlyUpdatePeriod}
```
I can see a case where the range will exceed the valid range if you reduce `$Conf{BackupPCNightlyPeriod}` from a higher value to a lower value (after running with the higher value for some time).  I'll add some error checking to fix that case, and to also make sure that `$Conf{BackupPCNightlyPeriod}` has one of the valid values 1, 2, 4, 8, 16.

I checked in a fix 3d17bcc for that case.

**Comment by guestisp** [comment]
```
$Conf{MaxBackupPCNightlyJobs} = 2;
$Conf{BackupPCNightlyPeriod} = 32;
$Conf{PoolSizeNightlyUpdatePeriod} = 128;
```

> I can see a case where the range will exceed the valid range if you reduce 
> $Conf{BackupPCNightlyPeriod} from a higher value to a lower value 
> (after running with the higher value for some time). 

It could be, as i'm chaning some settings trying to lower the I/O caused by the nighly job

> make sure that $Conf{BackupPCNightlyPeriod} has one of the valid values 1, 2, 4, 8, 16

Valid values are only 1,2,4,8,16 ? I've read on the mailing list that it was just an example, so I've set to 32 (is still a power of two)

**Comment by craigbarratt** [comment]
Yes, valid values are 1,2,4,8,16 and the code change I pushed now enforces that.
