### ISSUE TITLE
Remove hardlink test

### ISSUE THREAD

**Issue by johanehnberg** [backuppc/backuppc#31]
Since v4 no longer uses hard links, the hard link test can be removed (or run only when $Conf{PoolV3Enabled} is set) from the daemon code.

**Comment by johanehnberg** [comment]
I have successfully tested disabling the hard link check. When running the pc directory off an SSD (as opposed to on the same HDD as cpool) I am seeing speedups in the 2x-10x range for backup times. 

Furthermore, this makes it very smooth to use SDD for pc + SMR HDD for cpool where it previously would choke completely, causing process blocked warnings etc. due to SMR garbage collection after lots of small random writes.

In the bigger picture, I see this development as a big step towards making it possible to use object storage with BackupPC. Perhaps it would already work with a mounted object storage FS.

**Comment by johanehnberg** [comment]
A further consideration is that there may be two or more file systems to measure to avoid a disk full situation.

**Comment by johanehnberg** [comment]
Also, the pool count files keep changing in cpool. From the point of moving to object storage, it may be more useful to have them in a directory of their own. I will have a closer look at how the files behave and file a separate bug if needed.

**Comment by craigbarratt** [comment]
I haven't removed the hardlink test, but rather made it conditional upon $Conf{PoolV3Enabled}:

    if ( $Conf{PoolV3Enabled} && !$bpc->HardlinkTest("$TopDir/pc", "$TopDir/cpool") ) {
