### ISSUE TITLE
can not backup some directories（eg：lib，lib64，usr，var，sys with the directory / ）

### ISSUE THREAD

**Issue by rocky91-shi** [backuppc/backuppc#320]
Hello,this is the situation:
Server: centos7.6(x86_64)，backuppc 3.3.1-5
client: centos7.4(x86_64)
Xfer type: rsync
RsyncShareName: /
Exclusion paths: no
RsyncClientPath: /usr/bin/rsync
RsyncClientCmd: $sshPath -q -x -l root $host $rsyncPath $argList+

problem:
when i start to backup the directory /，the directories (lib、lib64、usr、var、sys) can not be backuped. and i can not find some error messages.

Has anyone been in this situation?
Thanks in advance!

**Comment by moisseev** [comment]
Probably it is a `--one-file-system` [1] issue if these directories are located on a different file system than `/`.
You need to remove  `--one-file-system` from `$Conf{RsyncArgs}`. Don't forget to exclude directories you don't want to be backuped, e.g. `/proc`.

1. rsync option: `-x, --one-file-system       don't cross filesystem boundaries`

**Comment by rocky91-shi** [comment]
Thank you for your advice，i will try in your way，and i will tell you the result。
bye the way，when i backup the directory / of rhel6.x(i686)，it has no problems above!

**Comment by rocky91-shi** [comment]
> 
> 
> Probably it is a `--one-file-system` [1] issue if these directories are located on a different file system than `/`.
> You need to remove `--one-file-system` from `$Conf{RsyncArgs}`. Don't forget to exclude directories you don't want to be backuped, e.g. `/proc`.
> 
>     1. rsync option: `-x, --one-file-system       don't cross filesystem boundaries`

Thank you for your advice，i will try in your way，and i will tell you the result。
bye the way，when i backup the directory / of rhel6.x(i686)，it has no problems above!

**Comment by rocky91-shi** [comment]
> 
> 
> Probably it is a `--one-file-system` [1] issue if these directories are located on a different file system than `/`.
> You need to remove `--one-file-system` from `$Conf{RsyncArgs}`. Don't forget to exclude directories you don't want to be backuped, e.g. `/proc`.
> 
>     1. rsync option: `-x, --one-file-system       don't cross filesystem boundaries`

hi，my config.pl configuration has no --one-file-system , as shown below:

#
$Conf{RsyncArgs} = [
  '--numeric-ids',
  '--perms',
  '--owner',
  '--group',
  '-D',
  '--links',
  '--hard-links',
  '--times',
  '--block-size=2048',
  '--recursive'
];

**Comment by craigbarratt** [comment]
It would be better to address this on the user list.  Git issues are for bugs and features.

Could you send the full rsync command that is being run (look in the XferLOG file)?

**Comment by rocky91-shi** [comment]
> 
> 
> It would be better to address this on the user list. Git issues are for bugs and features.
> 
> Could you send the full rsync command that is being run (look in the XferLOG file)?

This is the full rsync command，as shown below:
/usr/bin/ssh -q -l root x.x.x.x rsync --server --sender --numeric-ids --perms --owner --group -D --links   --times  --block-size=2048 --recursive

/usr/bin/perl /usr/share/BackupPC/bin/BackupPC_dump -f X.X.X.X

**Comment by rocky91-shi** [comment]
> 
> 
> > Probably it is a `--one-file-system` [1] issue if these directories are located on a different file system than `/`.
> > You need to remove `--one-file-system` from `$Conf{RsyncArgs}`. Don't forget to exclude directories you don't want to be backuped, e.g. `/proc`.
> > ```
> > 1. rsync option: `-x, --one-file-system       don't cross filesystem boundaries`
> > ```
> 
> Thank you for your advice，i will try in your way，and i will tell you the result。
> bye the way，when i backup the directory / of rhel6.x(i686)，it has no problems above!

**Comment by rocky91-shi** [comment]
> 
> 
> Probably it is a `--one-file-system` [1] issue if these directories are located on a different file system than `/`.
> You need to remove `--one-file-system` from `$Conf{RsyncArgs}`. Don't forget to exclude directories you don't want to be backuped, e.g. `/proc`.
> 
>     1. rsync option: `-x, --one-file-system       don't cross filesystem boundaries`
Yesterday ,I found a problem below:
my $Conf{RsyncArgs} has no --one-file-system option，After i add the --one-file-system to $Conf{RsyncArgs} and restart backuppc service，the directory(/usr，/var，/sys) could be backuped，but /sys  directory is empty。

**Comment by moisseev** [comment]
You shouldn't backup the `/sys` directory as it is virtual and is rebuilt upon each boot.

I guess it didn't work without `--one-file-system` because special directories like /dev, /proc, /sys were not excluded from backup. You should have get errors in the log. Now these directories are explicitly excluded since they are not on the root file system.

**Comment by rocky91-shi** [comment]
> 
> 
> > Probably it is a `--one-file-system` [1] issue if these directories are located on a different file system than `/`.
> > You need to remove `--one-file-system` from `$Conf{RsyncArgs}`. Don't forget to exclude directories you don't want to be backuped, e.g. `/proc`.
> > ```
> > 1. rsync option: `-x, --one-file-system       don't cross filesystem boundaries`
> > ```
> 
> hi，my config.pl configuration has no --one-file-system , as shown below:
> 
> $Conf{RsyncArgs} = [
> '--numeric-ids',
> '--perms',
> '--owner',
> '--group',
> '-D',
> '--links',
> '--hard-links',
> '--times',
> '--block-size=2048',
> '--recursive'
> ];

**Comment by rocky91-shi** [comment]
> 
> 
> You shouldn't backup the `/sys` directory as it is virtual and is rebuilt upon each boot.
> 
> I guess it didn't work without `--one-file-system` because special directories like /dev, /proc, /sys were not excluded from backup. You should have get errors in the log. Now these directories are explicitly excluded since they are not on the root file system.

ok，I will think about it，Thank you!
