### ISSUE TITLE
BlackoutPeriods ignored?

### ISSUE THREAD

**Issue by guestisp** [backuppc/backuppc#321]
v4.3.1

`BlackoutPeriods` seems to be ignored, at least on Monday.
This is what I have:

```
$Conf{BlackoutPeriods} = [
   {
      hourBegin => 21.5,
      hourEnd   =>  8.0,
      weekDays  => [1, 2, 3, 4, 5],
   },
   {
      hourBegin => 0,
      hourEnd   => 23.9,
      weekDays  => [6,0],
   },
];
```

everything is working fine, backups are not run starting from 21:30 till 8:00 of the next day, every day except monday. Currently I have 8 hours backups (one each hour starting from midnight)

Maybe there is something non working properly if the previous day was under a total blackout ? In my case, on sunday I don't run any backups, so I think there is something wrong when calculating the blackout spawing multiple days (like 21:00 till 08:00)

**Comment by craigbarratt** [comment]
When hourEnd < hourBegin, the blackout interval is [hourBegin, midnight] on the current day, and [midnight, hourEnd] on the next day (not the next day according to the weekDays setting).  So the first blackout specification has a blackout on Saturday midnight to 8am.  There won't be a blackout on Monday morning.  Is that what you see?  If so, it is working as intended, although it's confusing.  You could get your intended behavior by adding one more spec for midnight to 8am on Monday morning.
