### ISSUE TITLE
V3 to V4 migration - cpool not empty

### ISSUE THREAD

**Issue by thalueng** [backuppc/backuppc#324]
BackupPC V4.3.2

**Starting point**
hdd with 2.7TB backuppc data folder, created with BackupPC V3 (Debian 7)
installed BackupPC V4.3.2 on new machine running Debian 10 LXDE
mounted backuppc data folder
ran "BackupPC_migrateV3toV4"
ran "BackupPC_nightly 0 255"

**Result**
backuppc cpool not empty
Checking on hard linked files I found they all resided in folder pc/apollo/new, total size 483GB, with 650 entries in file pc/apollo/NewFileList (apollo is my client's name)
removed contents of folder pc/apollo/new and re-ran "BackupPC_nightly 0 255", which emptied the V3 pool

I assume "new" was created during a backup, but apparently the backup task did not complete, and folder new was not renamed into a valid backup folder

**Comment by craigbarratt** [comment]
Thanks for figuring this out. Yes, BackupPC_migrateV3toV4 should remove host/new and host/NewFileList.  I'll add that to my todo list.

**Comment by madduck** [comment]
FYI, I just completed the migration of a server backing up just a single host, and `cpool` is similarly not empty after a complete run, followed by nightly. It has shrunk *a lot*, but there are still thousands of files in the old hashing hierarchy:

![image](https://user-images.githubusercontent.com/195073/202847343-dbdf1409-dfc4-4bc5-a6d5-60b9d1be6fbe.png)

**Comment by kwisatz** [comment]
I'm seeing the same thing as @madduck. I have about 84Mb left in v3 CPool after a migrate and nightly. 
However, I still do have single digit directories:

```
root@naraj:/var/lib/backuppc# find cpool/? -type f
cpool/4/0/1/401321cf900654f7b8098b523a34d144_0
cpool/4/9/c/49c9d3af39b3e6a9b7ed18f0abe84cce_0
cpool/6/7/c/67ca87f6064ee6e528104617e40d8e75_1
cpool/6/7/c/67ca87f6064ee6e528104617e40d8e75_2
cpool/6/7/c/67ca87f6064ee6e528104617e40d8e75_3
cpool/6/7/c/67ca87f6064ee6e528104617e40d8e75_4
cpool/6/7/c/67ca87f6064ee6e528104617e40d8e75_6
cpool/6/7/c/67ca87f6064ee6e528104617e40d8e75_8
cpool/6/7/c/67ca87f6064ee6e528104617e40d8e75_5
cpool/6/7/c/67ca87f6064ee6e528104617e40d8e75_7
cpool/7/0/e/70e06ad5cc93e01f90d2279531a703b0_11
cpool/7/0/e/70e06ad5cc93e01f90d2279531a703b0_12
cpool/7/0/e/70e06ad5cc93e01f90d2279531a703b0_13
cpool/7/0/e/70e06ad5cc93e01f90d2279531a703b0_15
cpool/7/0/e/70e06ad5cc93e01f90d2279531a703b0_16
cpool/7/0/e/70e06ad5cc93e01f90d2279531a703b0_14
cpool/7/0/e/70e06ad5cc93e01f90d2279531a703b0_17
cpool/9/0/5/9055eda8bbd7104cf4269a044f83b0b9_1
cpool/9/0/5/9055eda8bbd7104cf4269a044f83b0b9_0
cpool/f/8/7/f87d435e6c349e00fba50f48881055ac
```

Should these have been removed? Can I safely remove them manually?
