### ISSUE TITLE
Warning: The unit file, source configuration file or drop-ins of backuppc.service changed on disk. Run 'systemctl daemon-reload' to reload units

### ISSUE THREAD

**Issue by rocky91-shi** [backuppc/backuppc#328]
hello，everyone! This is my problem as blew:

After I Configured backuppc on centos8，when I start backuppc.service。it Shows the following error，Are there Any good suggestions?Thanks in advance

[root@localhost ~]# systemctl status backuppc.service 
Warning: The unit file, source configuration file or drop-ins of backuppc.service changed on disk. Run 'systemctl daemon>
● backuppc.service - SYSV: Starts and stops the BackupPC server
   Loaded: loaded (/etc/rc.d/init.d/backuppc; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2020-03-21 14:22:03 CST; 13min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 4482 ExecStart=/etc/rc.d/init.d/backuppc start (code=exited, status=1/FAILURE)

Mar 21 14:22:03 localhost.localdomain systemd[1]: Starting SYSV: Starts and stops the BackupPC server...
Mar 21 14:22:03 localhost.localdomain backuppc[4482]: Starting BackupPC: runuser: user __BACKUPPCUSER__ does not exist
Mar 21 14:22:03 localhost.localdomain backuppc[4482]: [FAILED]
Mar 21 14:22:03 localhost.localdomain systemd[1]: backuppc.service: Control process exited, code=exited, status=1/FAILURE
Mar 21 14:22:03 localhost.localdomain systemd[1]: backuppc.service: Failed with result 'exit-code'.
Mar 21 14:22:03 localhost.localdomain systemd[1]: Failed to start SYSV: Starts and stops the BackupPC server.

**Comment by craigbarratt** [comment]
This is configuration error in the backuppc.service file.  The placeholder user name BACKUPPCUSER hasn't been replaced with a valid user name.

Also, please post these questions to the BackupPC-user list.  Don't use a git issue for a user question.

**Comment by hobbes1069** [comment]
Also, I would recommend using my package in Fedora EPEL. You're using the SYSV compatibily part of systemD and my package provides a systemd service file. 

You need to enable both Fedora's EPEL repository and PowerTools and then a simple "dnf install BackupPC".

https://fedoraproject.org/wiki/EPEL#How_can_I_use_these_extra_packages.3F

**Comment by rocky91-shi** [comment]
> Also, I would recommend using my package in Fedora EPEL. You're using the SYSV compatibily part of systemD and my package provides a systemd service file.
> 
> You need to enable both Fedora's EPEL repository and PowerTools and then a simple "dnf install BackupPC".
> 
> https://fedoraproject.org/wiki/EPEL#How_can_I_use_these_extra_packages.3F

Thank you for your suggestion and I understand what you mean，I will try it。 
The job i am doing is migrating BackupPC on centos8 to the customization system。
I guess are the above errors caused by software dependencies？Also I mean to use systemd file to start backuppc.service defaultly，but why it use he SYSV compatibily(/etc/init.d/) to start backuppc.service？
