### ISSUE TITLE
cpool files are read during incrementals 

### ISSUE THREAD

**Issue by johanehnberg** [backuppc/backuppc#33]
rsync_bpc seems to read cpool files even though the backup run is an incremental. This is likely unnecessary.

$ ps axu | grep BackupPC_dump
23954 ?        S      0:38 /usr/bin/perl /usr/local/BackupPC/bin/BackupPC_dump -i 10.1.0.2

$ lsof -c rsync_bpc |grep 6r
rsync_bpc 23967 backuppc    6r   REG  252,3 1339727 10630613 /srv/backuppc/cpool/8c/00/8c009fd0961ad87695362436629abcde

**Comment by craigbarratt** [comment]
These are almost certainly the pooled attrib files, which contain all the file names and meta data, one per directory.  They need to be read during all backups including incrementals.  So this is working as intended.  You can check if it's an attrib file by printing it:

    /usr/local/BackupPC/bin/BackupPC_attribPrint /srv/backuppc/cpool/8c/00/8c009fd0961ad87695362436629abcde

Alternatively, you can do this:

    /usr/local/BackupPC/bin/BackupPC_zcat /srv/backuppc/cpool/8c/00/8c009fd0961ad87695362436629abcde | od -t x1

The attrib file starts with a magic number 0x17585451, so the first four byes should be:

    0000000 17 56 53 53

**Comment by johanehnberg** [comment]
Thanks, ran the tests you suggested, they did not match attrib file:

attribPrint:
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE (\w+)}(\+?)/ at /usr/local/BackupPC/lib/BackupPC/Lib.pm line 1104.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/(.*)\${ <-- HERE (\w+)}(\+?)(.*)/ at /usr/local/BackupPC/lib/BackupPC/Lib.pm line 1109.
BackupPC_attribPrint: cannot read attrib file /srv/backuppc/cpool/8c/00/8c009fd0961ad87695362436629abcde

Hex tells us it is an MP4:
0000000 00 00 00 14 66 74 79 70 71 74 20 20 00 00 00 00
0000020 71 74 20 20 00 00 00 08 77 69 64 65 0e 1c c7 ed
0000040 6d 64 61 74 00 cc 40 07 01 02 99 cc 3d bd 56 cb
0000060 62 47 3f 3e 9f e7 f8 ea f8 5a ff fd bb df b6 e7
0000100 b4 d7 13 80 48 40 22 27 93 41 2b a0 54 81 7e 6d
0000120 cf a4 39 7c ef d2 be 99 a5 3f 71 ed f8 be bf 60
0000140 e1 fc f3 1f bc 75 ff ea 76 ba 09 fc e2 3f cf 3b
0000160 1f 01 ca f8 88 3c 45 9e c9 c1 89 4d e2 94 fd b0
0000200 00 01 57 9f 6c bd 7e 65 a2 89 79 7a c6 03 64 5f
0000220 94 d4 59 14 1a 98 19 48 06 18 8b 05 6c a1 79 1c
...

I thought attrib was stored only in pool and cpool containing only raw data files?

For reference, I am thinking especially in terms of making use of BackupPC with scale-out filesystems or object storage, where any access to cpool may be avoidable due to latency. Pool (being more of a database now), could be kept on fast storage. I already have this working with SSD for pool and SMR for cpool and these reads are the biggest bottleneck with incrementals.

**Comment by craigbarratt** [comment]
I tried to replicate this, but the only cases I found of rsync_bpc reading a pool file was if its metadata had changed from the last backup.

You can investigate further by finding the client path for the file above using BackupPC_ls, eg:

    BackupPC_ls -R -h HOST -n NUM -s SHARE / | egrep 8c009fd0961ad87695362436629abcde

You can then look at that file's metadata (mtime etc) and compare it with the previous backup.
