### ISSUE TITLE
V. 4.3.2 on my Ubuntu Server 

### ISSUE THREAD

**Issue by paweldesign** [backuppc/backuppc#331]
I created a new server and ran the script:
https://github.com/backuppc/backuppc/wiki/Installing-BackupPC-4-from-tarball-or-git-on-Ubuntu
Connecting does not work

Are there any other guides on how to install version 4.3.2?
Thank you

Forbidden
You don't have permission to access this resource.

Apache/2.4.29 (Ubuntu) Server at 192.168.99.62 Port 80

**Comment by craigbarratt** [comment]
Please post questions on the use list.  Git issues are for bugs and feature requests.
