### ISSUE TITLE
Very low request of web improvment: WakeupSchedule is limited at 256 characters

### ISSUE THREAD

**Issue by tititototutu** [backuppc/backuppc#335]
Version:  BackupPC-4.3.0

Hello,

I quickly searched and i didn't find an associated ticket. I apologize if it's a duplicate.

The Web configuration fields for WakeupSchedule is limited to 256 characters which limits the number of backups possible per day.

For example, a backup every 1/2 hour is not entirely possible.

I know that this interval is extreme, but at the moment COVID the client stations are essentially on VPN and therefore connected intermittently.

It remains of course possible to directly edit the /etc/backuppc/config.pl file.

Thank you for your work!

Vincent

**Comment by moisseev** [comment]
It's doable. What length do you need?

But I am not sure if I understand you right. I believe for 1/2 hour schedule we need 219 characters:
~~~
[0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15, 15.5, 16, 16.5, 17, 17.5, 18, 18.5, 19, 19.5, 20, 20.5, 21, 21.5, 22, 22.5, 23, 23.5, 24]
~~~
Moreover, spaces can be removed to save some more space.

**Comment by hamster65** [comment]
I also ran into this limitation of the webinterface. My config has about 115 wakeup times defined. I want my clients (at home) to be backupped once they are on....
