### ISSUE TITLE
Unix connect to BackupPC.sock

### ISSUE THREAD

**Issue by masunile** [backuppc/backuppc#339]
After upgrading from Version 3 to 4.3.2.
The sidebar on the webpage works, but the main contents of the site just says:

```
This CGI script (/backuppc/index.cgi) is unable to connect to the BackupPC server on backup.mqn.local port -1.
The error was: unix connect to /var/run/BackupPC/BackupPC.sock: No such file or directory.
Perhaps the BackupPC server is not running or there is a configuration error. Please report this to your Sys Admin
```

This is caused by a missing variable in `config.pl`
`$Conf{IncrLevels} = [1];` Must be added, then it's fine.

**Comment by craigbarratt** [comment]
Most likely there was a typo or error in the Config file that causes the BackupPC to not start.  Are there any messages in the LOG file or system log when you start BackupPC?  You could try running it manually to see if there are any errors.  If the config file has a syntax error, BackupPC will print a message to stderr and exit.
