### ISSUE TITLE
BackupFilesExclude is removed when upgrading

### ISSUE THREAD

**Issue by masunile** [backuppc/backuppc#340]
When upgrading from Version 3.* to 4.3.2 (Haven't tested other versions) all the paths you have entered into `BackupFilesExclude` under `Edit Config > Xfer` is removed.

This causes backups that previously worked to error due to the backup job trying to backup the backup it's currently taking, and all the folders in linux it should stay out of.

So if `BackupFilesExclude` has variables, they should persist through upgrade.

It's atleast preferable.

**Comment by craigbarratt** [comment]
BackupFilesExclude should work unchanged between 3.x and 4.x.  It would be good to understand why it didn't for you.  What was it set to in 3.x (ie, a string, and array or a hash)?
