### ISSUE TITLE
When using BackupFilesOnly, files are not always stored

### ISSUE THREAD

**Issue by ondrejj** [backuppc/backuppc#341]
Not sure when, but sometimes files are not found when using BackupFilesOnly. I can use different backups for each directory, then everything works. This happens after upgrading from BackupPC 3 to version 4. Also with new file storage or upgraded, doesn't matter.

Here is my host config:
```
$Conf{BackupFilesOnly} = {
  '*' => [
    'var/www/html'
  ]
};
$Conf{BackupPCNightlyPeriod} = 1;
```

There are some accessible files in /var/www/html on this server. I can rsync them using this command `rsync -avPH root@test.bart.sk:/var/www/html/ /tmp/testwww/`. Backuppc uses this command: `/usr/bin/rsync --super --recursive --protect-args --numeric-ids --perms --owner --group -D --times --links --hard-links --delete --delete-excluded --one-file-system --partial --log-format=log:\ %o\ %i\ %B\ %8U,%8G\ %9l\ %f%L --stats --checksum --timeout=72000 --include=/var --include=/var/www --include=/var/www/html --exclude=/\* --exclude=/var/\* --exclude=/var/www/\* root@servername:/ /` (slightly modified).

This command doesn't copy contents of /var/ directory, just an empty /var directory itself.
Not sure why, but this happens always.

If somebody is using backuppc after upgrade from v3 to v4, old content is copied before rsync, then rsync is run, but no files are transferred. Users are satisfied, that some content is on their backup, but this is only old content, no new files are stored and no files removed.

**Comment by craigbarratt** [comment]
Likely the problem is --one-file-system causes anything below /var to be skipped (assuming that's on a different filesystem than /).

**Comment by ondrejj** [comment]
Yes, remove of one-file-system helps, but this should affect more users, which are upgrading from BackupPC 3 to 4. Also it's a problem, that this problem is silently ignored.
