### ISSUE TITLE
BackupPC 4.4.0 and BackupPC::XS 0.62

### ISSUE THREAD

**Issue by ggdagg** [backuppc/backuppc#351]
Hi,

I run BackupPC 4.3.2 on a Centos 7. I tried to upgrade to the 4.4.0 version today after following the requirement such as BackupPC::XS (0.62) and rsync-bpc (3.0.9.15) minimum. However, even if I have the correct version of BackupPC::XS, backuppc doesn't want to start.

Here are some logs:

	[root@backuppc BackupPC]# cpan -D BackupPC::XS
	Reading '/root/.cpan/Metadata'
	  Database was generated on Sun, 21 Jun 2020 11:17:03 GMT
	BackupPC::XS
	-------------------------------------------------------------------------
			(no description)
			C/CB/CBARRATT/BackupPC-XS-0.62.tar.gz
			/root/perl5/lib/perl5/x86_64-linux-thread-multi/BackupPC/XS.pm
			Installed: 0.62
			CPAN:      0.62  up to date
			Craig Barratt (CBARRATT)
			cbarratt@users.sourceforge.net

	[root@backuppc BackupPC]# systemctl status backuppc
	● backuppc.service - BackupPC server
	   Loaded: loaded (/etc/systemd/system/backuppc.service; enabled; vendor preset: disabled)
	   Active: active (running) since Sun 2020-06-21 20:19:16 CEST; 2s ago
	 Main PID: 10357 (BackupPC)
	   CGroup: /system.slice/backuppc.service
			   └─10357 /bin/perl /usr/local/BackupPC/bin/BackupPC

	Jun 21 20:19:16 backuppc systemd[1]: Started BackupPC server.
	Jun 21 20:19:16 backuppc BackupPC[10357]: BackupPC: old version 0.57 of BackupPC::XS: need >= 0.62; exiting in 30s

Is there anything I missed? Do you have any suggestion?

Thanks.

**Comment by craigbarratt** [comment]
Is it possible you have multiple versions of perl installed?  Look at the first line of /usr/local/BackupPC/bin/BackupPC.  Using that path for perl, run:
```
whateverPathToPerl/perl -e 'use BackupPC::XS; print("$BackupPC::XS::VERSION\n")'
```
Compare to the first line in `which cpan`

**Comment by ggdagg** [comment]
Below are the results:

	[root@backuppc ~]# head /usr/local/BackupPC/bin/BackupPC
	#!/bin/perl
	#============================================================= -*-perl-*-
	#
	# BackupPC: Main program for PC backups.
	#
	# DESCRIPTION
	#
	#   BackupPC reads the configuration and status information from
	#   $ConfDir/conf.  It then runs and manages all the backup activity.
	#
	[root@backuppc ~]# /bin/perl -e 'use BackupPC::XS; print("$BackupPC::XS::VERSION\n")'
	0.62
	[root@backuppc ~]# which cpan
	/bin/cpan
	[root@backuppc ~]# which perl
	/bin/perl

I'm not really familiar with perl, but it doesn't look like I have different versions on my system. I will try to dig a bit more. Meanwhile, if you have any other suggestion they are welcomes ;)

**Comment by craigbarratt** [comment]
A few more lines down /usr/local/BackupPC/bin/BackupPC will be a line like this:
```
use lib "/usr/local/BackupPC/lib";
```
What is in that directory, and what's in the BackupPC directory below that?

**Comment by ggdagg** [comment]
This is the result:
	
	[root@backuppc ~]# ls /usr/local/BackupPC/lib/ -R
	/usr/local/BackupPC/lib/:
	BackupPC  Net

	/usr/local/BackupPC/lib/BackupPC:
	CGI  Config  DirOps.pm  Lang  Lib.pm  Storage  Storage.pm  View.pm  Xfer  Xfer.pm  Zip

	/usr/local/BackupPC/lib/BackupPC/CGI:
	AdminOptions.pm  Browse.pm        EditConfig.pm    HostInfo.pm  Metrics.pm       RestoreFile.pm  RSS.pm              StopServer.pm
	ArchiveInfo.pm   DeleteBackup.pm  EmailSummary.pm  Lib.pm       Queue.pm         RestoreInfo.pm  StartServer.pm      Summary.pm
	Archive.pm       DirHistory.pm    GeneralInfo.pm   LOGlist.pm   ReloadServer.pm  Restore.pm      StartStopBackup.pm  View.pm

	/usr/local/BackupPC/lib/BackupPC/Config:
	Meta.pm

	/usr/local/BackupPC/lib/BackupPC/Lang:
	cz.pm  de.pm  en.pm  es.pm  fr.pm  it.pm  ja.pm  nl.pm  pl.pm  pt_br.pm  ru.pm  uk.pm  zh_CN.pm

	/usr/local/BackupPC/lib/BackupPC/Storage:
	Text.pm

	/usr/local/BackupPC/lib/BackupPC/Xfer:
	Archive.pm  Ftp.pm  Protocol.pm  Rsync.pm  Smb.pm  Tar.pm

	/usr/local/BackupPC/lib/BackupPC/Zip:
	FileMember.pm

	/usr/local/BackupPC/lib/Net:
	FTP

	/usr/local/BackupPC/lib/Net/FTP:
	AutoReconnect.pm  RetrHandle.pm

**Comment by craigbarratt** [comment]
That looks normal (I was thinking perhaps somehow the old version of BackupPC::XS was installed below /usr/local/BackupPC/lib, but that's not the case).

Can you confirm that original perl version check produces the same answer when you run it as the BackupPC user?  Perhaps that user has a different PATH and perl, or there is some weird permissions problem.

You could also run perl -V to see the search path for modules (`@INC` at the end of the output), and try to find out where/why there is an old version still sitting around.  You could also add some debug code to the start of /usr/local/BackupPC/bin/BackupPC using, eg, [Module::Path](https://metacpan.org/pod/Module::Path) to find and print the actual path to the module.

**Comment by ggdagg** [comment]
Thanks, you got a good point since when I checked with the backuppc user, I had a different version of BackupPC::XS: 

	[backuppc@backuppc ~]$ /bin/perl -e 'use BackupPC::XS; print("$BackupPC::XS::VERSION\n")'
	0.57

I managed to install the latest version with:

	[backuppc@backuppc ~] cpan install BackupPC::XS
	[backuppc@backuppc ~]$ /bin/perl -e 'use BackupPC::XS; print("$BackupPC::XS::VERSION\n")'
	0.62
	[backuppc@backuppc ~]$ cpan -D BackupPC::XS
	Reading '/home/backuppc/.cpan/Metadata'
	  Database was generated on Sun, 21 Jun 2020 00:17:03 GMT
	BackupPC::XS
	-------------------------------------------------------------------------
			(no description)
			C/CB/CBARRATT/BackupPC-XS-0.62.tar.gz
			/home/backuppc/perl5/lib/perl5/x86_64-linux-thread-multi/BackupPC/XS.pm
			Installed: 0.62
			CPAN:      0.62  up to date
			Craig Barratt (CBARRATT)
			cbarratt@users.sourceforge.net

However, when I go back as root and try to start the service again, I still have the same error:

	[root@backuppc ~]# systemctl start backuppc
	[root@backuppc ~]# systemctl status backuppc
	● backuppc.service - BackupPC server
	   Loaded: loaded (/etc/systemd/system/backuppc.service; enabled; vendor preset: disabled)
	   Active: active (running) since Mon 2020-06-22 01:31:51 CEST; 23s ago
	 Main PID: 1644 (BackupPC)
	   CGroup: /system.slice/backuppc.service
			   └─1644 /bin/perl /usr/local/BackupPC/bin/BackupPC

	Jun 22 01:31:51 backuppc systemd[1]: Started BackupPC server.
	Jun 22 01:31:52 backuppc BackupPC[1644]: BackupPC: old version 0.57 of BackupPC::XS: need >= 0.62; exiting in 30s

This is strange, but as you suggested there might be something incorrect in my permission. I will try to find this out and I will let you know.

**Comment by hobbes1069** [comment]
Ok, so I've followed this thread, but I'm working on updating Fedora and
EPEL. I have a COPR for EPEL. If you give me a few days I should have an
update available.

Thanks,
Richard

**Comment by picklesrein** [comment]
FYI, 4.4.0 & 0.62 are available in EPEL Testing repository:
`dnf install --enablerepo=epel-testing backuppc`

**Comment by hobbes1069** [comment]
On Tue, Jun 30, 2020 at 7:27 AM System Admin <notifications@github.com>
wrote:

> FYI, 4.4.0 & 0.62 are available in EPEL Testing repository:
> dnf install --enablerepo=epel-testing backuppc
>

Yes, but that's for EL 8 only. EL 7 is staying with 3.x. In order to
upgrade to 4.x you have to use my COPR:

https://copr.fedorainfracloud.org/coprs/hobbes1069/BackupPC/

Thanks,
Richard

**Comment by ggdagg** [comment]
Thank you everybody.
I couldn't find out why my system still shows me the BackupPC::XS error, but now that we have alternatives I believe I can close this issue. Thanks again for your help.
