### ISSUE TITLE
Issues with Prometheus metrics

### ISSUE THREAD

**Issue by LuigiPattyn** [backuppc/backuppc#364]
Hello!

We run backuppc as a Docker container on a dedicated server for backup-ing (image: `adferrand/backuppc:4.4.0`). When we recently updated our instance to v4.4.0 our logs started flooding with the following log lines:

```
BackupPC_Admin: Use of uninitialized value in string eq at /usr/local/BackupPC/lib/BackupPC/CGI/Metrics.pm line 302.

BackupPC_Admin: Use of uninitialized value in numeric le (\u003c=) at /usr/local/BackupPC/lib/BackupPC/CGI/Metrics.pm line 292
BackupPC_Admin: Use of uninitialized value in concatenation (.) or string at /usr/local/BackupPC/lib/BackupPC/CGI/Metrics.pm line 307
BackupPC_Admin: "my" variable $hostState masks earlier declaration in same scope at /usr/local/BackupPC/lib/BackupPC/CGI/Metrics.pm line 226.
BackupPC_Admin: "my" variable $hostLastAttempt masks earlier declaration in same scope at /usr/local/BackupPC/lib/BackupPC/CGI/Metrics.pm line 227
BackupPC_Admin: "my" variable $hostDisabled masks earlier declaration in same scope at /usr/local/BackupPC/lib/BackupPC/CGI/Metrics.pm line 228.
BackupPC_Admin: Variable "%poolMapper" will not stay shared at /usr/local/BackupPC/lib/BackupPC/CGI/Metrics.pm line 98.\n
```
This is only just a snippet of the logs we see. Because these are printed every 15sec, the first log line even gets printed +- 50times every 15sec. 

This issue might also be related to a problem with the metrics that are exposed at the Prometheus end point.
One of the metrics keeps giving a Array pointer instead of the value:
```
backuppc_hosts_full_keep_count{host="xxx.yyy"} ARRAY(0x55a8c73d4620)
backuppc_hosts_full_keep_count{host="xxx.yyy"} ARRAY(0x55a8c619c578)
backuppc_hosts_full_keep_count{host="xxx.yyy"} ARRAY(0x55a8c61a8200)
```
This results in Prometheus unable to parse the metrics. 

I also wanted to point out that there might be a small typo in the documentation about the metrics.
```
    http://localhost/cgi-bin/BackupPC/BackupPC_Admin?action=metrics?format=json
    http://localhost/cgi-bin/BackupPC/BackupPC_Admin?action=metrics?format=prometheus
    http://localhost/cgi-bin/BackupPC/BackupPC_Admin?action=metrics?format=rss
```
Shouldn't it be:
```
    http://localhost/cgi-bin/BackupPC/BackupPC_Admin?action=metrics&format=json
    http://localhost/cgi-bin/BackupPC/BackupPC_Admin?action=metrics&format=prometheus
    http://localhost/cgi-bin/BackupPC/BackupPC_Admin?action=metrics&format=rss
```
I could be wrong, but the currently documented metrics endpoint (with `?`) doesn't work, only when I use the `&` ones. 

Thank you for still maintaining this project!

**Comment by pbe-axelor** [comment]
Related to unreleased PR #362 #361 and #353.

**Comment by LuigiPattyn** [comment]
I'll close this issue, because it will probably be fixed in the next release :smile:
