### ISSUE TITLE
installation error 4.4.0

### ISSUE THREAD

**Issue by zhuanmentiwen** [backuppc/backuppc#370]
backuppc 4.4.0 
CentOS Linux release 7.8.2003 (Core)

perl configure.pl --batch --cgi-dir /var/www/cgi-bin/backuppc \
> --data-dir /data0/backuppc --hostname backuppc --html-dir /var/www/html/backuppc \
> --html-dir-url /backuppc --install-dir /opt/backuppc

**You need to run makeDist first to create a tarball release that includes an
updated configure.pl.  After you unpack the tarball, run configure.pl from
there.**

How to solve this problem？

**Comment by craigbarratt** [comment]
It looks like you are trying to run `configure.pl` from a clone of the master github.  If you really want to do that, as the message says, you need to run `makeDist` first.

I recommend you start with the [4.4.0 release](https://github.com/backuppc/backuppc/releases/tag/4.4.0): download the [BackupPC-4.4.0.tar.gz](https://github.com/backuppc/backuppc/releases/download/4.4.0/BackupPC-4.4.0.tar.gz) file and use that instead.

**Comment by zhuanmentiwen** [comment]
[root@Hnjyt BackupPC-4.4.0]# perl configure.pl --batch --cgi-dir /var/www/cgi-bin/backuppc --data-dir /data0/backuppc --hostname backuppc --html-dir /var/www/html/backuppc --html-dir-url /backuppc --install-dir /opt/backuppc

Perl package BackupPC::XS needs to be at least version 0.62.
The currently installed BackupPC::XS is version 0.59.

Please upgrade package BackupPC::XS to the latest version and then re-run
this script.

**Comment by craigbarratt** [comment]
The messages are self explanatory.  Please read the text you pasted.

Git issues are intended for potential bugs or new feature suggestions.  For further questions please email the user list instead.
