### ISSUE TITLE
Stuck on "is queued on the user queue"

### ISSUE THREAD

**Issue by plegrand1** [backuppc/backuppc#377]
Hello,
i'm using backuppc to backup a windows 10 client. (rsync over ssh)
No problem to connect to the client with ssh.
When i start the complete backup, at the beginning, everything works 
fine and after a certain time, the backup stop with this message : "host 
blabla is queued on the user queue (will be backed up soon)".
Nothing in the log can explain what happens.
Can you help me ?

Debian stable
Backuppc : 3.3.2-2+deb10u1
rsync on the windows client (cygwin) :version 3.2.4dev  protocol version 31

Thanks for help

**Comment by craigbarratt** [comment]
This was cross-posted on the user list, which is the correct place.  So closing it here.
