### ISSUE TITLE
Feature Request: SendmailArgs

### ISSUE THREAD

**Issue by tadr0** [backuppc/backuppc#384]
Would anyone object to a pull request to add SendmailArgs to go along with SendmailPath like RsyncArgs are used with RsyncPath?

I have a deployment situation that seems to require it and a few simple patches that seem to make it work. I would like to push them upstream.

BTW thanks to everyone who made this so easy. BackupPC internals seem organized for comprehension from the outside.

**Comment by craigbarratt** [comment]
Yes, happy to consider this.  Please submit a PR.

**Comment by craigbarratt** [comment]
Closing based on merged PR #385.
