### ISSUE TITLE
v4 alpha 3 - Running BackupPC_refCountUpdate when not needed - Performance issue

### ISSUE THREAD

**Issue by adamgoryachev** [backuppc/backuppc#4]
Copied from the mailing list on 2016-01-22:

> I have glanced at the code and also believe that BackupPC_fsck is running
> unnecessarily after every backup attempt, whether it is successful or not.
> 
> In my xferLogs, BackupPC_refCountUpdate is being called twice at the end of
> a backup. Once like this:
> 
> Xfer PIDs are now
> Running BackupPC_refCountUpdate -h afsgaia1.cas.unc.edu on somehost.unc.edu
> xferPids 4508
> BackupPC_refCountUpdate: host somehost.unc.edu got 0 errors
> BackupPC_refCountPrint: total errors: 0
> xferPids
> Finished BackupPC_refCountUpdate (running time: 16 sec)
> 
> Then again like this:
> Running BackupPC_refCountUpdate -h somehost.unc.edu -f -c on somehost.unc.edu
> xferPids 4509
> BackupPC_refCountUpdate: host somehost.unc.edu got 0 errors
> BackupPC_refCountPrint: total errors: 0
> xferPids
> Finished BackupPC_refCountUpdate (running time: 1334 sec)
> 
> The second refCountUpdate includes the "-f -c" args which appear to force
> an fsck on the host.
> 
> I'm using rsync over ssh and there are no errors reported:
> 
> Done: 0 errors, 31 filesExist, 86366561 sizeExist, 47163323 sizeExistComp,
> 0 filesTotal, 0 sizeTotal, 49 filesNew, 180552022 sizeNew, 58504938
> sizeNewComp, 242121 inode
> Number of files: 105259
> Number of files transferred: 179
> Total file size: 2823131278 bytes
> Total transferred file size: 292936438 bytes
> Literal data: 18830521 bytes
> Matched data: 248088062 bytes
> File list size: 2308933
> File list generation time: 0.001 seconds
> File list transfer time: 0.000 seconds
> Total bytes sent: 616768
> Total bytes received: 21567585
> sent 616768 bytes  received 21567585 bytes  36638.07 bytes/sec
> total size is 2823131278  speedup is 127.26
> DoneGen: 0 errors, 2 filesExist, 8306 sizeExist, 61440 sizeExistComp, 90549
> filesTotal, 2823131278 sizeTotal, 0 filesNew, 0 sizeNew, 0 sizeNewComp,
> 242138 inode
> 
> Unlike Gandalf, my backups are succeeding. I have successfully performed
> restores. Fulls and incrs happen as expected. Expiration looks correct per
> my config policy.

Yes, exactly. It seems to run the full fsck even when not required. 
Preventing the second run is probably easy, but working out why it was 
written that way, and ensuring it really isn't needed, that is harder.....

If you have some extra time to look into the code, then I'm sure many 
people would appreciate any analysis you can do.

**Comment by craigbarratt** [comment]
I decided to do a full fsck every time to make sure things were stable.  The plan was to turn this off once we're convinced everything is working correctly.

**Comment by ngharo** [comment]
I'm convinced it's working correctly.  Can we move to get this behavior turned off or as an option?

**Comment by craigbarratt** [comment]
I've made substantial changes to reference counting for 4.x.  It's configurable, and the default is now to only do an fsck on just full backups (and never all the backups).
