### ISSUE TITLE
Can't backup with Windows and SMB

### ISSUE THREAD

**Issue by vp-lab** [backuppc/backuppc#408]
Hello,
We have 2 nodes with backuppc but I can't get to work the SMB backup with Windows machines.
Both hosts have the same config file. On one node everything it's working.
Backuppc v3.3.1 on centos7 .

`$Conf{SmbShareName} = [
  'Safe'
];
$Conf{SmbSharePasswd} = 'xxxxxxxxxxxx';
$Conf{SmbShareUserName} = 'backuppc';
$Conf{XferMethod} = 'smb';
$Conf{BackupZeroFilesIsFatal} = '0';
$Conf{SmbClientFullCmd} = '$smbClientPath \\\\$host\\$shareName $I_option -U $userName -E -d 1 -c tarmode\\ full -Tc$X_
option - $fileList';
$Conf{SmbClientIncrCmd} = '$smbClientPath \\\\$host\\$shareName $I_option -U $userName -E -d 1 -c tarmode\\ full -TcN$X
_option $timeStampFile - $fileList';`

I get this error every time:

`Running: /usr/bin/smbclient \\\\obi.xxxxxxxxxx\\SafeNet -U backuppc -E -d 1 -c tarmode\ full -Tc -
full backup started for share Safe
Xfer PIDs are now 20433,20432
tar:316  tarmode is now full, system, hidden, noreset, quiet
tarExtract: Done: 0 errors, 466 filesExist, 40434492 sizeExist, 12877089 sizeExistComp, 466 filesTotal, 40434492 sizeTotal
Got fatal error during xfer (tar:717  Total bytes received: 40434492)
Backup aborted (tar:717  Total bytes received: 40434492)
Not saving this as a partial backup since it has fewer files than the prior one (got 466 and 0 files versus 466)
`

Thank you.

**Comment by ediazrod** [comment]
I recomend to you to upgrade to the v 4.4.0 version because backuppc on 3. is very old.

If don't work try my guide using rsync client, better option on my opinion, but less flexible.

**Comment by ValentinPifu** [comment]
It's an easy way to update from 3.3 to 4.4.0 on CentOS 7? I'll lose all the backup data?

**Comment by ediazrod** [comment]
not at all, is pretty easy, just donwload and follow the guide you don't need to make anything only enable V3 backups, and in a time upgrade the V3 backup to the V4.. (takes time), Read the doc.
