### ISSUE TITLE
backuppc:4.4.0 RsyncClientPath add sudo error

### ISSUE THREAD

**Issue by plabanowski** [backuppc/backuppc#413]
Hello, I think I have an error equivalent to issue #204

`$Conf{RsyncClientPath} = '"sudo /usr/bin/rsync"';`

```
BackupPC.x86_64                      4.4.0-1.el8                             @epel        
BackupPC-XS.x86_64                   0.62-1.el8                              @epel
rsync.x86_64                         3.1.3-9.el8                             @anaconda    
rsync-bpc.x86_64                     3.1.3.0-1.el8                           @epel
```
I tried different configuration for the variable _RsyncClientPath_. But I still get the following result  : 

`rsync_bpc: Failed to exec --rsync-path=sudo /usr/bin/rsync: No such file or directory (2)`

thx

**Comment by plabanowski** [comment]
Sorry, you can close this issue . the error message misled me. 
The problem came from the user ssh connection .
var `RsyncSshArgs ` with arg `$sshPath -l root` and not my backup user

**Comment by craigbarratt** [comment]
Glad it's solved.  One thing that doesn't look right is your setting for `$Conf{RsyncClientPath}` - it has two sets of quotes.  It should only have one set of quotes, eg:
```
$Conf{RsyncClientPath} = 'sudo /usr/bin/rsync";
```
