### ISSUE TITLE
No graph in homepage 4.4.0

### ISSUE THREAD

**Issue by tabtab-ops** [backuppc/backuppc#416]
Hello all,

I installed fresh BackupPC 4.4.0 on Debian 10 since 1 week, start backup hosts since 3 days.
There's no graph in homepage of BackupPC.
I don't have any pool.rrd file in /var/lib/backuppc/log.
The package rrdtools is well installed on the server.

The rights in the log folder are the followings :
-r--r--r-- 1 backuppc backuppc     4 févr. 10 09:33 BackupPC.pid
srwxr-x--- 1 backuppc backuppc     0 févr. 10 09:33 BackupPC.sock
-rw-r----- 1 backuppc backuppc     0 févr. 11 08:00 LOCK
-rw-r----- 1 backuppc backuppc  3191 févr. 11 08:00 LOG
-rw-r----- 1 backuppc backuppc  1375 févr. 11 01:00 LOG.0.z
-rw-r----- 1 backuppc backuppc  1943 févr. 10 01:00 LOG.1.z
-rw-r----- 1 backuppc backuppc  1519 févr.  7 01:00 LOG.2.z
-rw-r----- 1 backuppc backuppc 21356 févr. 11 08:00 status.pl
-rw-r----- 1 backuppc backuppc 21356 févr. 11 07:00 status.pl.old
-rw-r----- 1 backuppc backuppc   391 févr. 11 01:00 UserEmailInfo.pl

The rights in the backuppc folder are the followings :
drwxr-x---   2 backuppc backuppc 4096 févr.  4 17:10 conf
drwxr-x--- 130 backuppc backuppc 4096 févr. 11 01:23 cpool
drwxr-x---   2 backuppc backuppc 4096 févr. 11 08:00 log
drwxr-x---   6 backuppc backuppc 4096 févr. 10 09:38 pc
drwxr-x---   2 backuppc backuppc 4096 août  12  2020 pool

I don't have any relating errors in error Apache logs or in syslog.
What must I verify to have the graph ?

Thanks in advance
Nicolas

**Comment by craigbarratt** [comment]
Have you installed `rrdtool`?

**Comment by tabtab-ops** [comment]
Yes it's installed, version 1.7.1-2.
Thanks
Nicolas

**Comment by moisseev** [comment]
What about BackupPC log? Is there anything about BackupPC_rrdUpdate?
It should happen at the end of BackupPC_nightly run.
Something like this:
```
2021-02-11 01:14:35 Running BackupPC_rrdUpdate (pid=32153)
2021-02-11 01:14:40  admin-1 : RRD updated: date 1613001600; cpoolKb 0.000000; total 2601366469.384766; poolKb 0.000000; pool4Kb 98817650.000000; cpool4Kb 0.000000
2021-02-11 01:14:45 Finished  admin-1  (BackupPC_rrdUpdate)
```

**Comment by tabtab-ops** [comment]
Here's something interesting :
```
2021-02-11 01:00:46 Cpool4 nightly clean removed 0 files of size 0.00GB
2021-02-11 01:00:46 Cpool4 is 187.18GB, 258586 files (0 repeated, 0 max chain, 206 max links), 16512 directories
2021-02-11 01:00:46 Running BackupPC_rrdUpdate (pid=12694)
2021-02-11 01:00:47  admin-1 :  is not a valid executable
2021-02-11 01:00:47 Finished  admin-1  (BackupPC_rrdUpdate)
```

**Comment by tabtab-ops** [comment]
It works ! Many thanks
Nicolas
