### ISSUE TITLE
bpc 4.0.0 configure failed

### ISSUE THREAD

**Issue by gazbarg** [backuppc/backuppc#43]
4.0.0 misses some files (BackupPC::XS ?) :

`perl ./configure.pl `

`Error loading BackupPC::Lib: Can't locate BackupPC/XS.pm in @INC (you may need to install the BackupPC::XS module) (@INC contains: ./lib /etc/perl /usr/local/lib64/perl5/5.22.3/x86_64-linux /usr/local/lib64/perl5/5.22.3 /usr/lib64/perl5/vendor_perl/5.22.3/x86_64-linux /usr/lib64/perl5/vendor_perl/5.22.3 /usr/local/lib64/perl5 /usr/lib64/perl5/vendor_perl /usr/lib64/perl5/5.22.3/x86_64-linux /usr/lib64/perl5/5.22.3 .) at lib/BackupPC/Lib.pm line 51.`
`BEGIN failed--compilation aborted at lib/BackupPC/Lib.pm line 51.`
`Compilation failed in require at (eval 16) line 2.`

**Comment by gazbarg** [comment]
Answering to myself :-(
I thought the 4.0.0 ZIP contained all needed stuff. I've just found the Backuppc-XS repo.
Sorry for the wrong issue, may be closed or destroyed.

**Comment by craigbarratt** [comment]
Yes, you need to have BackupPC::XS installed.  However, the error message isn't very helpful (since BackupPC:Lib now includes Backup::XS).  I'll update it so it prints a nicer error message.
