### ISSUE TITLE
Backup windows with smb over vpn

### ISSUE THREAD

**Issue by vp-lab** [backuppc/backuppc#451]
We update both nodes of backuppc from v3 to v4 and I have a small problem with a samba backup.

**First node** - it's on main location with IP 192.168.2.39 [no problems here]
**Second node** - on a remote location with IP 192.168.4.25 [can't backup a windows machine]
Between the nodes it's a VPN site-to-site.

windows machine config - backuppc
```
$Conf{BackupPCNightlyPeriod} = 1;
$Conf{SmbShareName} = [
  'xcccca',
  ''
];
$Conf{SmbSharePasswd} = 'backuppc';
$Conf{SmbShareUserName} = 'backuppc';
$Conf{XferMethod} = 'smb';
$Conf{XferLogLevel} = 2;
```

error from second node
```
2021-12-14 15:43:41 full backup started for share xca
2021-12-14 15:43:42 unexpected empty share name skipped
2021-12-14 15:43:47 Backup aborted ()
```

I can see all the backup files on second node interface but I get the error above.

There's something I'm missing?

Thank you.

**Comment by hamster65** [comment]
I think in $Conf{SmbShareName} there is a list / an array of two smb share names given. The second one is empty.

**Comment by candiedoperation** [comment]
@vp-lab, using rsyncd method in windows instead of smb is faster, better and easy-to-implement. Just try it out once...
_(This is just a recommendation and not a solution to the above issue)_

**Comment by vp-lab** [comment]
> I think in $Conf{SmbShareName} there is a list / an array of two smb share names given. The second one is empty.

That was the problem. Thank you for your help.
