### ISSUE TITLE
BPC4 host summary

### ISSUE THREAD

**Issue by gazbarg** [backuppc/backuppc#46]
In BPC3, recently backed-up hosts where color-coded  (light green by default). This seems to have disappeared in BPC4 (or I have managed to miss the configuration option). 
This color-coding was very useful to quickly know the latest backed-up hosts. It would be nice to have it back.

**Comment by craigbarratt** [comment]
It works for me.  See $Conf{CgiStatusHilightColor}.

**Comment by gazbarg** [comment]
As a matter of fact, it does work here also. 
But the delay between "backup done" and "idle" seems really shorter than for BPC3, which explains why I thought the 'backup done' state was not used. What drives the switch between 'backup done' and 'idle' statuses ?
