### ISSUE TITLE
BackupPC_archiveHost is not suitable for building a command pipe

### ISSUE THREAD

**Issue by pelzvieh** [backuppc/backuppc#463]
BackupPC_archiveHost could be an ideal tool to start an archiving pipe to programmatically stream backup archives to remote destinations. However, it does not keep stdout clean but print diagnostics to stdout instead of stderr. Plus, having a pipe as destination is not supported by one check.

**Comment by liedekef** [comment]
Any tips on how to use BackupPC_archiveHost after this fix? Currently we backup 2 times (2 backuppc servers) but this might help ...
