### ISSUE TITLE
BPC4 date format

### ISSUE THREAD

**Issue by gazbarg** [backuppc/backuppc#47]
In BPC4 web interface, dates are displayed as month/day. The date format should be configurable (best IMHO) or in ISO (YYY-MM-DD) format.

**Comment by craigbarratt** [comment]
See $Conf{CgiDateFormatMMDD}:
#
# Date display format for CGI interface.  A value of 1 uses US-style
# dates (MM/DD), a value of 2 uses full YYYY-MM-DD format, and zero
# for international dates (DD/MM).
#
$Conf{CgiDateFormatMMDD} = 1;

If you use 0 or 1, it will add the year (DD/MM/YY or MM/DD/YY) if it is more than 330 days old.
