### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by BenjaminLefoul** [backuppc/backuppc#48]
Hi Craig,

On the mailing list, you ask about branches. I think I would just rename "v3.xx" "release" and rename "master" "development" and delete all the rest (nothing forces you to have a master branch, it's only so common because no one bothers giving a non-default name to the first commit's branch).

When it's time to move 4 from alpha to stable, just do a merge.

**Comment by moisseev** [comment]
@BenjaminLefoul  I don't see any obstacles to delete `v4.0.0` branch, but I don't see the point in renaming `master` -> `development` as `master` is common.

Also I don't like the idea of merging master branch into stable branch on release. In general it makes hard to support previous versions. In my opinion it would be better to branch out stable versions from `master` and continue development in the`master` branch.

**Comment by BenjaminLefoul** [comment]
That sounds very reasonable.

**Comment by raoulbhatia** [comment]
I agree. I cannot thubk about any reason to rename master to development.

Removing v4.0.0 is fine. You can create a new branch from master once v4 is ready to be released.

Raoul

**Comment by craigbarratt** [comment]
Ok, I just deleted the v4.0.0 branch.  Master is the active 4.x development branch, and the 4.0.0 release was tagged as v4_0_0.
