### ISSUE TITLE
Both v3 and v4 Pool Graphs Displayed

### ISSUE THREAD

**Issue by Furynation** [backuppc/backuppc#488]
I am in a situation where I upgraded from v3 to v4 (via a Linux distro upgrade), and both sets of pool size graphs now show up:
![backuppc-dual-graphs](https://user-images.githubusercontent.com/2816767/206870885-2bf1a061-3e54-42f0-bd21-157399531af6.png)

Not sure if this is pertinent, but when I initially upgraded, the, v4 graphs wouldn't show up, and only the stale v3 graphs would. Conf{RrdToolPath} was not set. Setting that path correctly brought the v4 graphs back, but the v3 graphs never went away.

Is there any way I can remove the v3 graphs?

**Comment by moisseev** [comment]
Originally the pool graphs were introduced in Debian distro package by the package maintainer and later they were included in the upstream code.
I believe you should contact the distro package maintainer. I am quite sure they just forgot to remove the obsolete patch.

**Comment by Furynation** [comment]
That makes sense. This happened on Linux Mint, which is derived from Ubuntu. Maybe I'll try re-installing the package and see if that helps. Thanks!

**Comment by kwisatz** [comment]
@Furynation did you create a bug report with Debian and would you have the ticket number if so?

**Comment by Furynation** [comment]
@kwisatz No, I haven't filed a bug report yet. I'm not convinced this is a distribution bug. This started happening when I went through a major Linux (Mint Linux) distribution upgrade. There were things broken which I had to manually fix. 

I don't recall what they were, but it was something with rrdtool or the configuration with it, just to get the graphs to show up. I haven't had time to dig into this more unfortunately.

**Comment by Furynation** [comment]
Just a follow up, I figured out why this was happening. There was a pool.rrd file which existed from backuppc 3:

root@zeus:/var/lib/backuppc/log# ls -l

srwxr-x--- 1 backuppc backuppc     0 Aug 13  2022 BackupPC.sock
-rw-r----- 1 backuppc backuppc     0 Jun 24 04:00 LOCK
-rw-r----- 1 backuppc backuppc  9407 Jun 24 11:00 LOG
**-rw-r--r-- 1 backuppc backuppc 11784 Aug 21  2022 pool.rrd**
-rw-rw-r-- 1 backuppc backuppc  6500 Jun 24 01:05 poolUsage4.png
-rw-rw-r-- 1 backuppc backuppc 10044 Jun 24 01:05 poolUsage52.png
-rw-r--r-- 1 backuppc backuppc 31112 Jun 24 01:05 poolUsage.rrd
-rw-r----- 1 backuppc backuppc 23452 Jun 24 11:00 status.pl
-rw-r----- 1 backuppc backuppc  1025 Jun 24 01:05 UserEmailInfo.pl

Removing the pool.rrd file took care of the issue.
