### ISSUE TITLE
Question regarding existing / new Files in BackupPC [3.3.0]

### ISSUE THREAD

**Issue by futureweb** [backuppc/backuppc#52]
Hello,

I'm backing up an old Centos Server with almost no running processes - today I noticed that according to " BackupPC File Size/Count Reuse Summary" it seems that about 1/3 of all Files on the Server are changed and get backuped again ... repeating every day.
As I don't believe that 1/3 of all Files on a Linux Server are changed on a daily base I ask myself if there is some sort of problem with my BackupPC Settings.

Screenshot "BackupPC File Size/Count Reuse Summary": http://temp.in.futureweb.at/backuppc.jpg

Any ideas on this? ;-)

Thank you, bye from Austria
Andreas

**Comment by craigbarratt** [comment]
First, git issues shouldn't be used for general user questions.

What is your XferMethod and client configuration?

The next step is to look in the log file for each backup and see which
files it is transferring during the incrementals.  You could also increase
the debug level if it's not clear why those files are being transferred.
Assuming things are working correctly, incrementals should only transfer a
file if some metadata (eg, mtime, permissions, file size etc) has changed.

Craig

**Comment by futureweb** [comment]
Hi Craig,

what would be the right Place for such Questions?
(I was not sure if the old Sourceforge List is still active as you moved here to GIT?! ;-)

I'm using RSYNC for backing up my Servers: $sshPath -c blowfish -C -q -x -l root $host $rsyncPath $argList+

Will increase verbosity of Logs - good idea! :)

Thank you, bye from sunny Austria
Andreas

**Comment by futureweb** [comment]
I tried an INC with higher verbosity ...

Running: /usr/bin/ssh -c blowfish -C -q -x -l root vzct329 /usr/bin/rsync --server --sender --numeric-ids --perms --owner --group -D --links --hard-links --times --block-size=2048 --recursive --checksum-seed=32761 . /pathCT329/priv/

Done: 24753 files, 148326065 bytes

create       7.716 
pool	           803
delete 	     20
same      23.795

Examples:
>   pool     644       0/0       29404 329/fs/root/usr/libexec/webmin/authentic-theme/extensions/sql.js
>   pool     644       0/0       19674 329/fs/root/usr/libexec/webmin/authentic-theme/extensions/sql.min.js
>   delete   644       0/0       28876 329/fs/root/usr/libexec/webmin/authentic-theme/extensions/csf.js
>   create d 755       0/0        4096 329/fs/root/usr/libexec/webmin/authentic-theme/help
>   pool     644       0/0        5554 329/fs/root/usr/libexec/webmin/authentic-theme/help/file-manager.html
>   delete   644       0/0        5406 329/fs/root/usr/libexec/webmin/authentic-theme/help/file-manager.ca.html
>   create d 755       0/0        4096 329/fs/root/usr/libexec/webmin/authentic-theme/images
>   pool     644       0/0          49 329/fs/root/usr/libexec/webmin/authentic-theme/images/_blank.gif
>   same     644       0/0         339 329/fs/root/usr/libexec/webmin/authentic-theme/images/after.gif
>   same     644       0/0         591 329/fs/root/usr/libexec/webmin/authentic-theme/images/attach.gif
>   same     644       0/0         340 329/fs/root/usr/libexec/webmin/authentic-theme/images/before.gif

Not quite sure what this tells me ... none of those files should have changed ... ?

Andreas

**Comment by futureweb** [comment]
just made a second inc - and same files have been backuped again:

first inc::
same     644       0/0         591 329/fs/root/usr/libexec/webmin/authentic-theme/images/attach.gif

second inc a few minutes after:
same     644       0/0         591 329/fs/root/usr/libexec/webmin/authentic-theme/images/attach.gif

**Comment by futureweb** [comment]
alright - unfortunately I was caught by  a mean thought mistake ... :-/
As the INC Backups are INCs from the last FULL - and not the INC before - it was always the same changed files since last full ... 
my bad - sorry! :-/

Andreas
