### ISSUE TITLE
Opensuse 42.1, 42.2 systemd startup script

### ISSUE THREAD

**Issue by keenick** [backuppc/backuppc#57]
Just updated my BPC to 4.0. Created this startup script for systemd as Opensuse uses systemd, and and init.d script was problematic with /var/run permissions. Not sure if this is the right spot to contribute to.
*Installed BackupPC from source, not from OpenSuSE repos*
Steps to install
1) Put .service file in /usr/lib/systemd/system/
2)As root do,
            "systemctl daemon-reload"
            "systemctl enable backuppc.service"  #should create a link in /etc/systemd/system/multi-         user.target.wants/backuppc.service
             "systemctl start backuppc.service"
            "systemctl status backuppc.service"

Script runs as backuppc : backuppc owner, group
/var/run/BackupPC folder created for .pid use from .configure.pl

Any improvements welcome, and is available from Yast: Service-Manager for start,stop,etc

`[Unit]
Description= BackupPC server
After=syslog.target 

[Service]
Type=oneshot
User=backuppc
Group=backuppc
PermissionsStartOnly=true
ExecStartPre=-/usr/bin/mkdir /var/run/BackupPC
ExecStartPre=/usr/bin/chown -R backuppc:backuppc /var/run/BackupPC/
ExecStart=/opt/BackupPC/bin/BackupPC -d
PIDFile=/var/run/BackupPC.pid
RemainAfterExit=yes
ExecStop=/usr/bin/kill -HUP  $MAINPID

[Install]
WantedBy=multi-user.target.`

**Comment by SpareSimian** [comment]
Should it have a dependency on the network being up? (I'm new to systemd so not sure how the dependencies work.) Or Apache being up? Or can it run without that?

**Comment by craigbarratt** [comment]
It would be great if some knowledgable folks could provide a portable
robust systemd solution I can include in the next release.

Craig

**Comment by jaccol** [comment]
For reference, this is the systemd file as found in CentOS/EPEL 7:

$ cat backuppc.service 
[Unit]
Description= BackupPC server
After=syslog.target local-fs.target remote-fs.target

[Service]
Type=oneshot
User=backuppc
Group=backuppc
ExecStart=/usr/share/BackupPC/bin/BackupPC -d
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

**Comment by keenick** [comment]
@SpareSimian -I dont use remotefs, I think adding that would make sense for  NFS, etc storage usage. as 
@jaccol's Centos script shows local-fs.target  @remote-fs.target

@craigbarratt  -would like to see also, as Opensuse init.d referance in Docs (init.d)

When configure.pl is run, the script suse-backuppc is created.

Using Suse 9.0 "chkconfig --level" doesn't work, so you should run:

    chkconfig backuppc 345
    chkconfig --list backuppc
Suse 9.0 is obviously very old and not supported.
Hopefully, 

@jaccol , I had issues with backuppc starting as backuppc has no rights to create the temp folder in /run, /var/run. I dont use Centos, not sure how the packagers are tackling that. systemd provides a way to create and then drops privileges after

Brought this up as maybe a feature request, and had luck rolling my own for now.

**Comment by jaccol** [comment]
At this time I only run BackupPC on CentOS6 (which has old init.d scripts).
That said, the old init.d script also does not have any commands for creating /var/run directories or changing their rights.
What I think that happens is that /var/run/BackupPC is present in the package with all the right rights. No need to fix that on every start.

**Comment by craigbarratt** [comment]
I renamed the init.d directory to systemd, added a template backuppc.service to git and updated the README file.  See https://github.com/backuppc/backuppc/tree/master/systemd.  The template service file is in https://github.com/backuppc/backuppc/blob/master/systemd/src/backuppc.service.

The old init.d files are still built by configure.pl, but they are put in a subdirectory.
