### ISSUE TITLE
Weird permissions on created files/directories

### ISSUE THREAD

**Issue by moisseev** [backuppc/backuppc#58]
Permission mask `$Conf{UmaskMode} = 23;`

As expected, BackupPC V3 creates directories and files with following permissions:
```
drwxr-x---  backuppc  backuppc
-rw-r-----  backuppc  backuppc
```

But BackupPC 4.0.0 creates files and directories in `cpool` with permissions ( permission mask is the same:`23`):
```
drwxrwxrwx  backuppc  backuppc
-r--r--r--  backuppc  backuppc
```
and some files in `cpool` and `pc` directories have
```
-r--r--r-x  backuppc  backuppc
```

**Comment by craigbarratt** [comment]
Alexander,

Thanks for pointing that out.  It looks like the umask is not propagating
into rsync_bpc.  I'll look into it.

The last example with o+x is normal.  I use that bit to flag a pool file
that has no references to it.  It will be removed from the pool 24 hours
later if there are still no references to it.

Craig

**Comment by moisseev** [comment]
Yes, all `o+x` files were deleted from `cpool` next day. But there are a lot of `o+x` files in `pc` directory as well. What does that flag mean for them? Is it v3 backups related somehow?

Negative group permissions are uncommon. So, there is enabled by default periodic script on FreeBSD `/etc/periodic/security/110.neggrpperm`. It adds a list of files with negative group permissions to daily security report. For BackupPC it's quite a big list.   It can be disabled by administrator, of course.

**Comment by craigbarratt** [comment]
Committed a fix; closing.
