### ISSUE TITLE
Modern styles for backend, website, logo

### ISSUE THREAD

**Issue by EquisTango** [backuppc/backuppc#63]
I'm willing to make some contributions, but before that I would like to know which of these would be considered for merge:

## General
1 Restyled logo (see attachment)

## Website
2 New styles using current content
3 Using third party libraries (like Bootstrap)
4 Link to CDN hosted resources (for third party libraries)

## Back-end
5 Responsive, HTML5 theme
6 Reorganizing or modifying content
7 Radically reorganizing or modifying content
8 Using third party libraries (like Bootstrap)

Restyled logo sample:

![logo320](https://cloud.githubusercontent.com/assets/5860683/23862819/c3e44a30-07ec-11e7-92f4-503d71b6700e.png)

Regards.

**Comment by craigbarratt** [comment]
Yes, I'm definitely supportive of contributions in these areas.   I definitely like the new logo!

It would be good to coordinate on some of your proposed changes.  As you know, a lot of the html is mixed in with the language files, which makes changing the html more work (the makeDist script does some sanity checking to make sure the html tags match between the different language files).  And compromising responsiveness with a lot of JS bloat wouldn't be a great tradeoff.

I look forward to seeing the progress in the areas you mention.

**Comment by moisseev** [comment]
[8] I am not confident about that. I mean bootstrap in particular. IMO current web interface implementation is very good. Some of its advantages are: it is lightweight, fast and compatible with almost every browser version. We will lose them all with bootstrap, I am afraid.

I am not against JS, but IMO it shouldn't be used too extensively. I wouldn't use JS unless it is absolutely necessary, i.e. to implement some really useful features that cannot be achieved with server side scripting only.

Some of that hypothetic features will require
[9] Provide API for JavaScript widgets (like a CGI action that returns JSON).

**Comment by EquisTango** [comment]
Ok, here is the proposed restyling for the website:
https://github.com/EquisTango/backuppc/tree/gh-pages

This is a simple refactoring of the original HTML, with minimum CSS and JavaScript. Download size is about the same as the current site.

The design is minimalist, responsive and should be very compatible (it's prepared for retina display but still looks quite acceptable on IE6).

I also uploaded updated screenshots.

No files where moved or renamed, so all current links remain valid.

If you think it's ok, I can create a PR.

**Comment by moisseev** [comment]
Great! Looks good.
(Indeed, I have disabled `Roboto` with AdBlock ;) Sorry.)

There is a minor bug: `Close` button removes itself instead of modal. `Esc` button works fine.

**Comment by EquisTango** [comment]
Ok, may I ask two questions, please:

1) What browser do you use (to check the close button problem)?
2) What do you think would be a sensible fallback for the Roboto font, besides the generic "sans-serif", if any? Something like Roboto -> {Liberation Sans|Carlito|other} -> sans-serif?

**Comment by jirkade** [comment]
IMHO sans-serif is the best fallback font, i.e., Roboto -> sans-serif. Sans-serif gets translated into the default font used in the desktop environment a user works with.

**Comment by moisseev** [comment]
1. User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:45.9) Gecko/20100101 Goanna/3.0 Firefox/45.9 PaleMoon/27.1.2
2. As @jirkade mentioned, for sans-serif I get Arial on my PC and it's prefect. Tahoma or Verdana would be fine as well.

**Comment by craigbarratt** [comment]
This looks great - nice work!

I'm happy to merge a PR when you are ready.

Craig

**Comment by EquisTango** [comment]
It's ready #72

**Comment by craigbarratt** [comment]
Thanks.  I merged the PR.  Closing this issue.

**Comment by craigbarratt** [comment]
In the config editor with multiple arrays it's hard to know where one setting ends and the next begins.  I'm attaching a screenshot.  I'm not sure adding a line between every entry makes sense - too much clutter especially for scalar settings.  Maybe valign'ing the parameter name so it is at the top of the table cell would be better?

![screen shot 2017-04-30 at 1 37 27 pm](https://cloud.githubusercontent.com/assets/19445341/25568058/b631cc9e-2daf-11e7-807e-b9b9de95074a.png)

@ngharo might have suggestions too.

**Comment by craigbarratt** [comment]
Here's how it looks with a vertical-align: top.

What's the best way to improve the delineation between different edit variables?

![screen shot 2017-04-30 at 2 26 16 pm](https://cloud.githubusercontent.com/assets/19445341/25568123/30712382-2db1-11e7-8772-ef90d06be561.png)

**Comment by moisseev** [comment]
I believe the solution is obvious:
```css
table, th, td {
    border: 1px solid black;
}
```

**Comment by craigbarratt** [comment]
Maybe "solid #dfdfdf" to match the other lines, and only apply it to the subtables in the config editor?  I'll need to add a class to those tables so the css can just be for that (rather than every table).

**Comment by craigbarratt** [comment]
Ok, this is how it looks adding a class="editSubTable" to the sub tables in the editor, and adding this to the css file.
```css
.editSubTable {
    border: 1px solid #dfdfdf;
}
```
Is everyone ok with this change, or do you prefer a better way?
![screen shot 2017-04-30 at 3 15 37 pm](https://cloud.githubusercontent.com/assets/19445341/25568464/3f3edeac-2db8-11e7-9de3-773169662511.png)

**Comment by moisseev** [comment]
Actually, I prefer `BackupPC_retro_v3.css` :)

Regarding the modern theme, I think applying borders to every table would be useful. Especially as tables in the modern theme are stretched all over the screen and columns are too wide. But if you want to avoid it, maybe something like `tr:nth-child(odd) {background: #some_color}` could improve tables readability.

**Comment by ngharo** [comment]
I'm not a huge fan of the 100% width input styles in the modern theme.  I can play around and post screen shots of some ideas later next week.
