### ISSUE TITLE
rsync_bpc - Unable to Read /var/lib/backuppc/pc/hostname/.rsyncdpw5754

### ISSUE THREAD

**Issue by SimonUtter** [backuppc/backuppc#65]
Operating system - Ubuntu server 16.04 LTS
BackupPC version: 4

This was initially a BackupPC v3 installation that was upgraded to version 4 for testing.
Installed using the tar in the release section, followed the configuration prompt/configuration wizard.

When starting a backup (xfer method rsyncd) I am constantly getting the following error:
Got fatal error during xfer (No files dumped for share backups)

When skimming through the logfile I noticed that it cant read a file that appears to be a rsync credentials file. The specific error was
`Unable to Read /var/lib/backuppc/pc/hostname/.rsyncdpw5754`

I Kicked of a primitive check to see if there was a file even created when the backup was started, so ran the following command:
`watch -n 0.1 cp .rsyncdpw* rsyncpw.bak`
The credentials file was created, but seems like it only appeared for a fraction of a second (Not sure if this is desired behavior, or if the file should stay accessible until rsyncd transfer has started).
The file appears to be empty.

I have a per host configuration that specifies the rsyncd username and password, so just tested to add a global set of credentials and set the default xfer method to rsyncd.

Did the same thing, keept a lookout for the credentials file using the same watch command as above, and now the file appears to have the stored password in it.

However, I am still getting the same error in the error log for all rsyncd hosts, "Unable to Read /var/lib/backuppc/pc/hostname/.rsyncdpw<numberplaceholder>".

**Comment by craigbarratt** [comment]
This is a mystery.  Yes, the rsyncdpw file should get created before rsync_bpc starts, and it shouldn't get deleted until after it finishes.

The "Unable to Read" error is strange.  That text doesn't appear in the rsync source code.  The error it prints if it fails to open the password file is:

    could not open password file %s

I tried creating a new rsyncd host and it backs up fine for me.

Can you try running BackupPC_dump with the -v option (as the BackupPC user), and email me the output?

    BackupPC_dump -v -h HOSTNAME

Craig

**Comment by craigbarratt** [comment]
Simon,

Any update on this?  I hope to release 4.1 soon, and it would be great to get this resolved.

Craig

**Comment by SimonUtter** [comment]
Hi Craig, sorry for the delay. 

Below is the output from the command as requested.
I have sanitized the data in the log, and  replaced the hostname and usernames with some ,< > as placeholders, and also remove the output from the precommand (just a powershell script).

`Backup type: type = full, needs_full = 1, needs_incr = 1, lastFullTime = 1488272781, opts{f} = , opts{i} = , opts{F} = 
cmdSystemOrEval: about to system /bin/ping -c 1 172.21.24.130
cmdSystemOrEval: about to system /bin/ping -c 1 172.21.24.130
CheckHostAlive: returning 0.116
XferLOG file /var/lib/backuppc/pc/<HostnamePlaceholder>/XferLOG.5.z created 2017-03-16 16:22:55 
Backup prep: type = full, case = 6, inPlace = 1, doDuplicate = 0, newBkupNum = 5, newBkupIdx = 2, lastBkupNum = , lastBkupIdx =  (FillCycle = 0, noFillCnt = 1)
__bpc_progress_state__ pre-cmd
Executing DumpPreUserCmd: /etc/backuppc/preUserSSH_powershell.sh -i 172.21.24.130 -h <HostnamePlaceholder>
cmdSystemOrEval: about to system /etc/backuppc/preUserSSH_powershell.sh -i 172.21.24.130 -h <HostnamePlaceholder>
UNAME= BackupPC
warning: commands will be executed using /bin/sh
job 352 at Thu Mar 16 16:22:00 2017
Warning: Permanently added '172.21.24.130' (ECDSA) to the list of known hosts.
2017-03-16-16:23:07 Primary - Pre-cmd.ps1 Script now finished
__bpc_progress_state__ backup C
Running: /usr/local/bin/rsync_bpc --bpc-top-dir /var/lib/backuppc --bpc-host-name <HostnamePlaceholder> --bpc-share-name C --bpc-bkup-num 5 --bpc-bkup-comp 1 --bpc-bkup-prevnum -1 --bpc-bkup-prevcomp -1 --bpc-bkup-inode0 12440 --bpc-attrib-new --bpc-log-level 6 --super --recursive --protect-args --numeric-ids --perms --owner --group -D --times --links --hard-links --delete --partial --log-format=log: %o %i %B %8U,%8G %9l %f%L --stats -vvv --checksum --iconv=utf8,cp1252 --password-file=/var/lib/backuppc/pc/<HostnamePlaceholder>/.rsyncdpw2676 --include=/Projects --include=/Users --include=/Users/<UserName> --include=/Users/<UserName>/Documents --include=/Users/<UserName>/App --include=/Users/<UserName>/App/Data --include=/Users/<UserName>/App/Data/Roaming --include=/Users/<UserName>/App/Data/Roaming/Microsoft --include=/Users/<UserName>/App/Data/Roaming/Microsoft/Outlook --include=/Users/<UserName>/AppData --include=/Users/<UserName>/AppData/Roaming --include=/Users/<UserName>/AppData/Roaming/Mozilla --include=/Users/<UserName>/AppData/Roaming/Mozilla/Firefox --include=/Users/<UserName>/AppData/Roaming/Mozilla/Firefox/Profiles --include=/Users/<UserName>/AppData/Roaming/Mozilla/Firefox/Profiles/bo45vxve.default --exclude=/* --exclude=/Users/* --exclude=/Users/<UserName>/* --exclude=/Users/<UserName>/App/* --exclude=/Users/<UserName>/App/Data/* --exclude=/Users/<UserName>/App/Data/Roaming/* --exclude=/Users/<UserName>/App/Data/Roaming/Microsoft/* --exclude=/Users/<UserName>/AppData/* --exclude=/Users/<UserName>/AppData/Roaming/* --exclude=/Users/<UserName>/AppData/Roaming/Mozilla/* --exclude=/Users/<UserName>/AppData/Roaming/Mozilla/Firefox/* --exclude=/Users/<UserName>/AppData/Roaming/Mozilla/Firefox/Profiles/* --exclude=/Projects/Temp/ BackupPCadmin@172.21.24.130::C /
full backup started for directory C
started full dump, share=C
Xfer PIDs are now 2705
xferPids 2705
This is the rsync child about to exec /usr/local/bin/rsync_bpc
cmdExecOrEval: about to exec /usr/local/bin/rsync_bpc --bpc-top-dir /var/lib/backuppc --bpc-host-name <HostnamePlaceholder> --bpc-share-name C --bpc-bkup-num 5 --bpc-bkup-comp 1 --bpc-bkup-prevnum -1 --bpc-bkup-prevcomp -1 --bpc-bkup-inode0 12440 --bpc-attrib-new --bpc-log-level 6 --super --recursive --protect-args --numeric-ids --perms --owner --group -D --times --links --hard-links --delete --partial --log-format=log:\ %o\ %i\ %B\ %8U,%8G\ %9l\ %f%L --stats -vvv --checksum --iconv=utf8,cp1252 --password-file=/var/lib/backuppc/pc/<HostnamePlaceholder>/.rsyncdpw2676 --include=/Projects --include=/Users --include=/Users/<UserName> --include=/Users/<UserName>/Documents --include=/Users/<UserName>/App --include=/Users/<UserName>/App/Data --include=/Users/<UserName>/App/Data/Roaming --include=/Users/<UserName>/App/Data/Roaming/Microsoft --include=/Users/<UserName>/App/Data/Roaming/Microsoft/Outlook --include=/Users/<UserName>/AppData --include=/Users/<UserName>/AppData/Roaming --include=/Users/<UserName>/AppData/Roaming/Mozilla --include=/Users/<UserName>/AppData/Roaming/Mozilla/Firefox --include=/Users/<UserName>/AppData/Roaming/Mozilla/Firefox/Profiles --include=/Users/<UserName>/AppData/Roaming/Mozilla/Firefox/Profiles/bo45vxve.default --exclude=/\* --exclude=/Users/\* --exclude=/Users/<UserName>/\* --exclude=/Users/<UserName>/App/\* --exclude=/Users/<UserName>/App/Data/\* --exclude=/Users/<UserName>/App/Data/Roaming/\* --exclude=/Users/<UserName>/App/Data/Roaming/Microsoft/\* --exclude=/Users/<UserName>/AppData/\* --exclude=/Users/<UserName>/AppData/Roaming/\* --exclude=/Users/<UserName>/AppData/Roaming/Mozilla/\* --exclude=/Users/<UserName>/AppData/Roaming/Mozilla/Firefox/\* --exclude=/Users/<UserName>/AppData/Roaming/Mozilla/Firefox/Profiles/\* --exclude=/Projects/Temp/ BackupPCadmin@172.21.24.130::C /
[client] add_rule(+ /Projects)
[client] add_rule(+ /Users)
[client] add_rule(+ /Users/<UserName>)
[client] add_rule(+ /Users/<UserName>/Documents)
[client] add_rule(+ /Users/<UserName>/App)
[client] add_rule(+ /Users/<UserName>/App/Data)
[client] add_rule(+ /Users/<UserName>/App/Data/Roaming)
[client] add_rule(+ /Users/<UserName>/App/Data/Roaming/Microsoft)
[client] add_rule(+ /Users/<UserName>/App/Data/Roaming/Microsoft/Outlook)
[client] add_rule(+ /Users/<UserName>/AppData)
[client] add_rule(+ /Users/<UserName>/AppData/Roaming)
[client] add_rule(+ /Users/<UserName>/AppData/Roaming/Mozilla)
[client] add_rule(+ /Users/<UserName>/AppData/Roaming/Mozilla/Firefox)
[client] add_rule(+ /Users/<UserName>/AppData/Roaming/Mozilla/Firefox/Profiles)
[client] add_rule(+ /Users/<UserName>/AppData/Roaming/Mozilla/Firefox/Profiles/bo45vxve.default)
[client] add_rule(- /*)
[client] add_rule(- /Users/*)
[client] add_rule(- /Users/<UserName>/*)
[client] add_rule(- /Users/<UserName>/App/*)
[client] add_rule(- /Users/<UserName>/App/Data/*)
[client] add_rule(- /Users/<UserName>/App/Data/Roaming/*)
[client] add_rule(- /Users/<UserName>/App/Data/Roaming/Microsoft/*)
[client] add_rule(- /Users/<UserName>/AppData/*)
[client] add_rule(- /Users/<UserName>/AppData/Roaming/*)
[client] add_rule(- /Users/<UserName>/AppData/Roaming/Mozilla/*)
[client] add_rule(- /Users/<UserName>/AppData/Roaming/Mozilla/Firefox/*)
[client] add_rule(- /Users/<UserName>/AppData/Roaming/Mozilla/Firefox/Profiles/*)
[client] add_rule(- /Projects/Temp/)
bpc_path_create(/var/lib/backuppc/pc/<HostnamePlaceholder>/5)
bpc_attrib_backwardCompat: WriteOldStyleAttribFile = 0, KeepOldAttribFiles = 0
opening tcp connection to 172.21.24.130 port 873
Connected to 172.21.24.130 (172.21.24.130)
client charset: utf8
sending daemon args: --server --sender -svvvlHogDtprce.iLsf --iconv=utf8 
protected args: --numeric-ids . C/ 
receiving incremental file list
rsync_bpc: read error: Connection reset by peer (104)
bpc_sysCall_cleanup: doneInit = 1
RefCnt Deltas for new backup
Uncompressed HT:
Compressed HT:
Done: 0 errors, 0 filesExist, 0 sizeExist, 0 sizeExistComp, 0 filesTotal, 0 sizeTotal, 0 filesNew, 0 sizeNew, 0 sizeNewComp, 12440 inode
Parsing done: nFilesTotal = 0
rsync error: error in rsync protocol data stream (code 12) at io.c(788) [Receiver=3.0.9.5]
[Receiver] _exit_cleanup(code=12, file=io.c, line=788): about to call exit(12)
rsync_bpc exited with fatal status 12 (3072) (rsync error: error in rsync protocol data stream (code 12) at io.c(788) [Receiver=3.0.9.5])
Xfer PIDs are now 
xferPids 
__bpc_progress_state__ post-cmd
Executing DumpPostUserCmd: /etc/backuppc/postuserSSH.sh 172.21.24.130
cmdSystemOrEval: about to system /etc/backuppc/postuserSSH.sh 172.21.24.130
Warning: Permanently added '172.21.24.130' (ECDSA) to the list of known hosts.
Rsync and shadow copy unloaded
Got fatal error during xfer (No files dumped for share C)
cmdSystemOrEval: about to system /bin/ping -c 1 172.21.24.130
cmdSystemOrEval: about to system /bin/ping -c 1 172.21.24.130
CheckHostAlive: returning 0.133
Backup aborted (No files dumped for share C)
__bpc_progress_state__ fail cleanup
BackupFailCleanup: nFilesTotal = 0, type = full, BackupCase = 6, inPlace = 1, lastBkupNum = 
BackupFailCleanup: inPlace with no new files... no cleanup
__bpc_progress_state__ fsck
Running BackupPC_refCountUpdate -h <HostnamePlaceholder> -f on <HostnamePlaceholder>
cmdSystemOrEval: about to system /usr/share/backuppc/bin/BackupPC_refCountUpdate -h <HostnamePlaceholder> -f
Xfer PIDs are now 2710
xferPids 2710
BackupPC_refCountUpdate: host <HostnamePlaceholder> #5: gotFsck = 1, gotDelta = , gotPoolCnt = 1, gotNoPoolCntOk = 
BackupPC_refCountUpdate: processing host <HostnamePlaceholder> #5 (fsck = 1)
__bpc_progress_state__ refCnt #5
__bpc_progress_state__ cntUpdate #5
BackupPC_refCountUpdate: processing host <HostnamePlaceholder> #5 deltaFile /var/lib/backuppc/pc/<HostnamePlaceholder>/5/refCnt/poolCntDelta_1_0_0_2710 with 11437 entries
__bpc_progress_state__ rename #5
BackupPC_refCountUpdate: computing totals for host <HostnamePlaceholder>
__bpc_progress_state__ sumUpdate 0/128
__bpc_progress_state__ sumUpdate 8/128
__bpc_progress_state__ sumUpdate 16/128
__bpc_progress_state__ sumUpdate 24/128
__bpc_progress_state__ sumUpdate 32/128
__bpc_progress_state__ sumUpdate 40/128
__bpc_progress_state__ sumUpdate 48/128
__bpc_progress_state__ sumUpdate 56/128
__bpc_progress_state__ sumUpdate 64/128
__bpc_progress_state__ sumUpdate 72/128
__bpc_progress_state__ sumUpdate 80/128
__bpc_progress_state__ sumUpdate 88/128
__bpc_progress_state__ sumUpdate 96/128
__bpc_progress_state__ sumUpdate 104/128
__bpc_progress_state__ sumUpdate 112/128
__bpc_progress_state__ sumUpdate 120/128
__bpc_progress_state__ rename total
BackupPC_refCountUpdate: host <HostnamePlaceholder> got 0 errors (took 0 secs)
BackupPC_refCountUpdate total errors: 0
Xfer PIDs are now 
xferPids 
Finished BackupPC_refCountUpdate (running time: 0 sec)
Xfer PIDs are now 
xferPids 
dump failed: No files dumped for share C`

**Comment by craigbarratt** [comment]
Thanks for the log.  Feel free to delete the link, and just email me the log files directly (not the backuppc-user list).

This log shows that it does connect successfully to the rsyncd server, but fails soon after.  I don't see the error about failing to read the rsyncdpw file.

What version of rsyncd are you running on the backup client (which appears to be a windows machine)?

**Comment by craigbarratt** [comment]
Is there any rsync log output on the client machine?  Can you run it manually and see if it produces any output?

What happens when you manually telnet to your host port 873, eg:

    telnet 172.21.24.130:873

It should respond with a version number, like this

    @RSYNCD: 30.0

Try typing the same thing back:

    @RSYNCD: 30.0

Then you have to enter the module name, which appears to be "C":

    C

It will respond with an auth request, like this:

    @RSYNCD: AUTHREQD wjp2Ep/hPBQTw65PPix0Rg

Do you see something like that?

**Comment by SimonUtter** [comment]
Hi Craig, I've just started up the test server with the backuppc4 installation on.
Will have another go and confirm the details above (and provide more detailed logs).

Where can I find your email address?

**Comment by craigbarratt** [comment]
cbarratt@users.sourceforge.net

**Comment by craigbarratt** [comment]
The likely cause of this error is an empty or missing $Conf{RsyncdPasswd} setting.

**Comment by craigbarratt** [comment]
Simon confirmed that was the issue - an empty $Conf{RsyncdPasswd} setting.

4.1.0 includes a new check that prints a clear error message if $Conf{RsyncdPasswd} is empty.
