### ISSUE TITLE
backuppc 4.x on Gentoo

### ISSUE THREAD

**Issue by sigmoidal** [backuppc/backuppc#66]
The introduction of makeDist has made using the BackupPC from git complicated on gentoo. 
It seems to be mandatory now, or is there an option to skip its use and carry on using the top-level source tree?

It also appears that the openrc init scripts have been moved into the systemd folder.

Any help would be great. thx.

**Comment by craigbarratt** [comment]
makeDist dates back to 2.x.  It's never been intended to install/run BackupPC directly from the source tree.  There are just too many paths etc in git that won't match your setup.  makeDist creates a clean installation tree and tarball, and configure.pl then modifies it for your target.

Craig
