### ISSUE TITLE
DumpPreShareCmd error, but I haven't set DumpPreShareCmd!

### ISSUE THREAD

**Issue by stirab** [backuppc/backuppc#67]
Hello, after upgrade to v 4 many of the server I backup generate an error like this:
`DumpPreShareCmd returned error status 0... exiting`
**but I haven't set any DumpPreShareCmd in the configuration file!**

So I run BackupPC_dump from command line, under perl debugger. The function `UserCommandRun` is called for each directory to backup:
line 904 of BackupPC_dump:
`UserCommandRun("DumpPreShareCmd", $shareName);`
`    if ( $? && $Conf{UserCmdCheckStatus} ) {`

The first time '$?' is 0, but the second time '$?' is '-1' and the if condition become true, and the error is generated:

`DB<10> n`
`main::(/usr/local/BackupPC/bin/BackupPC_dump:905):`
`905:	    if ( $? && $Conf{UserCmdCheckStatus} ) {`
`DB<10> p $?`
`-1`

I've no idea why this happen, however I've changed the above code this way:
`my $UCR_ret = UserCommandRun("DumpPreShareCmd", $shareName);`
`if ( $UCR_ret && $Conf{UserCmdCheckStatus} ) {`
and now it works.

This is the config file for the server to backup:
`$Conf{XferMethod} = 'rsync';`
`$Conf{RsyncShareName} = ['/etc', '/opt', '/root', '/home/jboss', '/var/www'];`
`#$Conf{BackupFilesExclude} = ['/home/share/dogana', 'dogana/'];`
`$Conf{UserCmdCheckStatus} = 1;`
`$Conf{DumpPostUserCmd} = '$sshPath -q -x -l root drpcbatman /root/ReverseDRBackup.sh amelia64 /etc /opt /root /home/jboss /var/www';`

And from /etc/BackupPC/config.pl:
`$Conf{DumpPreShareCmd}    = undef;`
...
`  'DumpPostShareCmd' => 0,`

**Comment by craigbarratt** [comment]
Thanks for catching this.  I fixed it in a slightly different way - setting $? = 0 at the top of UserCommandRun().

Fixed in both master and 3.x.x.
