### ISSUE TITLE
Gentoo BPC package

### ISSUE THREAD

**Issue by sigmoidal** [backuppc/backuppc#70]
I am working on providing a good working BPC 4.x ebuild package for Gentoo (it is currently not available upstream) at:
```
https://github.com/sigmoidal/gentoo-overlay (overlay installation and usage instruction enclosed)
```

app-backuppc/backuppc/backuppc-9999.ebuild pulls the source of git master, so it's nice for testing bleeding edge BPC 4.x on gentoo, while app-backuppc/backuppc/backuppc-4.0.0-r1.ebuild is for the respective BPC version.

It works fine for me, but I am still improving it (have to add some dependencies), some users may find it useful. Note, that I have also created ebuilds for BackupPC::XS and rsync_bpc dependencies (also in that overlay), so when one emerges backuppc with dependencies (emerge -Dva backuppc) it emerges them also, as expected.

I will improve the BPC ebuild to take into account all dependencies and runtime-dependencies, so any feedback would be useful and I will be pushing it to upstream once it is ready.

**Comment by craigbarratt** [comment]
FYI, there's also this script on the Wiki that gives all the command-line
steps to install BackupPC master on Ubuntu 16.04:

https://github.com/backuppc/backuppc/wiki/Installing-
BackupPC-4-from-git-on-Ubuntu-Xenial-16.04-LTS


Craig

**Comment by sigmoidal** [comment]
Thanks. The ebuilds do most of these steps. Should we move this "issue" to the wiki? What do you think?

**Comment by craigbarratt** [comment]
If it's a set of instructions or documentation about how to configure/run
BackupPC, then yes, the Wiki would be the best place.

Craig
