### ISSUE TITLE
BackupPC_migrateV3toV4 bug?

### ISSUE THREAD

**Issue by spikebike** [backuppc/backuppc#71]
Possible that BackupPC_migrateV3toV4 has a path length limitation?

I'm migrating a V3 install to a V4 install with the above tool and:
BackupPC_migrateV3toV4: can't read attribute file ./f%2fnas-9-0BKUP/fapps/fspark-1.6.1/fexternal/fmqtt-assembly/ftarget/fstreams/f$global/fassemblyOption/f$global/fstreams/fassembly/f36991b4b5e0678f822e8fcc31508b5195f304c47_0fec8066cd2b4f8dc7ff7ba7a8e0a792939d9f9a/fscala/ftools/fnsc/fmatching/attrib
bpc_attrib_dirRead: got unreasonable file name length 572626

**Comment by craigbarratt** [comment]
Bill,

It looks like a corrupted old attrib file.  When the file is read, it finds
a file name length of 572626, which is definitely an error (typically the
max pathname length is 4096).

BackupPC_migrateV3toV4 should still create a sensible attrib file by
ignoring the corrupted attrib file and extracting the file sizes etc from
the (hardlinked) files in the directory.  Some meta data might not be
correct (eg, mtime).  You should confirm that's the case.

Craig

**Comment by spikebike** [comment]
Indeed the migration seems to be handling them fine, and I did verify that the new attrib files seem to work.

Thanks, I think this issue can be closed.
