### ISSUE TITLE
BackupPC_migrateV3toV4 missing and crashes

### ISSUE THREAD

**Issue by spikebike** [backuppc/backuppc#75]
I downloaded the 4.01 release (.tar.gz) and BackupPC_migrateV3toV4 is missing.

I downloaded the source release and it was there, not sure if that was intentional.

I launched the migrate tool on a 2.5TB pool I had around, it did a dozen hosts or so with a dozen backups each without problems.

Then:

forward.<snip> #1473: 99.9%
forward.<snip> #1473: 100.0%
BackupPC_migrateV3toV4: converted backup in /var/lib/backuppc/pc/forward.<snip>/1473; removing /var/lib/backuppc/pc/forward.<snip>/1473.old
BackupPC_migrateV3toV4: migrating host forward.<snip> backup #1474 to V4 (approx 0 files)
Illegal division by zero at /usr/share/backuppc/bin/BackupPC_migrateV3toV4 line 508.

**Comment by spikebike** [comment]
So it's a divide by zero on  $FileCntTotal, but the weird thing is I deleted that backup, so now it dies on #1475 and I'm in backuppc/pc/forward.geology.ucdavis.edu/1475/ and:

backuppc@fs1:~/pc/forward/1475$ find . -type f | wc -l
50
backuppc@fs1:~/pc/forward/1475$ cd ../1475.v4/
backuppc@fs1:~/pc/forward/1475.v4$ find . -type f | wc -l
209
backuppc@fs1:~/pc/forward/1475.v4$

**Comment by craigbarratt** [comment]
Oops, you found two bugs.  I've added BackupPC_migrateV3toV4 to makeDist (efc862dc8e3daf2a802c3439babb3b14f17706e1) and ensured that $FileCntTotal is >= 1 when the division occurs (34f1e517663ef790e9c6a14f39ee7cd5952cfc2d).

If you specify the -p flag that will avoid the divide-by-zero error.

In your find test, you might just be finding attrib files, that will still be present even if the file count is zero.

**Comment by craigbarratt** [comment]
Fixed in 4.1.1.
