### ISSUE TITLE
configure.pl --config-only issue(s): can't open [...]/etc/backuppc/hosts.sample for reading

### ISSUE THREAD

**Issue by raoulbhatia** [backuppc/backuppc#76]
Hi!

I am trying to automate the build-process with the ultimate goal of creating Debian packages.

Current issue:
`can't open /home/raoul/git/raoulbhatia/bpc/backuppc/debian/backuppc//etc/backuppc/hosts.sample for reading`

Steps to reproduce:
```
./makeDist --releasedate "`date +'%d %b %Y'`" --version "4.1.0"
cd ./dist/BackupPC-4.1.0/
./configure.pl --config-only --batch --no-fhs --uid-ignore --hostname XXXXXX \
		--bin-path perl=/usr/bin/perl \
		--bin-path tar=/bin/tar \
		--bin-path smbclient=/usr/bin/smbclient \
		--bin-path nmblookup=/usr/bin/nmblookup \
		--bin-path rsync=/usr/bin/rsync \
		--bin-path ping=/bin/ping \
		--bin-path df=/bin/df \
		--bin-path ssh=/usr/bin/ssh \
		--bin-path sendmail=/usr/sbin/sendmail \
		--bin-path hostname=/bin/hostname \
		--bin-path split=/usr/bin/split \
		--bin-path par2=/usr/bin/par2 \
		--bin-path cat=/bin/cat \
		--bin-path gzip=/bin/gzip \
		--bin-path bzip2=/bin/bzip2 \
		--config-dir /etc/backuppc \
		--cgi-dir /usr/share/backuppc/cgi-bin \
		--data-dir /var/lib/backuppc \
		--dest-dir /home/raoul/git/raoulbhatia/bpc/backuppc/debian/backuppc/ \
		--html-dir /usr/share/backuppc/image \
		--html-dir-url /backuppc/image \
		--install-dir /usr/share/backuppc;
```

Thanks,
Raoul

**Comment by moisseev** [comment]
`--config-only` shouldn't be used at build time. It is intended to create or update `config.pl` when the package is already installed. Basically `--config-only` option tells `configure.pl` to skip installation.

[Here](https://github.com/backuppc/backuppc/pull/62) you can find more detailed explanation that probably is not clear enough as I am not good with English and explanations. So if you still have questions feel free to ask.
