### ISSUE TITLE
rsync error: error in rsync protocol data stream

### ISSUE THREAD

**Issue by thomasgg23** [backuppc/backuppc#84]
Don't know if it is a bug or just some misconfiguration.

When trying to backup a Ubuntu 12.04 LTS Server (tried with full/incremental) all of the backup will quit with the following message.

rsync error: error in rsync protocol data stream
More logs in the end. 

Is there a way to get more debug data?
By the way 10 other machines just runs fine on the same backuppc server.

The backuppc server setup is Ubuntu 16.04 LTS, 4.1.1 backuppc, BackupPC-XS 0.53 and rsync-bpc 3.0.9.6.

XferLOG file /data/BackupPC/pc/192.168.0.109/XferLOG.309.z created 2017-03-28 18:23:57 
Backup prep: type = full, case = 2, inPlace = 1, doDuplicate = 1, newBkupNum = 309, newBkupIdx = 15, lastBkupNum = , lastBkupIdx =  (FillCycle = 0, noFillCnt = 2)
Executing /usr/local/BackupPC/bin/BackupPC_backupDuplicate -h 192.168.0.109
Xfer PIDs are now 4604
Copying v3 backup #304 to v4 #309
bpc_attrib_dirRead: got unreasonable file name length 1048962
bpc_attrib_dirRead: got unreasonable file name length 42999431
setVarInt botch: got negative argument -1275054303; setting to 0
setVarInt botch: got negative argument -2108928000; setting to 0
setVarInt botch: got negative argument -2105343864; setting to 0
Xfer PIDs are now 4604,5565
BackupPC_refCountUpdate: doing fsck on 192.168.0.109 #309 since there are no poolCnt files
BackupPC_refCountUpdate: host 192.168.0.109 got 0 errors (took 216 secs)
Xfer PIDs are now 4604
BackupPC_backupDuplicate: got 0 errors and 0 file open errors
Finished BackupPC_backupDuplicate (running time: 19529 sec)
Running: /usr/local/bin/rsync_bpc --bpc-top-dir /data/BackupPC --bpc-host-name 192.168.0.109 --bpc-share-name / --bpc-bkup-num 309 --bpc-bkup-comp 3 --bpc-bkup-prevnum -1 --bpc-bkup-prevcomp -1 --bpc-bkup-inode0 905048 --bpc-attrib-new --bpc-log-level 1 -e /usr/bin/ssh\ -l\ root --rsync-path=/usr/bin/rsync --super --recursive --protect-args --numeric-ids --perms --owner --group -D --times --links --hard-links --delete --partial --log-format=log:\ %o\ %i\ %B\ %8U,%8G\ %9l\ %f%L --stats --checksum --exclude=/dev --exclude=/lost+found --exclude=/media --exclude=/mount --exclude=/proc --exclude=/run --exclude=/sys --exclude=/bin --exclude=/lib --exclude=/mnt --exclude=/sbin --exclude=/tmp --exclude=/var/cache --exclude=/var/log --exclude=/var/tmp --exclude=/images --exclude=/var/lib/dhcp/proc --exclude=/var/lib/named/proc --exclude=/var/spool --exclude=/usr/src --exclude=/var/lib/amavis/virusmails --exclude=/var/lib/dpkg --exclude=/var/lib/mysql 192.168.0.109:/ /
full backup started for directory /
Xfer PIDs are now 5579
This is the rsync child about to exec /usr/local/bin/rsync_bpc
Xfer PIDs are now 5579,5581
xferPids 5579,5581

...Backup run...

rsync_bpc: writefd_unbuffered failed to write 8 bytes to message fd [receiver]: Broken pipe (32)
Done: 0 errors, 4 filesExist, 728454 sizeExist, 134801 sizeExistComp, 0 filesTotal, 0 sizeTotal, 425 filesNew, 1507666699 sizeNew, 1002792794 sizeNewComp, 905843 inode
rsync error: error in rsync protocol data stream (code 12) at io.c(1556) [receiver=3.0.9.6]
rsync_bpc exited with fatal status 0 (11) (rsync error: error in rsync protocol data stream (code 12) at io.c(1556) [receiver=3.0.9.6])
Xfer PIDs are now 
Got fatal error during xfer (No files dumped for share /)
Backup aborted (No files dumped for share /)
BackupFailCleanup: nFilesTotal = 0, type = full, BackupCase = 6, inPlace = 1, lastBkupNum = 
BackupFailCleanup: inPlace with no new files... no cleanup
Running BackupPC_refCountUpdate -h 192.168.0.109 -f on 192.168.0.109
Xfer PIDs are now 19333
BackupPC_refCountUpdate: host 192.168.0.109 got 0 errors (took 63 secs)
Xfer PIDs are now 
Finished BackupPC_refCountUpdate (running time: 63 sec)
Xfer PIDs are now

**Comment by craigbarratt** [comment]
Not sure what the problem is.  It appears some files do get transferred before it fails, so ssh authorization doesn't appear to be a problem.

Is there anything about the client that is different from the ones that work (rsync version etc)?

Could you re-run with a setting of $Conf{XferLogLevel} = 7?  The file will be quite large; please send it directly to me (cbarratt@users.sourceforge.net) rather than on git or the email list.  I'd like to see the first ~200 and last ~200 lines or so (it's important to get the last few lines that start with R and G) if you want to redact most of the lines.  But seeing the whole log file would be best if you are ok.

**Comment by johanehnberg** [comment]
I am also seeing this on BackupPC 4.1.2, BackupPC-XS 0.53 and rsync-bpc 3.0.9.6. In the same environment there is a BackupPC pre-4.0.0, BackupPC-XS 0.40 and rsync-bpc 3.0.9.4 backing up the same hosts just fine. Both instances run on Ubuntu 16.04 LTS but on different hardware.

I made a log available to Craig by email.

Let me know if there are any specific versions or commits to test, our automated deployment should be fairly easy to tweak to bisect this rapidly if it is indeed introduced between said versions.

**Comment by johanehnberg** [comment]
It would seem the first full (#0) runs fine, and most subsequent fulls or incrementals fail with the error.

**Comment by johanehnberg** [comment]
Running without --one-file-system also fails.
If I remove (backupDelete) the failed backup, the next one still fails.
If I remove the first (i.e. all) backup, the new full (#0) again succeeds.

**Comment by thomasgg23** [comment]
Sorry for the late response.
For me it worked when I deleted the whole client and did a fresh backup.
Sorry I know that this is no answer for the problem but for me it worked.

**Comment by thomasgg23** [comment]
Perhaps @johanehnberg could delete the client too and check if the backup still fails or works. Perhaps something went wrong with the update to 4.1.2

**Comment by johanehnberg** [comment]
@thomasgg23 this is a fresh install on a fresh cloud image. I tested also deleting the host as you suggested. The outcome did not change.

**Comment by johanehnberg** [comment]
Some background that may be of importance: the instance is running in LXD and uses ZFS for all storage. It's a privileged container so cgroups issues should not be at play. ZFS has compression turned on, and BackupPC has compression turned off (uses pool rather than cpool).

**Comment by johanehnberg** [comment]
Interestingly, turning compression on in BackupPC allows for another backup to complete but after that it fails as before.

I.e. the list shows
#0 full (success, compression 0)
#1 partial (fail, compression 0)
#2 full (success, compression 3)
#3 partial (fail, compression 3).

Moving back and forth like this seems to succeed, at least #4 full was a success with compression 0 again.

**Comment by johanehnberg** [comment]
@thomasgg23 are you using rsync compression? I noticed that is the trigger in my case, but I don't see it in your arguments list. Our cases may be different.

**Comment by johanehnberg** [comment]
The trigger is definitely in --compress in RsyncArgs in my case. Without that it completes fine. As a less flexible alternative (no levels), compression can of course be added to RsyncSshArgs instead.

**Comment by thomasgg23** [comment]
@johanehnberg You are right I don't use compression via RsyncArgs

**Comment by thomasgg23** [comment]
@johanehnberg Should we close this issue? Something for the FAQ?

**Comment by johanehnberg** [comment]
We are working on the compression case with Craig. If it needs further tracking I can open a new issue for it. Since your case is likely different although the error is the same, you decide.

**Comment by thomasgg23** [comment]
My error is gone with the removing of the prior backup. 
Since the other backups (v3 to v4) didn't show the error, I'll close this bug.

**Comment by jej** [comment]
I had the same problem with the last version of BackupPC (version 4.1.5)

`Backup aborted (rsync error: error in rsync protocol data stream...)`

I resolved the problem with the given advice above, by removing the "--compress" argument.

Hope it helps!
