### ISSUE TITLE
Strange behavior with delete

### ISSUE THREAD

**Issue by AlexeySaff** [backuppc/backuppc#87]
Have BackupPC 3.x after upgrade move some PC backup to V4 format (by doing fullbackup). After that i delete some directories on My PC, create incr backup (still see that folders in latest backup). Then try create full backup (this folders still persist).

**Comment by craigbarratt** [comment]
What is your XferMethod?

**Comment by AlexeySaff** [comment]
rsync

2017-04-02 21:57 GMT+03:00 Craig Barratt <notifications@github.com>:

**Comment by craigbarratt** [comment]
What is $Conf{RsyncArgs} set to?

Please email me a log file with $Conf{XferLogLevel} set to 6, and tell me which files/directories are not present on your PC.

**Comment by AlexeySaff** [comment]
sorry for long delay. it's strange as i check old logs there are no
permissions issue
we add rbackup user to sudoers for /usr/bin/rsync

but in new version we have some permission issues

XferLOG file /mnt/backuppc/pc/ltspc162/XferLOG.151.z created
2017-04-10 16:19:05
Backup prep: type = incr, case = 4, inPlace = 0, doDuplicate = 0,
newBkupNum = 151, newBkupIdx = 14, lastBkupNum = 150, lastBkupIdx = 13
(FillCycle = 0, noFillCnt = 0)
Running: /usr/local/bin/rsync_bpc --bpc-top-dir /mnt/backuppc
--bpc-host-name ltspc162 --bpc-share-name /home --bpc-bkup-num 151
--bpc-bkup-comp 3 --bpc-bkup-prevnum 150 --bpc-bkup-prevcomp 3
--bpc-bkup-inode0 172460 --bpc-attrib-new --bpc-log-level 6 -e
/usr/bin/ssh\ -q\ -x\ -l\ rbackup --rsync-path=/usr/bin/rsync --super
--recursive --protect-args --numeric-ids --perms --owner --group -D
--times --links --hard-links --delete --partial --log-format=log:\ %o\
%i\ %B\ %8U,%8G\ %9l\ %f%L --stats --include=/\*
--include=/\*/\[dD\]ev --include=/\*/\[dD\]evelopment
--include=/\*/\[Ww\]orkspace\* --include=/\*/\[Pp\]rojects\*
--include=/\*/svn --include=/\*/.\* --include=/\*/www
--include=/\*/script\* --exclude=/\* --exclude=/\*/\* ltspc162:/home/
/
incr backup started for directory /home
Xfer PIDs are now 90974
This is the rsync child about to exec /usr/local/bin/rsync_bpc
bpc_path_create(/mnt/backuppc/pc/ltspc162/151)
bpc_path_create(/mnt/backuppc/pc/ltspc162/150)
bpc_attrib_backwardCompat: WriteOldStyleAttribFile = 0, KeepOldAttribFiles = 0
rsync: opendir "/home/asafonov/.adobe" failed: Permission denied (13)
rsync: opendir "/home/asafonov/.ansible" failed: Permission denied (13)
rsync: opendir "/home/asafonov/.aptitude" failed: Permission denied (13)
rsync: opendir "/home/asafonov/.cache" failed: Permission denied (13)
rsync: opendir "/home/asafonov/.compiz" failed: Permission denied (13)
rsync: opendir "/home/asafonov/.config" failed: Permission denied (13)
rsync: opendir "/home/asafonov/.dbus" failed: Permission denied (13)
bpc_stat(/)
bpc_attrib_dirRead(/mnt/backuppc/pc/ltspc162/151//attrib); dirPath =
/mnt/backuppc/pc/ltspc162/151, attribFilePath = /attrib,
attribFileName = attrib
bpc_attrib_dirRead: Got attrib file
attrib_db10aa56d6122e87cf5472a8399d0ec9: digest =
db10aa56d6122e87cf5472a8399d0ec9, len = 16
bpc_lstat(/)
bpc_chdir(/)
Xfer PIDs are now 90974,90976
xferPids 90974,90976
G bpc_lstat(.)
IO error encountered -- skipping file deletion


2017-04-06 14:34 GMT+08:00 Craig Barratt <notifications@github.com>:

**Comment by AlexeySaff** [comment]
it seems it's completly different and not using sudo?

and also ignoring nice and ionice

new command from 4.x
Running: /usr/local/bin/rsync_bpc --bpc-top-dir /mnt/backuppc
--bpc-host-name gwdc2 --bpc-share-name /home --bpc-bkup-num 287
--bpc-bkup-comp 3 --bpc-bkup-prevnum -1 --bpc-bkup-prevcomp -1
--bpc-bkup-inode0 3135 --bpc-attrib-new --bpc-log-level 1 -e /usr/bin/ssh\
-q\ -x\ -l\ rbackup --rsync-path=/usr/bin/rsync --super --recursive
--protect-args --numeric-ids --perms --owner --group -D --times --links
--hard-links --delete --partial --log-format=log:\ %o\ %i\ %B\ %8U,%8G\
%9l\ %f%L --stats --checksum --include=/ gwdc2:/home/ /
full backup started for directory /home

old command from 3.x
Running: /usr/bin/ssh -q -x -l rbackup gwdc2 nice -n 19 ionice -n 7 sudo
/usr/bin/rsync --server --sender --numeric-ids --perms --owner --group -D
--links --hard-links --times --block-size=2048 --recursive --specials
--one-file-system --ignore-times . /home/

2017-04-10 16:20 GMT+08:00 alexey safonov <alexeysaff@gmail.com>:

**Comment by AlexeySaff** [comment]
how to make similar config in new version?
$Conf{RsyncClientCmd} = '$sshPath -q -x -l rbackup $host nice -n 19 ionice -n 7 sudo $rsyncPath $argList+';


it seems this settings was changed

**Comment by AlexeySaff** [comment]
ok resolved. if you need sudo and NICE 
put it as RSyncClientPath = nice -n 19 ionice -n 7 sudo /usr/bin/rsync

it's better to add such to documentation for upgrade as it's completly different from v3

**Comment by AlexeySaff** [comment]
there are still some strange behaviour
for example it seems that rsync_bcp ignores --one-file-system and tries to backup nfs mounted dirs

in v3 it was possible to create --exclude-from=file_name_on_backuppc_server and not on client

**Comment by craigbarratt** [comment]
--one-file-system definitely should work.  Let me look into --exclude-from.

**Comment by AlexeySaff** [comment]
I've think the problem is that i ran one time without --one-file-system and
backuppc backup my mounted folder.

now when i add this option it is not backup mounted dirs, but still show
old files that was on first run. May be it's better to add --one-file-system
as default initial setting ?



2017-04-17 7:25 GMT+08:00 Craig Barratt <notifications@github.com>:

**Comment by AlexeySaff** [comment]
I was right. Once i remove old backups and create new one from scratch with
-x option, there are no more NFS data. So it's because in new version even
if we do full backup, it's merge all data from previous backup.
same with --exclude-from. Example:

i have an .iso files in one dir. Create full backup and see all *.iso in
backup - good
then i add *.iso in --exclude-from file and make full or incremental backup
again. and see same iso in backup (because they was in previous backup).

i like an idea of new versions in V4 , but V3 was simpler and more
predictive in work.

Alex

2017-04-18 9:45 GMT+08:00 alexey safonov <alexeysaff@gmail.com>:

**Comment by craigbarratt** [comment]
Try adding --delete-excluded to $Conf{RsyncArgs}.

**Comment by AlexeySaff** [comment]
thanks. it works.
not 100%, so it delete all local *.iso from backup as expected, but still
save old nfs backups (i think because of --one-file-system it doesn't check
NFS at all anymore)

sorry for my stupid questions. and thanks for great software

2017-04-18 12:20 GMT+08:00 Craig Barratt <notifications@github.com>:

**Comment by craigbarratt** [comment]
I've added --delete-excluded to the main conf/config.pl file, so it's now default.
