### ISSUE TITLE
FillKeepPeriod

### ISSUE THREAD

**Issue by hengesb** [backuppc/backuppc#88]
In the documentation of "FillCycle" the setting "FillKeepPeriod" is mentioned but there is no setting named this. Is this an error in documentation or is that setting really missing?

From Help:
more importantly, in V4+, deleting backups is done based on Fill/Unfilled,
    not whether the original backup was full/incremental.  If there aren't
    any filled backups (other than the most recent), then the **FillKeepPeriod**
    settings won't have any effect

**Comment by craigbarratt** [comment]
Thanks for pointing that out.  I changed it to $Conf{FullKeepCnt}.
