### ISSUE TITLE
SCGI + systemd not working

### ISSUE THREAD

**Issue by ngharo** [backuppc/backuppc#95]
I provisioned a new backuppc server (built from git tag 4.1.1) on Debian 8.  I'm using the systemd unit file for starting the BackupPC daemon.

Problem is the SCGI listener doesn't respond when BackupPC is started via systemctl using the included unit file.  This is the commit that broke it 51e579bae854ec78573cff9c3ff36ee589286502.  I reverted to Type=forking which fixes the problem.

Most simple test case is to enable SCGI in the config by setting the port, e.g. `$Conf{SCGIServerPort} = 7000;`

Then start the backuppc.service via systemctl:
`systemctl start backuppc.service`

At this point, you should have at least one `BackupPC_Admin_SCGI` process running, listening on port 7000.

You can test it's responding to requests by using curl:
`curl localhost:7000`
Expected output is an immediate empty reply
`curl: (52) Empty reply from server` (this is OK because curl doesn't speak SCGI)

**Comment by craigbarratt** [comment]
Thanks for reporting this and providing the key clues.  I found the bug in BackupPC_Admin_SCGI and just pushed it to git.
